"""K 循环底稿公式 surfacing 目录（与各 useK{n}* composable 同源，不臆造）。

对齐 E1 标准（wp_formula._E1_SHEET_FORMULAS）与 D 循环（wp_surfaced_d）：把「专属组件
底稿」（数据存 checklist_responses、无 wp_formula 网格记录）的取数/计算/逻辑审核公式以
只读条目 surface 到公式管理中心，让每张 sheet 都能体现其取数逻辑。

每条公式均可在对应前端 composable 中找到依据（calc 函数 / 跨 sheet 键 / TB 核对 /
合计聚合 / 借贷平衡 / 检查比例 / CAS 判断）；找不到依据的 sheet 不写（宁缺勿造）。

分类只用三种：
  - 取数     跨 sheet / 从明细带入 / 抽凭回填 / 从序时账取数 / 附注自动取数
  - 计算     审定=未审+AJE+RJE、期末余额、变动额/率、合计、坏账测算、ECL、摊销、
             检查比例、保修率、现值折现、孰低净额等
  - logic_check  TB 核对、审定↔明细勾稽、借贷平衡、检查比例阈值、CAS 判断、三角勾稽等

科目方向（从各 useK{n}* composable 的 ACCOUNT_CODE / writebackTB 常量核实）：
  K1 其他应收款(1221 资产借方) + 坏账准备(1231 备抵)
  K2 其他流动资产(1231 资产借方)
  K3 其他应付款(2241 负债贷方)
  K4 其他流动负债(2245 负债贷方)
  K5 预计负债(2701 负债贷方，CAS13 或有事项)
  K6 持有待售(1481 资产借方 + 2605 负债贷方，CAS42 孰低)
  K7 递延收益(2401 负债贷方，CAS16 政府补助)
  K8 销售费用(6601 损益借方，取发生额=借−贷)
  K9 管理费用(6602 损益借方，取发生额=借−贷)
  K10 其他收益(6117 损益贷方，取发生额=贷−借)
  K11 资产减值损失(6701 损益借方，取发生额=借−贷)
  K12 营业外收入(6301 损益贷方，取发生额=贷−借)
  K13 营业外支出(6711 损益借方，取发生额=借−贷)
"""
from __future__ import annotations

SheetFormula = tuple[str, str, str, str, str]  # (项目名, 公式, 分类, 说明, 来源)

CATALOG: dict[str, dict[str, list[SheetFormula]]] = {
    # ═══════════════════════════════════════════════════════════════════════
    # K1 其他应收款（资产借方 1221 + 坏账准备 1231；含 ECL 三阶段 / 坏账测算 / 凭证检查）
    # ═══════════════════════════════════════════════════════════════════════
    "K1": {
        "K1-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各分类行审定金额（calcAuditedAmount）", "useK1Adjudication / useK1FormulaEngine.calcAuditedAmount"),
            ("其他应收款原值期末", "期初 + 借方 − 贷方", "计算",
             "资产类期末（buildRow / calcAssetEndBalance）", "useK1Adjudication / calcAssetEndBalance"),
            ("坏账准备期末", "期初 + 贷方 − 借方", "计算",
             "备抵类期末（buildRow / calcContraEndBalance）", "useK1Adjudication / calcContraEndBalance"),
            ("其他应收款净值", "应收原值审定 − 坏账准备审定", "计算",
             "净值行（buildNetRows / calcNetValue）", "useK1Adjudication / calcNetValue"),
            ("合计", "Σ 各分类行", "计算",
             "组合/账龄/性质区块合计（buildSubtotal / calcSubtotal）", "useK1Adjudication / calcSubtotal"),
            ("变动额", "本期审定 − 上期审定", "计算",
             "changeAmount（_round2）", "useK1Adjudication"),
            ("变动率", "(本期审定 − 上期审定) ÷ |上期审定|", "计算",
             "changeRate（calcChangeRate）", "useK1Adjudication / calcChangeRate"),
            ("三角勾稽差额", "(期初 + 借方 − 贷方) − 期末", "logic_check",
             "reconciliation（calcTriangleReconciliation，差<0.01 平衡）", "useK1Adjudication / calcTriangleReconciliation"),
            ("试算平衡表数核对", "审定合计 − TB 审定数(1221 / 坏账准备 1231)", "logic_check",
             "tbReconciliation（receivableDiff / badDebtDiff）", "useK1Adjudication / tbReconciliation"),
            ("与经审计财报核对", "其他应收款净值审定 − (应收利息 + 应收股利 + 其他)", "logic_check",
             "fsReconciliation", "useK1Adjudication / fsReconciliation"),
            ("变动率阈值告警", "|变动率| ≥ 30% 且未填原因", "logic_check",
             "varianceAlerts（K1_VARIANCE_THRESHOLD）", "useK1Adjudication / varianceAlerts"),
            ("组合交叉验证", "组合区块与明细一致性核对", "logic_check",
             "comboCrossCheck（computeK11ComboCrossCheck）", "useK1Adjudication / k1AdjudicationCross"),
            ("从明细带入未审数", "按组合/账龄/性质对 K1-2 明细 SUMIF 聚合", "取数",
             "syncUnadjFromK12（aggregateK12ForK11）", "useK1Adjudication / syncUnadjFromK12"),
            ("TB预填未审数", "从 tb_balance 子科目按分类预填期初/期末未审", "取数",
             "applyAdjudicationPrefill（render adjudication_prefill）", "useK1Adjudication / applyAdjudicationPrefill"),
            ("从K1-4回写AJE/RJE", "1221→原值行、1231→坏账行，按未审数权重分摊", "取数",
             "syncEndAdjFromK14（applyK14NetsToK11）", "useK1Adjudication / k1AdjK11Writeback"),
            ("审定↔明细勾稽", "K1-1 审定合计 − K1-2 明细期末小计", "logic_check",
             "adjudicationVsDetail（|diff|<0.01）", "useK1CrossSheet / adjudicationVsDetail"),
            ("审定AJE/RJE↔K1-4净额勾稽", "K1-1 逐行 AJE/RJE 合计 − K1-4 1221/1231 净额", "logic_check",
             "adjudicationVsK14", "useK1CrossSheet / adjudicationVsK14"),
        ],
        "K1-2": [
            ("账龄合计", "agingAudited 各账龄段之和", "计算",
             "_calcAgingTotal（calcSubtotal）", "useK1Detail / _calcAgingTotal"),
            ("净值", "期末余额 − 坏账准备", "计算",
             "netValue（updateRow 自动重算）", "useK1Detail"),
            ("3年以上占比", "3年以上金额 ÷ 期末合计", "计算",
             "stats.over3YearRatio（calcProportion）", "useK1Detail / calcProportion"),
            ("账龄勾稽", "账龄合计 vs 期末余额（差>0.01 告警）", "logic_check",
             "agingMismatches", "useK1Detail / agingMismatches"),
        ],
        "K1-3": [
            ("期初审定", "期初账面 + 期初账项调整", "计算",
             "recalcK1BadDebtMainRow（calcAuditedAmount）", "useK1BadDebt / recalcK1BadDebtMainRow"),
            ("期末账面", "期初审定 + 计提 + 其他增加 − 转回 − 核销 − 其他减少", "计算",
             "recalcK1BadDebtMainRow", "useK1BadDebt / recalcK1BadDebtMainRow"),
            ("期末审定", "期末账面 + 期末账项调整", "计算",
             "recalcK1BadDebtMainRow", "useK1BadDebt / recalcK1BadDebtMainRow"),
            ("分类合计", "单项/组合/合计逐列汇总", "计算",
             "recomputeCategoryTotals", "useK1BadDebt / recomputeCategoryTotals"),
            ("三阶段期末余额", "Σ 各变动行(期初/迁徙/计提/转回/核销/汇兑/其他)", "计算",
             "recalcStageClosing", "useK1BadDebt / recalcStageClosing"),
            ("坏账测算勾稽", "K1-8 测算应计提 − 本表期末坏账合计", "logic_check",
             "crossValidation（|diff|<0.01）", "useK1BadDebt / crossValidation"),
            ("从(一)同步至(二)", "(一)合计的计提/转回/核销带入三阶段行", "取数",
             "syncStageFromMain", "useK1BadDebt / syncStageFromMain"),
        ],
        "K1-4": [
            ("借贷平衡", "借方调整合计 − 贷方调整合计", "logic_check",
             "balanceCheck（|diff|<0.01）", "useK1Adjustment / balanceCheck"),
            ("1221 AJE净额", "Σ(借−贷)｜账项调整且科目 1221", "计算",
             "receivableAjeNet", "useK1Adjustment / receivableAjeNet"),
            ("1221 RJE净额", "Σ(借−贷)｜报表调整且科目 1221", "计算",
             "receivableRjeNet", "useK1Adjustment / receivableRjeNet"),
            ("坏账准备1231 AJE/RJE净额", "Σ(借−贷)｜科目 1231 按调整类别", "计算",
             "badDebtAjeNet / badDebtRjeNet", "useK1Adjustment / badDebtAjeNet"),
            ("回写K1-1", "净额按未审权重回写 K1-1 组合行 AJE/RJE", "取数",
             "publishAndSync → applyK14NetsToK11", "useK1Adjustment / k1AdjK11Writeback"),
            ("推送A13错报", "账项调整行推送至 A13 未更正错报汇总", "logic_check",
             "pushToA13（eventBus a13:push-misstatement）", "useK1Adjustment / pushToA13"),
            ("从中央调整模块同步", "拉取含 1221 分录导入本表", "取数",
             "syncFromAdjustmentModule", "useK1Adjustment / syncFromAdjustmentModule"),
        ],
        "K1-5": [
            ("期末未审", "期初 + 借方 − 贷方", "计算",
             "computeRow（calcAssetEndBalance）", "useK1LargeAmountSheet / calcAssetEndBalance"),
            ("账面价值", "期末未审 − 坏账准备", "计算",
             "computeRow（calcNetValue）", "useK1LargeAmountSheet / calcNetValue"),
            ("占比", "单户期末未审 ÷ K1-2 明细合计", "计算",
             "computeRow（calcProportion）", "useK1LargeAmountSheet / calcProportion"),
            ("从K1-2取前十名", "按期末余额降序取前 10 户(排除合并范围关联方)", "取数",
             "importTopFromDetail（extractTopLargeFromK1Detail）", "useK1LargeAmountSheet / importTopFromDetail"),
            ("期后收款取数", "序时账 1221 贷方按债务人归集(基准日后 N 月)", "取数",
             "importPostPaymentFromLedger", "useK1LargeAmountSheet / fetchK1PostPaymentFromLedger"),
            ("B19关联方匹配", "债务人名称匹配 B19 清单标记关联方", "logic_check",
             "applyB19Match / b19SuspectRows", "useK1LargeAmountSheet / applyB19MatchToLargeRows"),
        ],
        "K1-6": [
            ("组合划分与K1-8一致性", "K1-6 组合基础 vs K1-8 测算组合名称核对", "logic_check",
             "k18ComboConsistency（computeK16K18ComboConsistency）", "useK1PolicyCheck / k18ComboConsistency"),
            ("从K1-8同步组合", "按 K1-8 组合名称合并到本表组合划分", "取数",
             "syncCombosFromK18（mergeCombosFromK18）", "useK1PolicyCheck / syncCombosFromK18"),
            ("K2账龄损失率↔K1-8勾稽", "拉取/回写 K2 历史损失率与 K1-8 测算率", "取数",
             "pullK2RatesFromK18Sheet / pushK2RatesToK18", "useK1PolicyCheck / k1PolicyCrossHelpers"),
            ("完成度评分", "组合/政策/历史损失/前瞻性/同业/说明/结论 完成项计数", "logic_check",
             "completionScore", "useK1PolicyCheck / completionScore"),
        ],
        "K1-7": [
            ("信用风险显著增加(SICR)", "13 项风险迹象任一为「是」", "logic_check",
             "calcK1HasSignificantIncrease", "useK1StageCheck / calcK1HasSignificantIncrease"),
            ("较低信用风险豁免", "3 项条件全部为「是」", "logic_check",
             "calcK1HasLowCreditRisk", "useK1StageCheck / calcK1HasLowCreditRisk"),
            ("已减值判定", "6 项已减值迹象任一为「是」", "logic_check",
             "calcK1HasCreditImpairment", "useK1StageCheck / calcK1HasCreditImpairment"),
            ("建议阶段", "含较低信用风险豁免的三阶段判定", "计算",
             "recalcRow（determineStageWithExemption）", "useK1StageCheck / determineStageWithExemption"),
            ("企业↔审计阶段不一致", "companyStage ≠ 审计 stage", "logic_check",
             "inconsistentRows / summary.inconsistentCount", "useK1StageCheck / inconsistentRows"),
            ("阶段迁移未填说明", "priorStage ≠ stage 且变动说明为空", "logic_check",
             "stageMigrationWarnings", "useK1StageCheck / stageMigrationWarnings"),
            ("从K1-2带入", "往来对象与期末余额、企业阶段带入", "取数",
             "applyFromK12Detail", "useK1StageCheck / applyFromK12Detail"),
            ("从K1-10逾期升级阶段", "按逾期天数/无法收回/涉诉自动勾选并升级(只升不降)", "取数",
             "applyFromK110（mergeOverdueStageHintsToK7）", "useK1StageCheck / applyFromK110"),
            ("不一致→K1-4调整草稿", "企业≠审计阶段生成坏账准备 1231 调整备忘", "logic_check",
             "buildInconsistencyAdjDrafts（buildK1StageInconsistencyAdjDrafts）", "useK1StageCheck"),
        ],
        "K1-8": [
            ("应计提", "审定余额① × 损失率②", "计算",
             "calcExpected（recalcLine）", "useK1BadDebtCalcSheet / calcExpected"),
            ("差异", "应计提③ − 账面准备④", "计算",
             "calcDiff", "useK1BadDebtCalcSheet / calcDiff"),
            ("ECL", "EAD × PD × LGD", "计算",
             "组合预期信用损失（负值兜底 0）", "useK1BadDebtCalcEngine / calcECL"),
            ("账龄损失", "余额 × 损失率", "计算",
             "calcAgingLoss", "useK1BadDebtCalcEngine / calcAgingLoss"),
            ("合计", "单项 + 信用期组合 + 账龄组合 逐列汇总", "计算",
             "sumLines / grandTotal", "useK1BadDebtCalcSheet / grandTotal"),
            ("测算差异告警", "|测算应计提合计 − 账面准备合计| ≥ 0.01", "logic_check",
             "diffAlert", "useK1BadDebtCalcSheet / diffAlert"),
            ("从K1-2带入余额", "按往来对象/账龄段汇总审定余额", "取数",
             "pullBalancesFromK1Detail", "useK1BadDebtCalcSheet / pullBalancesFromK1Detail"),
        ],
        "K1-9": [
            ("转回合计", "Σ 各转回行金额", "计算",
             "reversalTotal", "useK1WriteoffCheck / reversalTotal"),
            ("核销合计", "Σ 各核销行金额", "计算",
             "writeoffTotal", "useK1WriteoffCheck / writeoffTotal"),
            ("转回勾稽", "本表转回合计 − K1-3 本期转回合计", "logic_check",
             "reversalConsistencyWarning", "useK1WriteoffCheck / reversalConsistencyWarning"),
            ("核销勾稽", "本表核销合计 − K1-3 本期核销合计", "logic_check",
             "writeoffConsistencyWarning", "useK1WriteoffCheck / writeoffConsistencyWarning"),
            ("转回超原计提预警", "转回金额 > 原累计计提", "logic_check",
             "isReversalExceedsProvision", "useK1WriteoffCheck / isReversalExceedsProvision"),
            ("从K1-3导入转回/核销", "K1-3 本期有转回/核销的明细行同名合并", "取数",
             "importFromK13（importWriteoffFromK13）", "useK1WriteoffCheck / importFromK13"),
            ("从K1-11标记关联方核销", "按 K1-11 关联方名录标记核销行关联方", "取数",
             "syncRelatedPartyFromK11", "useK1WriteoffCheck / syncRelatedPartyFromK11"),
        ],
        "K1-10": [
            ("期末余额", "期初 + 借方 − 贷方", "计算",
             "computeRow（calcAssetEndBalance）", "useK1OverdueCheck / calcAssetEndBalance"),
            ("审定余额", "期末余额 − 坏账准备", "计算",
             "syncAuditedFromNet（calcNetValue）", "useK1OverdueCheck / calcNetValue"),
            ("合计", "Σ 各行(期初/借/贷/期末/准备/审定/期后收款)", "计算",
             "summary（calcSubtotal）", "useK1OverdueCheck / summary"),
            ("坏账计提勾稽", "本表计提 vs K1-3 坏账准备(按债务人)", "logic_check",
             "provisionReconciliation（computeK110ProvisionReconciliation）", "useK1OverdueCheck / provisionReconciliation"),
            ("从K1-2导入超1年挂账", "账龄超 1 年往来对象带入", "取数",
             "importFromDetail（filterLongTermFromK1Detail）", "useK1OverdueCheck / importFromDetail"),
            ("期后收款取数", "序时账 1221 贷方按债务人归集", "取数",
             "importPostPaymentFromLedger", "useK1OverdueCheck / fetchK1PostPaymentFromLedger"),
            ("向K1-7写阶段升级信号", "逾期信号写入 K1-7 阶段(只升不降)", "取数",
             "syncStagesToK17（mergeOverdueStageHintsToK7）", "useK1OverdueCheck / syncStagesToK17"),
        ],
        "K1-11": [
            ("期末余额", "期初 + 借方 − 贷方", "计算",
             "recalcK1RelatedPartyRow（calcAssetEndBalance）", "useK1RelatedParty / recalcK1RelatedPartyRow"),
            ("账面价值", "期末余额 − 坏账准备", "计算",
             "bookValueOf（calcNetValue）", "useK1RelatedParty / bookValueOf"),
            ("合计", "Σ 各关联方行", "计算",
             "computeK1RelatedPartySubtotal", "useK1RelatedParty / computeK1RelatedPartySubtotal"),
            ("三角勾稽", "期末 − (期初 + 借 − 贷)", "logic_check",
             "rowBalanceGap（calcTriangleReconciliation）", "useK1RelatedParty / rowBalanceGap"),
            ("从K1-2关联方行合并", "关联关系≠否的明细行按名合并带入", "取数",
             "mergeRelatedPartyFromK1Detail", "useK1RelatedParty / mergeRelatedPartyFromK1Detail"),
            ("B19清单完整性", "B19 清单有而本表缺的关联方(漏列)", "logic_check",
             "computeK1MissingRelatedParties", "useK1RelatedParty / computeMissingRelatedParties"),
            ("B19匹配建议关联关系", "债务人名匹配 B19 → 建议关联关系", "logic_check",
             "matchK1RelatedPartyFromRegistry", "useK1RelatedParty / matchK1RelatedPartyFromRegistry"),
        ],
        "K1-12": [
            ("抽样总体", "测试总体(借+贷发生额) − 特定样本", "计算",
             "computeK1SamplingPopulation", "useK1VoucherCheck / computeK1SamplingPopulation"),
            ("检查比例", "检查金额 ÷ 账面发生额(本期借方/贷方/期末余额)", "计算",
             "checkRatios", "useK1VoucherCheck / checkRatios"),
            ("检查比例偏低告警", "检查比例 < 30% 且账面金额>0", "logic_check",
             "lowRatioWarnings", "useK1VoucherCheck / lowRatioWarnings"),
            ("样本量偏差", "实际检查笔数 < 计划样本量 → 需扩样", "logic_check",
             "sampleSizeDeviation", "useK1VoucherCheck / sampleSizeDeviation"),
            ("五项核对完整性", "凭证行五项核对是否全部勾选", "logic_check",
             "isK1VoucherRowChecksComplete / evaluateK1VoucherChecks", "useK1VoucherCheck / evaluateK1VoucherChecks"),
            ("从K1-1/K1-2带入发生额", "带入账面本期借/贷发生额与期末余额(检查比例分母)", "取数",
             "applyFromK1Sheets（pullK1BookAmounts）", "useK1VoucherCheck / applyFromK1Sheets"),
            ("从K1-5带入特定样本", "K1-5 大额户作为特定样本(全部测试)", "取数",
             "applyFromK1LargeAmount", "useK1VoucherCheck / applyFromK1LargeAmount"),
            ("抽凭引擎回填", "抽凭样本(科目 1221)映射为凭证检查行", "取数",
             "fillFromSamples", "useK1VoucherCheck / fillFromSamples"),
            ("异常凭证→K1-4草稿", "异常凭证生成 1221 调整备忘草稿", "logic_check",
             "buildAbnormalAdjDrafts", "useK1VoucherCheck / buildAbnormalAdjDrafts"),
        ],
        "附注上市": [
            ("账龄勾稽", "账龄披露合计 vs K1-1 应收原值审定", "logic_check",
             "agingTieOut（calcAgingTieOut）", "useK1DisclosureListed / agingTieOut"),
            ("性质勾稽", "性质披露合计 vs K1-1 应收原值审定", "logic_check",
             "natureTieOut（calcNatureTieOut）", "useK1DisclosureListed / natureTieOut"),
            ("减值勾稽", "账龄坏账准备 vs 三阶段 Stage1 期末", "logic_check",
             "provisionTieOut", "useK1DisclosureListed / provisionTieOut"),
            ("前五名占比", "单户期末余额 ÷ 前五名合计", "计算",
             "recalcTop5Proportions", "useK1DisclosureListed / recalcTop5Proportions"),
            ("ECL三阶段重算", "各阶段 provision = balance × eclRate", "计算",
             "recomputeStageEclRows", "useK1DisclosureListed / recomputeStageEclRows"),
            ("自动取数", "从 K1-1/K1-2/K1-3/K1-9 同步账龄/性质/三阶段/转回核销", "取数",
             "refreshFromSources（autoFillFromK1Sources）", "useK1DisclosureListed / autoFillFromK1Sources"),
            ("同步至附注模块", "披露表数据 sync-from-workpaper 至附注", "取数",
             "syncToNotes（buildK1ListedSyncPayloads）", "useK1DisclosureListed / syncToNotes"),
        ],
        "附注国企": [
            ("账龄勾稽", "账龄披露合计 vs K1-1 应收原值审定", "logic_check",
             "agingTieOut（calcAgingTieOut）", "useK1DisclosureSoe / agingTieOut"),
            ("计提方法勾稽", "计提方法披露合计 vs K1-1 应收原值审定", "logic_check",
             "methodTieOut（calcMethodTieOut）", "useK1DisclosureSoe / methodTieOut"),
            ("余额三阶段勾稽", "余额三阶段合计 vs K1-1 应收原值审定", "logic_check",
             "balanceStageTieOut（calcBalanceStageTieOut）", "useK1DisclosureSoe / balanceStageTieOut"),
            ("减值勾稽", "账龄坏账准备 vs ECL 三阶段期末合计", "logic_check",
             "provisionTieOut", "useK1DisclosureSoe / provisionTieOut"),
            ("单项减值率", "单项减值准备 ÷ 单项余额", "计算",
             "updateIndividualRow（eclRate）", "useK1DisclosureSoe / updateIndividualRow"),
            ("自动取数", "从 K1-1/K1-2/K1-3/K1-7/K1-9 同步", "取数",
             "refreshFromSources（autoFillSoeFromK1Sources）", "useK1DisclosureSoe / autoFillSoeFromK1Sources"),
            ("同步至附注模块", "披露表数据 sync-from-workpaper 至附注", "取数",
             "syncToNotes（buildK1SoeSyncPayloads）", "useK1DisclosureSoe / syncToNotes"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K2 其他流动资产（资产借方 1231；含合同取得成本 / 摊销测算）
    # ═══════════════════════════════════════════════════════════════════════
    "K2": {
        "K2-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "buildRow（calcAuditedAmount）", "useK2Adjudication / useK2FormulaEngine.calcAuditedAmount"),
            ("期末余额", "期初 + 借方 − 贷方", "计算",
             "资产类 1231 期末（calcAssetEndBalance）", "useK2Adjudication / calcAssetEndBalance"),
            ("合计", "Σ 8 个固定明细行", "计算",
             "subtotalRow（calcSubtotal）", "useK2Adjudication / calcSubtotal"),
            ("变动率", "(本期审定 − 上期审定) ÷ |上期审定| × 100", "计算",
             "buildRow（calcChangeRate）", "useK2Adjudication / calcChangeRate"),
            ("三角勾稽差额", "期末 − (期初 + 借方 − 贷方)", "logic_check",
             "reconciliation（calcTriangleReconciliation）", "useK2Adjudication / calcTriangleReconciliation"),
            ("审定↔明细勾稽", "K2-1 审定合计 − K2-2 明细期末合计", "logic_check",
             "adjudicationVsDetail（|diff|<0.01）", "useK2CrossSheet / adjudicationVsDetail"),
        ],
        "K2-2": [
            ("期末余额", "期初 + 增加 − 减少", "计算",
             "_recalcRow（calcAssetEndBalance）", "useK2Detail / calcAssetEndBalance"),
            ("合计", "Σ 各行(期初/增/减/期末)", "计算",
             "subtotals（calcSubtotal）", "useK2Detail / subtotals"),
        ],
        "K2-4": [
            ("期末余额", "期初 + 增加 − 摊销", "计算",
             "_recalcRow（calcAssetEndBalance）", "useK2ContractCost / calcAssetEndBalance"),
            ("合计", "Σ 各行(合同金额/期初/增/摊销/期末)", "计算",
             "subtotals（calcSubtotal）", "useK2ContractCost / subtotals"),
            ("CAS14资本化判断", "增量成本 ∧ 预期可收回 ∧ 与合同直接相关", "logic_check",
             "capitalizationSuggestions", "useK2ContractCost / capitalizationSuggestions"),
            ("企业摊销↔测算勾稽", "K2-4 企业摊销合计 − K2-5 测算摊销合计", "logic_check",
             "contractCostVsAmort（|diff|<0.01）", "useK2CrossSheet / contractCostVsAmort"),
        ],
        "K2-5": [
            ("直线法摊销", "取得成本 ÷ 摊销期总期数 × 本期期数", "计算",
             "calcStraightLineAmort（总期=0 兜底 0）", "useK2Amortization / useK2AmortizationEngine.calcStraightLineAmort"),
            ("进度法摊销", "取得成本 × (本期进度 − 上期进度)", "计算",
             "calcProgressAmort（进度回退兜底 0）", "useK2Amortization / calcProgressAmort"),
            ("摊余成本", "取得成本 − 累计摊销", "计算",
             "calcAmortizedBalance", "useK2Amortization / calcAmortizedBalance"),
            ("摊销差异", "测算摊销 − 企业账面摊销", "计算",
             "calcAmortVariance", "useK2Amortization / calcAmortVariance"),
            ("合计", "Σ 各行(成本/测算/累计/摊余/企业/差异)", "计算",
             "subtotals（calcSubtotal）", "useK2Amortization / subtotals"),
            ("差异超重要性水平高亮", "|差异| > 重要性水平", "logic_check",
             "varianceExceedRows", "useK2Amortization / varianceExceedRows"),
        ],
        "K2-6": [
            ("分类正确性/流动性/可回收性/资本化合理性判定", "各检查项「合规/不合规/不适用」点选", "logic_check",
             "checkItems（K2_CHECK_DEFINITIONS 四项）", "useK2Check / checkItems"),
            ("存在不合规项高亮", "不合规项数 > 0", "logic_check",
             "summary.hasNonCompliant", "useK2Check / summary"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K3 其他应付款（负债贷方 2241；含性质/账龄双维度 / 大额 / 关联方 / 凭证检查）
    # ═══════════════════════════════════════════════════════════════════════
    "K3": {
        "K3-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "buildRow（calcAuditedAmount）", "useK3Adjudication / useK3FormulaEngine.calcAuditedAmount"),
            ("期末余额", "期初 + 贷方 − 借方", "计算",
             "负债类 2241 期末（calcLiabilityEndBalance）", "useK3Adjudication / calcLiabilityEndBalance"),
            ("按性质分类合计", "Σ 保证金/往来款/代收代付/其他", "计算",
             "natureSubtotal（calcSubtotal）", "useK3Adjudication / natureSubtotal"),
            ("按账龄分类合计", "Σ 动态账龄段各行", "计算",
             "agingSubtotal（calcSubtotal）", "useK3Adjudication / agingSubtotal"),
            ("变动率", "(本期审定 − 上期审定) ÷ 上期审定", "计算",
             "buildRow（calcChangeRate，上期0→特判）", "useK3Adjudication / calcChangeRate"),
            ("三角勾稽差额", "期末 − (期初 + 贷方 − 借方)", "logic_check",
             "reconciliation（calcTriangleReconciliation）", "useK3Adjudication / calcTriangleReconciliation"),
            ("TB预填未审数", "无持久化时 tbData.unadjusted2241 seed 至性质行", "取数",
             "seedFromTbIfEmpty（手工优先不覆盖）", "useK3Adjudication / seedFromTbIfEmpty"),
            ("审定↔明细勾稽", "K3-1 审定合计 − K3-2 明细期末合计(完整性关注)", "logic_check",
             "adjudicationVsDetail（|diff|<0.01）", "useK3CrossSheet / adjudicationVsDetail"),
        ],
        "K3-2": [
            ("期末余额", "期初 + 贷方(增加) − 借方(减少)", "计算",
             "_recalcRow（calcLiabilityEndBalance）", "useK3Detail / calcLiabilityEndBalance"),
            ("账龄合计", "agingAudited 各账龄段之和(应=期末余额)", "计算",
             "_recalcRow（calcSubtotal）", "useK3Detail / _recalcRow"),
            ("合计", "Σ 各行(期初/增/减/期末/各账龄段)", "计算",
             "subtotals（calcSubtotal）", "useK3Detail / subtotals"),
            ("3年以上账龄笔数/金额", "3年以上账龄行数与金额合计(供 K3-5)", "计算",
             "getAgingOver3YCount / getAgingOver3YTotal", "useK3Detail / getAgingOver3YCount"),
            ("大额款项笔数/金额", "≥阈值(默认10万)行数与金额合计(供 K3-4)", "计算",
             "getLargeAmountItems", "useK3Detail / getLargeAmountItems"),
        ],
        "K3-4": [
            ("占比", "单项期末余额 ÷ K3-2 明细合计", "计算",
             "_recalcProportions（calcProportion）", "useK3LargeAmount / calcProportion"),
            ("大额合计", "Σ 各大额行期末余额", "计算",
             "largeTotal（calcSubtotal）", "useK3LargeAmount / largeTotal"),
            ("大额合计占比", "大额合计 ÷ 明细合计", "计算",
             "largeTotalProportion（calcProportion）", "useK3LargeAmount / largeTotalProportion"),
            ("从K3-2筛选大额", "按阈值筛选并按金额降序带入", "取数",
             "initFromDetail", "useK3LargeAmount / initFromDetail"),
            ("大额→K3-4覆盖", "K3-2 大额款项笔数供大额分析完整覆盖核对", "logic_check",
             "largeAmountVsDetail", "useK3CrossSheet / largeAmountVsDetail"),
        ],
        "K3-5": [
            ("从K3-2带入长期挂账候选", "K3-2 中 3 年以上账龄有余额往来对象去重带入", "取数",
             "initLongOutstandingFromDetail", "useK3Checks / initLongOutstandingFromDetail"),
            ("处理结论判定", "应确认收入/应退回/应转营业外收入/正常挂账/待确定", "logic_check",
             "disposalConclusion（K3_DISPOSAL_CONCLUSIONS）", "useK3Checks / K3_DISPOSAL_CONCLUSIONS"),
            ("不合规摘要", "长期挂账行结论为「不合规/需处理」汇总", "logic_check",
             "nonComplianceSummary", "useK3Checks / nonComplianceSummary"),
            ("3年以上账龄→K3-5覆盖", "K3-2 3 年以上笔数供长期挂账完整覆盖核对", "logic_check",
             "longOutstandingVsDetail", "useK3CrossSheet / longOutstandingVsDetail"),
        ],
        "K3-6": [
            ("期末余额", "期初 + 贷方 − 借方", "计算",
             "_normalizeRelatedParty（负债类期末）", "useK3Checks / _normalizeRelatedParty"),
            ("从K3-2关联方行带入", "关联关系≠非关联的明细行去重带入", "取数",
             "initRelatedPartyFromDetail", "useK3Checks / initRelatedPartyFromDetail"),
            ("是否公允/披露/资金占用判定", "关联方逐行「是/否/待评估」判定", "logic_check",
             "relatedPartyRows.conclusion", "useK3Checks / relatedPartyRows"),
            ("不合规摘要", "关联方行结论为「不合规」汇总", "logic_check",
             "nonComplianceSummary", "useK3Checks / nonComplianceSummary"),
        ],
        "K3-7": [
            ("八项综合检查判定", "期末余额核对/大额异常/长期挂账/关联方完整性/反向截止/分类/计价/披露 逐项合规判定", "logic_check",
             "checkItems（DEFAULT_CHECK_ITEMS 八项）", "useK3Checks / checkItems"),
            ("反向截止测试", "期后偿付倒查未入账负债(是否属期前/期末是否已入账)", "logic_check",
             "reverseCutoffRows(belongsToPrior/isRecorded)", "useK3Checks / reverseCutoffRows"),
            ("不合规摘要", "K3-5/K3-6/K3-7 不合规项跨表汇总", "logic_check",
             "nonComplianceSummary / getIncompliantCount", "useK3Checks / nonComplianceSummary"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K4 其他流动负债（负债贷方 2245；含凭证检查 K4-4 复用 useK1VoucherCheck）
    # ═══════════════════════════════════════════════════════════════════════
    "K4": {
        "K4-1": [
            ("审定数", "未审 + AJE + RJE", "计算",
             "各行审定金额（calcAuditedAmount）", "useK4Adjudication / useK4FormulaEngine"),
            ("期末余额", "期初 + 贷方 − 借方", "计算",
             "负债类期末，2245 贷方（calcLiabilityEndBalance）", "useK4Adjudication / useK4FormulaEngine"),
            ("变动率", "(审定 − 上期审定) ÷ 上期审定", "计算",
             "变动率，除零特判（calcChangeRate）", "useK4Adjudication / useK4FormulaEngine"),
            ("合计", "Σ 各行", "计算",
             "审定表合计（calcSubtotal / subtotalRow）", "useK4Adjudication"),
            ("从K4-2明细带入", "审定数 = K4-2 明细期末合计", "取数",
             "审定数取自明细聚合（adjudicationFromDetail）", "useK4CrossSheet"),
            ("三角勾稽", "|期初 + 贷方 − 借方 − 期末| < 0.01", "logic_check",
             "负债类三角勾稽（calcTriangleReconciliation / reconciliation）", "useK4Adjudication / useK4FormulaEngine"),
            ("K4-1↔K4-2勾稽", "|K4-1 审定合计 − K4-2 明细期末合计| < 0.01", "logic_check",
             "审定表与明细交叉验证（adjudicationVsDetail）", "useK4CrossSheet"),
            ("TB回写2245", "审定合计 → trial_balance(2245)", "取数",
             "审定数合计回写试算表（getAuditedTotal）", "useK4Adjudication"),
        ],
        "K4-2": [
            ("期末余额", "期初 + 增加(贷) − 减少(借)", "计算",
             "负债类期末（calcLiabilityEndBalance）", "useK4Detail"),
            ("审定期初", "未审期初 + 期初调整", "计算",
             "审定期初（_recalcRow.auditedBegin）", "useK4Detail"),
            ("审定本期增加", "未审增加 + 账项调整增 + 重分类调整增", "计算",
             "审定增加（_recalcRow.auditedIncrease）", "useK4Detail"),
            ("审定本期减少", "未审减少 + 账项调整减 + 重分类调整减", "计算",
             "审定减少（_recalcRow.auditedDecrease）", "useK4Detail"),
            ("审定期末", "审定期初 + 审定增加 − 审定减少", "计算",
             "审定期末（_recalcRow.auditedEnd）", "useK4Detail"),
            ("明细合计", "Σ 各行", "计算",
             "底部统计合计（calcSubtotal / subtotals）", "useK4Detail"),
            ("明细期末合计→跨sheet", "Σ 期末余额 → K4-2-detail-total", "计算",
             "供审定表交叉验证（getDetailTotal）", "useK4Detail"),
        ],
        "K4-3": [
            ("从K4-4异常带入", "K4-4 检查表 abnormal 行 → 调整分录草稿", "取数",
             "异常凭证需调整项带入（importFromK44Abnormal / pendingAbnormalCount）", "K4TabAdjustment"),
        ],
        "K4-4": [
            ("检查比例", "检查金额 ÷ 本期发生额(仅本期借/贷，过滤期末余额行)", "计算",
             "凭证检查比例（checkRatios / k4CheckRatios）", "useK1VoucherCheck / K4TabCheck"),
            ("本期发生额账面", "取自 K4-1 审定表本期借/贷合计", "取数",
             "检查比例分母用 K4-1 审定数据覆盖账面（k4CheckRatios）", "K4TabCheck / useK4Adjudication"),
            ("检查比例阈值", "检查比例 < 30% → 告警", "logic_check",
             "比例偏低需扩样/说明（lowRatioWarnings）", "useK1VoucherCheck"),
            ("异常凭证汇总", "abnormal=true 的凭证行", "logic_check",
             "异常凭证标记（abnormalRows）", "useK1VoucherCheck"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K5 预计负债（负债贷方 2701；CAS13 或有事项：保修/弃置/诉讼 + 凭证检查）
    # ═══════════════════════════════════════════════════════════════════════
    "K5": {
        "K5-1": [
            ("审定数", "未审 + AJE + RJE", "计算",
             "审定金额（calcAuditedAmount）", "useK5Adjudication / useK5FormulaEngine"),
            ("期末余额", "期初 + 计提 − 转销", "计算",
             "负债类期末，2701 贷方（calcLiabilityEndBalance）", "useK5Adjudication / useK5FormulaEngine"),
            ("合计", "Σ 各类型行", "计算",
             "8 类型行合计（calcSubtotal / subtotalRow）", "useK5Adjudication"),
            ("差异", "审定合计 − 期末合计", "计算",
             "差异行（diffRow）", "useK5Adjudication"),
            ("三角勾稽", "|期末 − (期初 + 计提 − 转销)| < 0.01", "logic_check",
             "期末 vs 期初计提转销勾稽（reconciliation）", "useK5Adjudication / useK5FormulaEngine"),
            ("TB核对2701", "|审定合计 − TB 审定(2701)| < 0.01", "logic_check",
             "审定数与试算表核对（tbReconciliation）", "useK5Adjudication"),
            ("TB回写2701", "审定合计 → trial_balance(2701)", "取数",
             "审定合计回写 + substantive:adjudicated 事件（getAuditedTotal / publishAdjudicated）", "useK5Adjudication"),
        ],
        "K5-2": [
            ("期末余额", "期初 + 计提 − 转销", "计算",
             "负债类期末（calcLiabilityEndBalance）", "useK5Detail"),
            ("审定期末", "审定期初 + 审定增加 − 审定减少", "计算",
             "审定列（_recalcRow）", "useK5Detail"),
            ("最佳估计-区间中值", "(上限 + 下限) ÷ 2", "计算",
             "CAS13 区间中值（calcRangeMidpoint）", "useK5Detail / useK5BestEstimateEngine"),
            ("最佳估计-期望值", "Σ(各情形金额 × 概率)", "计算",
             "CAS13 期望值加权（calcExpectedValue）", "useK5Detail / useK5BestEstimateEngine"),
            ("CAS13或有事项判断", "很可能→确认 / 可能→披露 / 极小→不处理", "logic_check",
             "或有事项三级可能性映射（determineRecognition）", "useK5Detail / useK5ContingencyEngine"),
            ("明细合计", "Σ 各行", "计算",
             "明细合计（calcSubtotal / subtotals）", "useK5Detail"),
            ("明细期末合计→跨sheet", "Σ 期末 → K5-2-detail-total", "计算",
             "供审定表交叉验证（getDetailTotal）", "useK5Detail"),
        ],
        "K5-4": [
            ("应计提保修费", "计提基数(销售收入) × 历史保修率", "计算",
             "CAS13 保修支出测算（calcWarrantyProvision）", "useK5Warranty / useK5BestEstimateEngine"),
            ("差异金额", "应计提 − 账面已计提", "计算",
             "测算与账面差异（_recalcRow.variance）", "useK5Warranty"),
            ("期末余额", "期初 + 计提 − 使用", "计算",
             "负债类期末（calcLiabilityEndBalance）", "useK5Warranty"),
            ("3年平均保修率", "Σ(本期+前2年实际) ÷ Σ(本期+前2年收入)", "计算",
             "历史保修率对照（_recalcHistoryRow.avgRate）", "useK5Warranty"),
            ("K5-4↔K5-1勾稽", "|K5-4 质保期末合计 − K5-1 产品质保审定| < 0.01", "logic_check",
             "质保测算与审定交叉（crossCheck / warrantyVsAdjudication）", "useK5Warranty / useK5CrossSheet"),
        ],
        "K5-5": [
            ("弃置费用现值", "预计弃置支出 ÷ (1+折现率)^年数", "计算",
             "现值折现，rate/years<=0 兜底不折现（calcPresentValue）", "useK5Decommission / useK5BestEstimateEngine"),
            ("利息调整", "期初现值 × 折现率", "计算",
             "本期利息调整（_recalcRow）", "useK5Decommission"),
            ("期末余额", "期初 + 增加 + 利息调整", "计算",
             "弃置义务期末（_recalcRow）", "useK5Decommission"),
            ("K5-5↔K5-1勾稽", "|K5-5 弃置期末合计 − K5-1 弃置义务审定| < 0.01", "logic_check",
             "弃置现值与审定交叉（crossCheck / decommissionVsAdjudication）", "useK5Decommission / useK5CrossSheet"),
        ],
        "K5-6": [
            ("CAS13败诉可能性判断", "很可能→确认 / 可能→披露 / 极小→不处理", "logic_check",
             "诉讼三级判断 + recognition 派生（determineRecognition）", "useK5Litigation / useK5ContingencyEngine"),
            ("差异金额", "应承担赔偿(预计损失) − 已计提预计负债", "计算",
             "差异派生（_recalcRow.variance）", "useK5Litigation"),
            ("确认损失合计", "Σ recognition='recognize' 的预计损失", "计算",
             "仅很可能败诉计入预计负债（subtotals.recognizedLoss）", "useK5Litigation"),
            ("K5-6↔K5-1勾稽", "|K5-6 确认损失合计 − K5-1 未决诉讼审定| < 0.01", "logic_check",
             "诉讼损失与审定交叉（crossCheck / litigationVsAdjudication）", "useK5Litigation / useK5CrossSheet"),
        ],
        "K5-7": [
            ("检查比例", "检查金额 ÷ 本期发生额(本期借/贷/期末余额)", "计算",
             "凭证检查比例（checkRatios）", "useK1VoucherCheck / K5TabProvisionCheck"),
            ("检查比例阈值", "检查比例 < 30% → 告警", "logic_check",
             "比例偏低需扩样/说明（lowRatioWarnings）", "useK1VoucherCheck"),
            ("异常凭证汇总", "abnormal=true 的凭证行", "logic_check",
             "异常凭证标记（abnormalRows）", "useK1VoucherCheck"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K6 持有待售（资产借方 1481 + 负债贷方 2605；CAS42 孰低计量）
    # ═══════════════════════════════════════════════════════════════════════
    "K6": {
        "K6-1": [
            ("审定数", "未审 + AJE + RJE", "计算",
             "资产/负债双区块审定（calcAuditedAmount）", "useK6Adjudication / useK6FormulaEngine"),
            ("资产期末", "期初 + 增加 − 减少 − 减值", "计算",
             "持有待售资产期末，1481 借方（calcAssetPeriodEnd）", "useK6Adjudication / useK6FormulaEngine"),
            ("负债期末", "期初 + 增加 − 减少", "计算",
             "持有待售负债期末，2605 贷方（calcLiabilityPeriodEnd）", "useK6Adjudication / useK6FormulaEngine"),
            ("变动率", "(审定 − 上期) ÷ 上期", "计算",
             "变动率除零特判（calcVariationRate）", "useK6Adjudication / useK6FormulaEngine"),
            ("区块合计", "Σ 区块内各行", "计算",
             "资产/负债区块小计（calcSubtotal / buildSubtotal）", "useK6Adjudication"),
            ("资产区块三角勾稽", "|资产期末合计 − 资产审定合计| < 0.01", "logic_check",
             "资产双路径勾稽，任一为 0 视为平衡（assetReconciliation）", "useK6Adjudication"),
            ("负债区块三角勾稽", "|负债期末合计 − 负债审定合计| < 0.01", "logic_check",
             "负债双路径勾稽（liabilityReconciliation）", "useK6Adjudication"),
            ("K6-1↔K6-2勾稽", "|K6-1 审定合计 − K6-2 明细账面价值合计| < 0.01", "logic_check",
             "审定表与明细交叉（adjudicationVsDetail）", "useK6CrossSheet"),
            ("TB回写1481+2605", "资产审定→1481 / 负债审定→2605", "取数",
             "双科目回写（getAssetAuditedTotal / getLiabilityAuditedTotal）", "useK6Adjudication"),
        ],
        "K6-2": [
            ("账面价值", "账面原值 − 累计折旧摊销 − 减值准备", "计算",
             "账面价值（calcBookValue）", "useK6Detail / useK6FormulaEngine"),
            ("公允价值净额", "公允价值 − 出售费用", "计算",
             "公允净额（_recalcRow）", "useK6Detail"),
            ("明细合计", "Σ 各行", "计算",
             "底部统计合计（calcSubtotal / subtotals）", "useK6Detail"),
            ("账面价值合计→跨sheet", "Σ 账面价值 → K6-2-detail-total", "计算",
             "供审定表交叉验证（getDetailBookValueTotal）", "useK6Detail"),
        ],
        "K6-4": [
            ("公允价值优先级取值", "IF 销售协议价>0→协议价; ELSE IF 活跃市场价>0→市场价; ELSE 估计价", "计算",
             "公允价值三方法优先级（calcFairValuePriority）", "useK6InitialRecognition / useK6ImpairmentEngine"),
            ("公允价值净额", "公允价值 − 出售费用", "计算",
             "孰低净额，可为负（calcFairValueNet）", "useK6InitialRecognition / useK6ImpairmentEngine"),
            ("CAS42五条件分类", "五条件全满足→classified; 任一不满足→not_classified", "logic_check",
             "持有待售分类判断（classifyHeldForSale）", "useK6InitialRecognition / useK6ClassificationEngine"),
            ("资产/负债分区小计", "Σ 分类内 账面/公允净额", "计算",
             "估值表分区小计（calcSubtotal / valuationSubtotals）", "useK6InitialRecognition"),
        ],
        "K6-5": [
            ("公允价值净额", "公允价值 − 预计出售费用", "计算",
             "孰低净额（calcFairValueNet）", "useK6Impairment / useK6ImpairmentEngine"),
            ("减值金额", "MAX(0, 账面价值 − 公允价值净额)", "计算",
             "CAS42 孰低法减值（calcImpairment）", "useK6Impairment / useK6ImpairmentEngine"),
            ("本期应补提", "减值金额 − 已计提减值", "计算",
             "应补提/转回（calcAdditionalProvision）", "useK6Impairment / useK6ImpairmentEngine"),
            ("减值合计", "Σ 各行减值 → K6-5-impairment-total", "计算",
             "减值合计供交叉验证（getImpairmentTotal）", "useK6Impairment"),
            ("K6-5↔K6-1减值勾稽", "|K6-1 减值准备合计 − K6-5 减值合计| < 0.01", "logic_check",
             "减值测试与审定交叉（impairmentVsAdjudication）", "useK6CrossSheet"),
        ],
        "K6-6": [
            ("处置组减值(测算)", "MAX(0, 账面 − 公允净额)", "计算",
             "Part一处置组减值测算孰低（calcImpairment）", "useK6GroupImpairment / useK6ImpairmentEngine"),
            ("分摊比例", "组内资产账面 ÷ 组账面合计(不含商誉)", "计算",
             "分摊比例，组合计为 0 兜底 0（calcAllocationRatio）", "useK6GroupImpairment / useK6ImpairmentEngine"),
            ("商誉抵减+比例分摊", "先抵商誉 min(减值,商誉)；余额 × 分摊比例", "计算",
             "处置组减值先抵商誉再分摊（calcGroupImpairmentAllocation / recalcAll）", "useK6GroupImpairment / useK6ImpairmentEngine"),
            ("分摊后账面", "账面价值 − 分摊减值", "计算",
             "分摊后账面（recalcAll）", "useK6GroupImpairment"),
            ("CAS42减值下限校验", "分摊后账面 < MAX(公允净额,使用价值,0) → 告警(商誉行豁免)", "logic_check",
             "分摊后账面不得低于下限（belowFloor）", "useK6GroupImpairment"),
            ("Part一↔Part二勾稽", "|应计提减值合计 − 已分摊减值合计| < 0.01", "logic_check",
             "测算与分摊勾稽（reconciliation）", "useK6GroupImpairment"),
            ("K6-6↔K6-5勾稽", "|K6-5 处置组减值总额 − K6-6 分摊合计| < 0.01", "logic_check",
             "分摊合计与处置组减值交叉（groupVsImpairment）", "useK6CrossSheet"),
        ],
        "K6-7": [
            ("净额④", "① 划归前账面 − ② 假设折旧摊销 − ③ 假设减值", "计算",
             "CAS42 第22条(a)净额（_recalcItem.netValue）", "useK6NoLongerCheck"),
            ("调整后账面", "min(④净额, 可收回金额)", "计算",
             "不再满足持有待售孰低计量（_calcAdjusted）", "useK6NoLongerCheck"),
            ("调整差额", "调整后账面 − 现账面", "计算",
             "计入当期损益的差额（_recalcItem.adjustmentDiff）", "useK6NoLongerCheck"),
            ("资产/负债分区小计", "Σ 分类内 划归前账面/净额/调整后账面", "计算",
             "分区小计（calcSubtotal / subtotals）", "useK6NoLongerCheck"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K7 递延收益（负债贷方 2401；CAS16 政府补助 + 摊销测算 + 凭证检查）
    # ═══════════════════════════════════════════════════════════════════════
    "K7": {
        "K7-1": [
            ("审定数", "未审 + AJE + RJE", "计算",
             "审定金额（calcAuditedAmount）", "useK7Adjudication / useK7FormulaEngine"),
            ("期末余额", "期初 + 收到 − 分摊", "计算",
             "负债类期末，2401 贷方（calcLiabilityEndBalance）", "useK7Adjudication / useK7FormulaEngine"),
            ("变动率", "(审定 − 上期审定) ÷ |上期审定|", "计算",
             "变动率（_recalcRow.changeRate）", "useK7Adjudication"),
            ("与资产/与收益分组小计", "Σ 分组内各行", "计算",
             "分组小计 + 合计（calcSubtotal / _buildSubtotal / grandTotal）", "useK7Adjudication"),
            ("K7-1↔K7-2勾稽", "|K7-1 审定合计 − K7-2 明细期末合计| < 0.01", "logic_check",
             "审定表与明细交叉（reconciliation / adjudicationVsDetail）", "useK7Adjudication / useK7CrossSheet"),
            ("TB回写2401", "审定合计 → trial_balance(2401)", "取数",
             "审定合计回写（getAuditedTotal）", "useK7Adjudication"),
        ],
        "K7-2": [
            ("期末余额", "期初 + 收到 − 分摊", "计算",
             "负债类期末（calcLiabilityEndBalance）", "useK7Detail"),
            ("合计/分组小计", "Σ 各行 / 按相关类型分组", "计算",
             "明细合计与分组小计（calcSubtotal / subtotals）", "useK7Detail"),
            ("明细期末合计→跨sheet", "Σ 期末余额 → K7-2-detail-end-total", "计算",
             "供审定表交叉验证（getDetailEndTotal）", "useK7Detail"),
            ("企业分摊合计→跨sheet", "Σ 本期分摊 → K7-2-amort-total", "计算",
             "供 K7-2↔K7-4 交叉验证（getAmortTotal）", "useK7Detail"),
        ],
        "K7-4": [
            ("本期应分摊(直线法)", "补助总额 ÷ 分摊期总期数 × 本期期数", "计算",
             "CAS16 直线分摊，总期数 0 兜底 0（calcStraightLineAmort）", "useK7AmortizationCalc / useK7GrantAmortEngine"),
            ("本期应分摊(一次性)", "= 补助总额", "计算",
             "一次性计入当期损益（_recalcRow）", "useK7AmortizationCalc"),
            ("期末余额", "补助总额 − 累计分摊", "计算",
             "递延收益余额，负数兜底 0（calcRemainingBalance）", "useK7AmortizationCalc / useK7GrantAmortEngine"),
            ("分摊差异", "测算分摊 − 企业分摊", "计算",
             "测算与账面差异（calcAmortVariance）", "useK7AmortizationCalc / useK7GrantAmortEngine"),
            ("合计", "Σ 各行", "计算",
             "测算表合计（calcSubtotal / subtotals）", "useK7AmortizationCalc"),
            ("差异超重要性", "|差异| > 重要性水平 → 红色标记", "logic_check",
             "差异超阈值告警（isVarianceExceeded / hasExceededVariance）", "useK7AmortizationCalc"),
            ("测算分摊合计→跨sheet", "Σ 本期应分摊 → K7-4-calc-amort-total", "计算",
             "供 K7-2↔K7-4 交叉验证（getCalcAmortTotal）", "useK7AmortizationCalc"),
            ("K7-2↔K7-4分摊勾稽", "|K7-2 企业分摊合计 − K7-4 测算分摊合计| < 0.01", "logic_check",
             "企业分摊与测算分摊交叉（detailVsCalc）", "useK7CrossSheet"),
        ],
        "K7-5": [
            ("检查比例", "检查金额 ÷ 本期发生额(仅贷方，源模板设计)", "计算",
             "凭证检查比例（checkRatios）", "useK1VoucherCheck / K7TabDeferredCheck"),
            ("检查比例阈值", "检查比例 < 30% → 告警", "logic_check",
             "比例偏低需扩样/说明（lowRatioWarnings）", "useK1VoucherCheck"),
            ("异常凭证汇总", "abnormal=true 的凭证行", "logic_check",
             "异常凭证标记（abnormalRows）", "useK1VoucherCheck"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K8 销售费用（损益借方 6601，取发生额=借−贷；含合同费用摊销 / 双向截止）
    # ═══════════════════════════════════════════════════════════════════════
    "K8": {
        "K8-1": [
            ("未审数(净发生额)", "本期借方发生 − 本期贷方发生(红冲)", "计算",
             "损益类 6601 借方取发生额（calcIncomeStatementOccurrence）", "useK8FormulaEngine"),
            ("审定数", "未审(净发生额) + AJE 账项调整 + RJE 重分类调整", "计算",
             "各费用项目审定金额（calcAuditedAmount）", "useK8Adjudication"),
            ("同比变动额", "本期审定数 − 上期审定数", "计算",
             "审定表同比变动列（calcYoYChangeAmount）", "useK8FormulaEngine"),
            ("同比变动率", "同比变动额 ÷ |上期审定数|", "计算",
             "上期为 0 返空，±30% 高亮（calcChangeRate）", "useK8Adjudication"),
            ("合计行", "Σ 各费用项目(未审借/贷、AJE、RJE、审定、上期)", "计算",
             "审定表合计（calcSubtotal）", "useK8Adjudication"),
            ("从K8-2明细带入", "按明细科目重建审定行：未审=Σ月度、AJE/RJE/上期审定", "取数",
             "复现源模板 SUMIF（pullFromDetail 读 K8-2-detail-rows）", "useK8Adjudication"),
            ("审定↔明细勾稽", "K8-1 审定合计 − K8-2 明细审定合计(K8-2-detail-audited-total)", "logic_check",
             "差异<0.01 视为一致（detailCrossValidation）", "useK8Adjudication"),
            ("试算平衡表数核对(6601)", "审定合计 回写 trial-balance(6601, is_occurrence=true)", "logic_check",
             "损益类回写发生额非期末余额（writeback）", "useK8Adjudication"),
            ("附注取数键回写", "K8-1-audited-by-item = {项目名:{audited,prior}}", "取数",
             "供附注上市/国企 applyAutoFill 消费（_persistAuditedByItem）", "useK8Adjudication"),
        ],
        "K8-2": [
            ("本期未审合计", "Σ(1~12月发生额)", "计算",
             "月度构成合计（calcSubtotal / months）", "useK8Detail"),
            ("审定数", "本期未审合计 + AJE + RJE", "计算",
             "明细各科目审定（calcAuditedAmount）", "useK8Detail"),
            ("同比变动率", "(审定 − 上期发生额) ÷ |上期|", "计算",
             "明细同比分析（calcYoYChange）", "useK8AnalysisEngine"),
            ("占营业收入比", "审定数 ÷ 营业收入", "计算",
             "收入为 0 返空（calcRatioToRevenue）", "useK8AnalysisEngine"),
            ("各项目占比", "本行审定 ÷ 审定合计", "计算",
             "对齐源模板 R 列（rowsWithRatio）", "useK8Detail"),
            ("上期各项目占比", "本行上期 ÷ 上期合计", "计算",
             "对齐源模板 X 列（rowsWithRatio）", "useK8Detail"),
            ("占比变动", "本期占比 − 上期占比", "计算",
             "对齐源模板 Y 列（rowsWithRatio）", "useK8Detail"),
            ("合计行", "Σ 各明细(月度/未审/AJE/RJE/审定/上期)", "计算",
             "明细合计（subtotal）", "useK8Detail"),
            ("从序时账按月取数", "拉 /ledger/entries/6601 按明细科目×月聚合(借−贷)", "取数",
             "回填 12 月发生额（pullExpenseLedgerMonthly + applyMonthlyRows）", "expenseLedgerMonthlyPull"),
            ("审定合计回写", "K8-2-detail-audited-total = 明细审定合计", "取数",
             "供审定表/分析表跨 sheet 勾稽（_persist）", "useK8Detail"),
        ],
        "K8-3": [
            ("类别→调整桶", "报表调整→RJE(重分类)；账项调整/其他→AJE(账项调整)", "计算",
             "分录分桶（categoryToBucket）", "K8TabAdjustment"),
            ("借方合计", "Σ 各分录借方调整金额", "计算",
             "借贷平衡校验用（totalDebits）", "K8TabAdjustment"),
            ("贷方合计", "Σ 各分录贷方调整金额", "计算",
             "借贷平衡校验用（totalCredits）", "K8TabAdjustment"),
            ("借贷平衡", "|Σ借方 − Σ贷方| < 0.005", "logic_check",
             "不平衡禁止回写（isBalanced）", "K8TabAdjustment"),
            ("AJE合计回写K8-1", "Σ(账项/其他分录: 借−贷) → K8-1-aje-total", "取数",
             "损益类对科目影响=借−贷（handleSaveWriteback）", "K8TabAdjustment"),
            ("RJE合计回写K8-1", "Σ(报表调整分录: 借−贷) → K8-1-rje-total", "取数",
             "供 K8-1 审定表消费（handleSaveWriteback）", "K8TabAdjustment"),
        ],
        "K8-4": [
            ("同比变动额", "本期金额 − 上期金额", "计算",
             "实质性分析变动列（changeAmount）", "useK8Analysis"),
            ("同比变动率", "(本期 − 上期) ÷ |上期|", "计算",
             "上期为 0 返空（calcYoYChange）", "useK8AnalysisEngine"),
            ("占营业收入比", "本期金额 ÷ 本期营业收入", "计算",
             "占收入比（calcRatioToRevenue）", "useK8AnalysisEngine"),
            ("上期占营业收入比", "上期金额 ÷ 上期营业收入(缺省回退本期收入)", "计算",
             "占比偏离分母（calcRatioToRevenue）", "useK8Analysis"),
            ("占比偏离", "本期占收入比 − 上期占收入比", "计算",
             "ratioDeviation", "useK8Analysis"),
            ("结构比", "本项目金额 ÷ 费用合计", "计算",
             "占费用总额比（calcStructureRatio）", "useK8AnalysisEngine"),
            ("异常波动判断", "|同比变动率| > 阈值(默认0.3)", "logic_check",
             "自动标记异常项（isAbnormalFluctuation）", "useK8AnalysisEngine"),
            ("从K8-2明细带入", "按明细审定/上期填入分析行", "取数",
             "populateFromDetail", "useK8Analysis"),
            ("分析合计回写", "K8-4-analysis-total = Σ 本期金额", "取数",
             "供分析↔明细勾稽（useK8CrossSheet.analysisVsDetail）", "useK8Analysis"),
        ],
        "K8-5": [
            ("合同总月份", "(结束年−开始年)×12 + (结束月−开始月) + 1", "计算",
             "含首尾月跨月数（monthsInclusive）", "useK8ContractAmortization"),
            ("本期应计月份", "合同期 ∩ 摊销期(期初~期末) 的跨月数", "计算",
             "可手工覆盖（accrualMonthsInPeriod）", "useK8ContractAmortization"),
            ("本期应计损益", "合同金额 ÷ 合同总月份 × 本期应计月份", "计算",
             "直线摊销（calcAccruedPL）", "useK8ContractAmortization"),
            ("差异", "本期应计损益 − 本期已计损益", "计算",
             "摊销核对差异（computedRows.diff）", "useK8ContractAmortization"),
            ("摊销差异告警", "|差异| > 1 元", "logic_check",
             "差异行高亮 + 汇总（diffWarnings）", "useK8ContractAmortization"),
            ("差异→K8-3调整草稿", "差异>0 借销售费用调增/差异<0 贷调减", "计算",
             "生成 AJE 草稿（diffAdjustmentDrafts）", "useK8ContractAmortization"),
            ("合计行", "Σ(合同金额/应计损益/已计损益/差异)", "计算",
             "totals", "useK8ContractAmortization"),
        ],
        "K8-6": [
            ("跨期判定(V2S)", "记账日期与原始凭证日期 自然月(年+月)不同即跨期", "logic_check",
             "记账→原始真实性（isCrossPeriod / crossesByNaturalMonth）", "useK8CutoffEngine"),
            ("跨期金额", "跨期时取 记账金额 或 支出凭单金额", "计算",
             "crossAmount", "useK8Cutoff"),
            ("金额不符判定", "支出凭单金额>0 且 记账金额>0 且 |两者差|>0.01", "logic_check",
             "amountMismatch", "useK8Cutoff"),
            ("默认结论", "缺任一侧日期→证据不完整；双侧齐全按自然月→跨期/正常", "logic_check",
             "禁止假绿正常（_defaultConclusion / deriveConclusion）", "useK8Cutoff"),
            ("资产负债表日前/后分段", "记账日期 ≤ 期末 → 日前，否则日后", "logic_check",
             "截止日分隔（preCutoff / postCutoffSamples）", "useK8Cutoff"),
            ("自动从序时账抽样", "POST /sampling/cutoff-test(6601, 期末±5天, cutoff_date)", "取数",
             "提取窗口内凭证（autoSample）", "useK8Cutoff"),
            ("汇总统计", "跨期笔数/证据不完整笔数/正常笔数/跨期金额合计/不符笔数", "计算",
             "summary", "useK8Cutoff"),
        ],
        "K8-7": [
            ("跨期判定(S2V)", "原始凭证日期与记账日期 自然月不同即跨期", "logic_check",
             "原始→记账完整性（isCrossPeriod）", "useK8CutoffEngine"),
            ("是否及时入账", "S2V 方向：非跨期即及时入账", "logic_check",
             "isTimely", "useK8Cutoff"),
            ("默认结论", "缺任一侧日期→证据不完整；双侧齐全按自然月判定", "logic_check",
             "_defaultConclusion", "useK8Cutoff"),
            ("自动从序时账抽样", "POST /sampling/cutoff-test(6601, 期末±5天)", "取数",
             "autoSample", "useK8Cutoff"),
        ],
        "K8-8": [
            ("检查比例(本期借方)", "本期借方检查金额 ÷ 账面本期借方发生额", "计算",
             "损益借方检查覆盖比例（checkRatios）", "useK1VoucherCheck"),
            ("凭证五项核对", "①原始凭证完整②账记相符③会计处理正确④会计期间正确⑤费用分类正确 全勾", "logic_check",
             "逐笔核对完备（isK1VoucherRowChecksComplete / evaluateK1VoucherChecks）", "useK1VoucherCheck"),
            ("检查金额合计", "Σ 凭证检查行借方(/贷方)金额", "计算",
             "occurrenceDebitChecked / CreditChecked", "useK1VoucherCheck"),
            ("检查比例偏低告警", "检查比例 < 30% 且账面>0", "logic_check",
             "需扩样或说明（lowRatioWarnings）", "useK1VoucherCheck"),
            ("从K8-2带入本期发生额", "K8-2 审定合计 → 检查比例分母 bookDebitOccurrence", "取数",
             "检查比例分母（criteria）", "K8TabSellingCheck"),
            ("异常凭证→A13", "异常凭证行 → 错报汇总(voucherNo/amount/description)", "取数",
             "eventBus a13:push-misstatement（abnormalRows）", "K8TabSellingCheck"),
        ],
        "附注上市": [
            ("从K8-1审定表构建披露行", "读 K8-1-audited-by-item：本期=audited，上期=prior", "取数",
             "按费用性质动态构建（buildRowsFromK81 / applyAutoFill）", "K8TabDisclosureListed"),
            ("披露合计", "Σ 各披露行本期金额", "计算",
             "disclosureCurrentTotal", "K8TabDisclosureListed"),
            ("披露↔审定勾稽", "披露本期合计 − K8-1 审定合计 (差异≥0.01 告警)", "logic_check",
             "附注销售费用须等于审定数（disclosureReconcile）", "K8TabDisclosureListed"),
            ("同比变动率", "(本期 − 上期) ÷ 上期", "计算",
             "异常率>阈值高亮（formatRate / isAbnormal）", "K8TabDisclosureListed"),
        ],
        "附注国企": [
            ("从K8-1审定表构建披露行", "读 K8-1-audited-by-item：本期=audited，上期=prior", "取数",
             "按费用性质简化披露（buildRowsFromK81 / applyAutoFill）", "K8TabDisclosureSoe"),
            ("披露合计", "Σ 各披露行本期金额", "计算",
             "disclosureCurrentTotal", "K8TabDisclosureSoe"),
            ("披露↔审定勾稽", "披露本期合计 − K8-1 审定合计 (差异≥0.01 告警)", "logic_check",
             "disclosureReconcile", "K8TabDisclosureSoe"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K9 管理费用（损益借方 6602，取发生额=借−贷；结构同 K8）
    # ═══════════════════════════════════════════════════════════════════════
    "K9": {
        "K9-1": [
            ("未审数(净发生额)", "本期借方发生 − 本期贷方发生(红冲)", "计算",
             "损益类 6602 借方取发生额（calcIncomeStatementOccurrence）", "useK9FormulaEngine"),
            ("审定数", "未审(净发生额) + AJE 账项调整 + RJE 重分类调整", "计算",
             "各费用项目审定金额（calcAuditedAmount）", "useK9Adjudication"),
            ("同比变动额", "本期审定数 − 上期审定数", "计算",
             "审定表同比变动列", "useK9Adjudication"),
            ("同比变动率", "同比变动额 ÷ |上期审定数|", "计算",
             "上期为 0 返空（calcChangeRate）", "useK9Adjudication"),
            ("合计行", "Σ 各费用项目(未审借/贷、AJE、RJE、审定、上期)", "计算",
             "审定表合计（calcSubtotal）", "useK9Adjudication"),
            ("tb_balance明细预填", "无持久化行时按 6602 明细子科目建行(未审借/贷)", "取数",
             "对齐 J1 审定表预填铁律（prefill seed）", "useK9Adjudication"),
            ("从K9-2明细带入", "按明细科目建行：未审借=K9-2 本期发生额，保留已编辑 AJE/RJE", "取数",
             "fillFromDetail 读 K9-2-detail-rows", "useK9Adjudication"),
            ("审定↔明细勾稽", "K9-1 审定合计 − K9-2 明细审定合计(K9-2-detail-audited-total)", "logic_check",
             "差异<0.01 一致（detailCrossValidation）", "useK9Adjudication"),
            ("审定↔K9-3调整勾稽", "K9-1 逐行 AJE/RJE 合计 − K9-3 回写的 K9-1-aje-total/rje-total", "logic_check",
             "不双加仅勾稽提示（adjustmentReconcile）", "useK9Adjudication"),
            ("试算平衡表数核对(6602)", "审定合计 回写 trial-balance(6602, is_occurrence=true)", "logic_check",
             "损益类回写发生额（writeback）", "useK9Adjudication"),
            ("附注取数键回写", "K9-1-audited-by-item = {项目名:{audited,prior}}", "取数",
             "供附注上市/国企 applyAutoFill 精确匹配（_persistAuditedByItem）", "useK9Adjudication"),
        ],
        "K9-2": [
            ("本期未审合计", "Σ(1~12月发生额)", "计算",
             "月度构成合计（calcSubtotal）", "useK9Detail"),
            ("审定数", "本期未审合计 + AJE + RJE", "计算",
             "明细各科目审定（calcAuditedAmount）", "useK9Detail"),
            ("同比变动率", "(审定 − 上期发生额) ÷ |上期|", "计算",
             "明细同比（calcYoYChange）", "useK9AnalysisEngine"),
            ("占营业收入比", "审定数 ÷ 营业收入", "计算",
             "收入为 0 返空（calcRatioToRevenue）", "useK9AnalysisEngine"),
            ("合计行", "Σ 各明细(月度/未审/AJE/RJE/审定/上期)", "计算",
             "明细合计（subtotal）", "useK9Detail"),
            ("从序时账按月取数", "拉 /ledger/entries/6602 按明细科目×月聚合(借−贷)", "取数",
             "回填 12 月发生额（pullExpenseLedgerMonthly + applyMonthlyRows）", "expenseLedgerMonthlyPull"),
            ("审定合计回写", "K9-2-detail-audited-total = 明细审定合计", "取数",
             "供审定表/分析表跨 sheet 勾稽（_persist）", "useK9Detail"),
        ],
        "K9-3": [
            ("类别→调整桶", "报表调整→RJE(重分类)；账项调整/其他→AJE(账项调整)", "计算",
             "分录分桶（categoryToBucket）", "K9TabAdjustment"),
            ("借方合计", "Σ 各分录借方调整金额", "计算",
             "totalDebit", "K9TabAdjustment"),
            ("贷方合计", "Σ 各分录贷方调整金额", "计算",
             "totalCredit", "K9TabAdjustment"),
            ("借贷平衡", "|Σ借方 − Σ贷方| < 0.01", "logic_check",
             "isBalanced", "K9TabAdjustment"),
            ("AJE合计回写K9-1", "Σ(账项/其他分录: 借−贷) → K9-1-aje-total", "取数",
             "损益类对科目影响=借−贷（ajeTotal）", "K9TabAdjustment"),
            ("RJE合计回写K9-1", "Σ(报表调整分录: 借−贷) → K9-1-rje-total", "取数",
             "供 K9-1 审定表消费（rjeTotal）", "K9TabAdjustment"),
        ],
        "K9-4": [
            ("同比变动额", "本期金额 − 上期金额", "计算",
             "changeAmount", "useK9Analysis"),
            ("同比变动率", "(本期 − 上期) ÷ |上期|", "计算",
             "上期为 0 返空（calcYoYChange）", "useK9AnalysisEngine"),
            ("占营业收入比", "本期金额 ÷ 营业收入", "计算",
             "calcRatioToRevenue", "useK9AnalysisEngine"),
            ("上期占营业收入比", "上期金额 ÷ 营业收入", "计算",
             "占比偏离分母（calcRatioToRevenue）", "useK9Analysis"),
            ("占比偏离", "本期占收入比 − 上期占收入比", "计算",
             "ratioDeviation", "useK9Analysis"),
            ("异常波动判断", "|同比变动率| > 阈值(默认0.3)", "logic_check",
             "自动标记异常项（isAbnormalFluctuation）", "useK9AnalysisEngine"),
            ("从K9-2明细带入", "按明细审定/上期填入分析行", "取数",
             "populateFromDetail", "useK9Analysis"),
            ("分析合计回写", "K9-4-analysis-total = Σ 本期金额", "取数",
             "供分析↔明细勾稽（_persist）", "useK9Analysis"),
        ],
        "K9-6": [
            ("跨期判定(V2S)", "记账日期与原始凭证日期 自然月(年+月)不同即跨期", "logic_check",
             "记账→原始（isCrossPeriod / crossesByNaturalMonth）", "useK9CutoffEngine"),
            ("跨期金额", "跨期时取记账金额", "计算",
             "crossAmount", "useK9Cutoff"),
            ("默认结论", "缺任一侧日期→证据不完整；双侧齐全按自然月→跨期/正常", "logic_check",
             "禁止假绿（_defaultConclusion / deriveConclusion）", "useK9Cutoff"),
            ("自动从序时账抽样", "POST /sampling/cutoff-test(6602, 期末±5天, cutoff_date)", "取数",
             "提取窗口内凭证（autoSample）", "useK9Cutoff"),
            ("汇总统计", "跨期笔数/证据不完整笔数/正常笔数/跨期金额合计", "计算",
             "summary", "useK9Cutoff"),
        ],
        "K9-7": [
            ("跨期判定(S2V)", "原始凭证日期与记账日期 自然月不同即跨期", "logic_check",
             "原始→记账完整性（isCrossPeriod）", "useK9CutoffEngine"),
            ("是否及时入账", "S2V 方向：非跨期即及时入账", "logic_check",
             "isTimely", "useK9Cutoff"),
            ("默认结论", "缺任一侧日期→证据不完整；双侧齐全按自然月判定", "logic_check",
             "_defaultConclusion", "useK9Cutoff"),
            ("自动从序时账抽样", "POST /sampling/cutoff-test(6602, 期末±5天)", "取数",
             "autoSample", "useK9Cutoff"),
        ],
        "K9-8": [
            ("检查比例(本期借方)", "本期借方检查金额 ÷ 账面本期借方发生额", "计算",
             "损益借方检查覆盖比例（checkRatios）", "useK1VoucherCheck"),
            ("凭证五项核对", "①原始凭证完整②账记相符③会计处理正确④会计期间正确⑤费用分类正确 全勾", "logic_check",
             "逐笔核对完备（K9_CHECK_LABELS 第⑤项=费用分类正确）", "useK1VoucherCheck"),
            ("检查金额合计", "Σ 凭证检查行借方金额", "计算",
             "occurrenceDebitChecked", "useK1VoucherCheck"),
            ("检查比例偏低告警", "检查比例 < 30% 且账面>0", "logic_check",
             "需扩样或说明（lowRatioWarnings）", "useK1VoucherCheck"),
            ("从K9-1带入本期发生额", "K9-1 审定合计(K9-1-audited-total) → 检查比例分母 bookDebitOccurrence", "取数",
             "importFromK91", "K9TabAdminCheck"),
            ("异常凭证→A13", "异常凭证行 → 错报汇总(voucherNo/amount/description)", "取数",
             "eventBus a13:push-misstatement（pushToA13）", "K9TabAdminCheck"),
        ],
        "附注上市": [
            ("从K9-1审定表构建披露行", "读 K9-1-audited-by-item(费用性质 keyed)：本期=audited，上期=prior", "取数",
             "命名与 k9FeeNatures 一致（buildRowsFromK81 / applyAutoFill）", "K9TabDisclosureListed"),
            ("披露合计", "Σ 各披露行本期金额", "计算",
             "disclosureCurrentTotal", "K9TabDisclosureListed"),
            ("披露↔审定勾稽", "披露本期合计 − K9-1 审定合计 (差异≥0.01 告警)", "logic_check",
             "附注管理费用须等于审定数（disclosureReconcile）", "K9TabDisclosureListed"),
        ],
        "附注国企": [
            ("从K9-1审定表构建披露行", "读 K9-1-audited-by-item(含国企特有项)：本期=audited，上期=prior", "取数",
             "K9_FEE_NATURES_SOE 命名（buildRowsFromK81 / applyAutoFill）", "K9TabDisclosureSoe"),
            ("披露合计", "Σ 各披露行本期金额", "计算",
             "disclosureCurrentTotal", "K9TabDisclosureSoe"),
            ("披露↔审定勾稽", "披露本期合计 − K9-1 审定合计 (差异≥0.01 告警)", "logic_check",
             "disclosureReconcile", "K9TabDisclosureSoe"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K10 其他收益（损益贷方 6117，取发生额=贷−借；含政府补助核对 / 应收补助 / 综合检查）
    # ═══════════════════════════════════════════════════════════════════════
    "K10": {
        "K10-1": [
            ("审定数", "未审 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各收益来源行审定金额（calcAuditedAmount）", "useK10Adjudication / useK10FormulaEngine"),
            ("本期发生额(净额)", "本期贷方发生 − 本期借方发生(红冲)", "计算",
             "损益贷方发生额（calcIncomeStatementOccurrence 贷−借）", "useK10FormulaEngine"),
            ("同比变动率", "(本期审定 − 上期审定) ÷ 上期审定", "计算",
             "上期为 0 返 null（calcYoYChange）", "useK10FormulaEngine"),
            ("合计", "Σ 各来源行审定", "计算",
             "审定合计（calcSubtotal）", "useK10FormulaEngine"),
            ("TB回写6117发生额", "审定合计 回写 trial-balance(6117, is_occurrence)", "取数",
             "损益贷方回写发生额（writebackTB）", "useK10Adjudication / useK10FormData"),
            ("审定↔明细勾稽", "K10-1 审定合计(K10-1-audited-total) − K10-2 明细合计(K10-2-subtotal)", "logic_check",
             "差异<0.01 视为一致（adjudicationVsDetail）", "useK10CrossSheet"),
            ("递延分摊↔K7勾稽", "K10-4 递延分摊计入合计 − K7 递延收益(2401)本期分摊", "logic_check",
             "|diff|<0.01（reconcileVsK7）", "useK10CrossSheet"),
        ],
        "K10-2": [
            ("本期审定数", "本期未审 + 本期AJE + 本期RJE", "计算",
             "明细行审定（calcAuditedAmount）", "useK10Detail / useK10FormulaEngine"),
            ("上年同期审定数", "上年未审 + 上年AJE", "计算",
             "上期审定（calcAuditedAmount，rje=0）", "useK10Detail"),
            ("合计", "Σ 各明细行(未审/AJE/RJE/审定/上年)", "计算",
             "明细合计（calcSubtotal）→ K10-2-subtotal", "useK10Detail"),
        ],
        "K10-4": [
            ("期末递延余额", "期初 + 新增 − 摊销冲减成本 − 摊销转其他收益 − 摊销转营业外 − 返还 − 其他转出", "计算",
             "递延收益滚存（_calcClosingDeferred）", "useK10GrantReconcile"),
            ("合计计入其他收益", "直接计入其他收益 + 摊销转其他收益", "计算",
             "确认为其他收益的补助合计（calcTotalRecognized）", "useK10GrantReconcile / useK10GrantReconcileEngine"),
            ("各列合计", "Σ 各行(直接计入/新增/期初/摊销/返还/期末)", "计算",
             "合计行（calcSubtotal）", "useK10GrantReconcile"),
            ("K7一致性核对", "K10-4 摊销转其他收益合计 − K7 递延收益(2401)本期分摊", "logic_check",
             "递延分摊一致性（k7Consistency / isConsistentWithK7，K7 分摊手工从 K7-4 填入）", "useK10GrantReconcile"),
        ],
        "K10-5": [
            ("综合结论", "收款权利 + 预期可收回 + 确认时点 三项派生(任一不合规→不合规)", "logic_check",
             "应收补助综合判断（deriveReceivableStatus）", "useK10Checks"),
            ("期后收款状态", "已收回(期后≥应收) / 部分收回 / 未收回", "logic_check",
             "核对期后实际收款佐证可收回性（deriveCollectionStatus）", "useK10Checks"),
            ("不合规摘要", "任一检查项不合规的补助项汇总", "logic_check",
             "receivableSummary", "useK10Checks"),
        ],
        "K10-6": [
            ("总体结论", "分类正确性 + 确认条件满足 派生(任一不合规→不合规)", "logic_check",
             "综合检查结论（deriveOverallStatus）", "useK10Checks"),
            ("检查覆盖率", "检查金额合计 ÷ K10-2 明细合计(K10-2-subtotal)", "计算",
             "覆盖率（coverageRate）", "useK10Checks"),
            ("从K10-2带入检查项", "checkItem=补助项目、checkAmount=审定数，去重", "取数",
             "importIncomeChecksFromDetail", "useK10Checks"),
            ("错分至营业外收入提示", "分类=营业外收入 → 应重分类至 6301/K12", "logic_check",
             "misclassifiedRows", "useK10Checks"),
            ("不合规摘要", "总体结论不合规的检查项汇总", "logic_check",
             "incomeCheckSummary", "useK10Checks"),
        ],
        "附注上市": [
            ("附注披露金额自动取数", "读 K10-1-rows 按来源名称匹配审定数", "取数",
             "buildAdjAuditedMap / applyAutoFill（订阅 substantive:adjudicated 6117）", "K10TabDisclosureListed"),
        ],
        "附注国企": [
            ("附注披露金额自动取数", "读 K10-1-rows 按来源名称匹配审定数", "取数",
             "buildAdjAuditedMap / applyAutoFill（订阅 substantive:adjudicated 6117）", "K10TabDisclosureSoe"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K11 资产减值损失（损益借方 6701，取发生额=借−贷；含 18 类减值来源交叉核对）
    # ═══════════════════════════════════════════════════════════════════════
    "K11": {
        "K11-1": [
            ("本期发生额(净额)", "本期借方发生 − 本期贷方发生(转回红冲)", "计算",
             "损益借方发生额（calcIncomeStatementOccurrence 借−贷）", "useK11FormulaEngine"),
            ("审定数", "本期未审(发生额) + AJE + RJE", "计算",
             "各资产类别行审定（calcAuditedAmount）", "useK11Adjudication / useK11FormulaEngine"),
            ("上期审定数", "上期未审 + 上期账项调整", "计算",
             "priorAudited（priorUnadjusted + priorAdjustment）", "useK11Adjudication"),
            ("变动额", "本期审定 − 上期审定", "计算",
             "yoyChange", "useK11Adjudication"),
            ("变动率", "变动额 ÷ |上期审定|", "计算",
             "calcChangeRate（上期为 0 返 null）", "useK11Adjudication"),
            ("合计", "Σ 各资产类别行", "计算",
             "totalRow（calcSubtotal）", "useK11Adjudication / calcSubtotal"),
            ("附注取数键回写(按归一化类别)", "K11-1-audited-by-category = {归一化资产类别:{审定发生额,上期}}", "取数",
             "供附注 applyAutoFill 按归一化类别匹配（_buildAuditedByCategory / normalizeImpairmentCategory）", "useK11Adjudication"),
            ("TB回写6701发生额", "审定合计 回写 trial-balance(6701, is_occurrence)", "logic_check",
             "损益借方回写发生额 + substantive:adjudicated 事件（writeback）", "useK11Adjudication"),
            ("审定↔明细勾稽", "K11-1 审定合计 − K11-2 发生额合计(K11-2-total-occurrence)", "logic_check",
             "差异<0.01 视为一致（detailCrossValidation）", "useK11Adjudication"),
            ("审定↔K11-3调整勾稽", "K11-1 逐行 AJE/RJE 合计 − K11-3 回写的 K11-1-aje-total/rje-total", "logic_check",
             "不双加仅勾稽提示（adjustmentReconcile）", "useK11Adjudication"),
        ],
        "K11-2": [
            ("本期发生额", "本期计提 − 本期转回(商誉不可转回则转回=0)", "计算",
             "减值发生额（currentProvision − currentReversal）", "useK11Detail"),
            ("减值准备期末", "减值准备期初 + 本期计提 − 本期转回", "计算",
             "对应科目减值准备滚存（allowanceEnding）", "useK11Detail"),
            ("源底稿核对差异", "本期发生额 − 源底稿(F2/H1/I1/I3/D6 等)计提金额", "logic_check",
             "差异非零红色标记（calcSourceVariance / varianceRows）", "useK11Detail / useK11FormulaEngine"),
            ("合计", "Σ 各行(计提/转回/发生额/源底稿/减值准备)", "计算",
             "subtotal（calcSubtotal）→ K11-2-total-occurrence", "useK11Detail"),
            ("商誉减值不可转回", "资产类别含「商誉」→ 本期转回强制为 0 且不可编辑", "logic_check",
             "CAS8 商誉减值不可转回（isGoodwillCategory）", "useK11Detail"),
            ("从H1-14引入本期补提", "拉 H1-14 本期补提⑧写入固定资产行 sourceAmount", "取数",
             "pullH1SupplementAsSource", "useK11Detail"),
        ],
        "K11-3": [
            ("类别→调整桶", "报表调整→RJE(重分类)；账项调整/其他→AJE(账项调整)", "计算",
             "分录分桶（categoryToBucket）", "K11TabAdjustment"),
            ("借贷平衡", "|Σ借方 − Σ贷方| < 0.01", "logic_check",
             "调整分录借贷平衡", "K11TabAdjustment"),
            ("AJE/RJE合计回写K11-1", "AJE(借−贷)合计 → K11-1-aje-total；RJE → K11-1-rje-total", "取数",
             "供 K11-1 adjustmentReconcile 勾稽消费", "K11TabAdjustment"),
            ("推送A13错报", "调整分录 → A13 未更正错报汇总", "取数",
             "eventBus a13:push-misstatement", "K11TabAdjustment"),
        ],
        "附注上市": [
            ("附注披露金额自动取数", "读 K11-1-audited-by-category 按归一化资产类别匹配审定发生额", "取数",
             "buildRowsFromK11 / applyAutoFill（订阅 substantive:adjudicated 6701）", "K11TabDisclosureListed"),
            ("减值准备变动披露", "取自 K11-2(本期计提/转回/期末)", "取数",
             "减值变动明细取数", "K11TabDisclosureListed"),
        ],
        "附注国企": [
            ("附注披露金额自动取数", "读 K11-1-audited-by-category 按归一化资产类别匹配审定发生额", "取数",
             "buildRowsFromK11 / applyAutoFill（订阅 substantive:adjudicated 6701）", "K11TabDisclosureSoe"),
            ("减值准备变动披露", "取自 K11-2(本期计提/转回/期末)", "取数",
             "减值变动明细取数", "K11TabDisclosureSoe"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K12 营业外收入（损益贷方 6301，取发生额=贷−借；含月度明细 / 凭证检查）
    # ═══════════════════════════════════════════════════════════════════════
    "K12": {
        "K12-1": [
            ("审定数", "未审 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各来源行审定金额（calcAuditedAmount）", "useK12Adjudication / useK12FormulaEngine"),
            ("上期审定数", "上期未审 + 上期AJE + 上期RJE", "计算",
             "priorAudited（calcAuditedAmount）", "useK12Adjudication"),
            ("同比变动率", "(本期审定 − 上期审定) ÷ |上期审定|", "计算",
             "上期为 0 返 null（calcYoYChange）", "useK12FormulaEngine"),
            ("合计", "Σ 各来源行审定", "计算",
             "totalRow（calcSubtotal）", "useK12Adjudication"),
            ("TB回写6301发生额", "审定合计 回写 trial-balance(6301, is_occurrence)", "取数",
             "损益贷方回写发生额（writebackTB）", "useK12Adjudication / useK12FormData"),
            ("审定↔明细勾稽", "K12-1 审定合计(K12-1-audited-total) − K12-2 明细合计(K12-2-subtotal)", "logic_check",
             "差异<0.01 视为一致（adjudicationVsDetail / detailCrossValidation）", "useK12Adjudication / useK12CrossSheet"),
        ],
        "K12-2": [
            ("月度合计", "Σ(1~12月贷方发生)", "计算",
             "N 列月度合计（calcSubtotal）", "useK12Detail"),
            ("审定数", "月度合计 + AJE + RJE", "计算",
             "Q 列审定（calcAuditedAmount）", "useK12Detail"),
            ("占比", "本行审定 ÷ 合计审定", "计算",
             "占比（calcProportion）", "useK12Detail / useK12FormulaEngine"),
            ("同比变动率", "(审定 − 上期金额) ÷ 上期金额", "计算",
             "calcYoYChange", "useK12Detail"),
            ("合计", "Σ 各明细行(金额/月度/AJE/RJE/审定/上期)", "计算",
             "subtotal（calcSubtotal）→ K12-2-subtotal", "useK12Detail"),
        ],
        "K12-4": [
            ("逐项合规判断", "真实性/依据合规/分类正确性(与日常活动无关非其他收益6117)/期间归属/税务处理 逐项「合规/不合规/不适用」", "logic_check",
             "compliance 三态点选（DEFAULT_CHECK_ITEMS 13 项）", "useK12Check"),
            ("不合规摘要", "compliance='不合规' 的检查项汇总(红色警告)", "logic_check",
             "nonComplianceSummary", "useK12Check"),
            ("检查进度", "已判定项数 ÷ 总检查项数", "计算",
             "checkProgress", "useK12Check"),
        ],
        "附注上市": [
            ("附注披露金额自动取数", "读 K12-1-rows 按来源名称匹配审定数", "取数",
             "applyAutoFill（订阅 substantive:adjudicated 6301）", "K12TabDisclosureListed"),
        ],
        "附注国企": [
            ("附注披露金额自动取数", "读 K12-1-rows 按来源名称匹配审定数", "取数",
             "applyAutoFill（订阅 substantive:adjudicated 6301）", "K12TabDisclosureSoe"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # K13 营业外支出（损益借方 6711，取发生额=借−贷；含月度明细 / 调整分录 / 凭证检查）
    # ═══════════════════════════════════════════════════════════════════════
    "K13": {
        "K13-1": [
            ("审定数", "未审 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各支出去向行审定金额（calcAuditedAmount）", "useK13Adjudication / useK13FormulaEngine"),
            ("上期审定数", "上期未审 + 上期AJE + 上期RJE", "计算",
             "priorAudited（calcAuditedAmount）", "useK13Adjudication"),
            ("同比变动率", "(本期审定 − 上期审定) ÷ |上期审定|", "计算",
             "上期为 0 返 null（calcYoYChange）", "useK13FormulaEngine"),
            ("合计", "Σ 各去向行审定", "计算",
             "totalRow（calcSubtotal）", "useK13Adjudication"),
            ("TB回写6711发生额", "审定合计 回写 trial-balance(6711, is_occurrence)", "取数",
             "损益借方回写发生额（writebackTB）", "useK13Adjudication"),
            ("审定↔明细勾稽", "K13-1 审定合计(K13-1-audited-total) − K13-2 明细合计(K13-2-subtotal)", "logic_check",
             "差异<0.01 视为一致（adjudicationVsDetail / detailCrossValidation）", "useK13Adjudication / useK13CrossSheet"),
            ("审定↔K13-3调整勾稽", "K13-3 净影响(K13-1-aje-total/rje-total) − 本表 AJE/RJE 列合计", "logic_check",
             "不一致=尚未反映 K13-3 调整（adjustmentReconcile）", "useK13Adjudication"),
        ],
        "K13-2": [
            ("月度合计", "Σ(1~12月借方发生)", "计算",
             "N 列月度合计（calcSubtotal）", "useK13Detail"),
            ("审定数", "月度合计 + AJE + RJE", "计算",
             "Q 列审定（calcAuditedAmount）", "useK13Detail"),
            ("占比", "本行审定 ÷ 合计审定", "计算",
             "占比（calcProportion）", "useK13Detail / useK13FormulaEngine"),
            ("上期审定数", "上期金额 + 上期AJE + 上期RJE", "计算",
             "priorAudited（calcAuditedAmount）", "useK13Detail"),
            ("上期占比", "本行上期审定 ÷ 上期合计审定", "计算",
             "priorProportion（calcProportion）", "useK13Detail"),
            ("同比变动率", "(本期审定 − 上期审定) ÷ 上期审定", "计算",
             "calcYoYChange", "useK13Detail"),
            ("合计", "Σ 各明细行(金额/月度/AJE/RJE/审定/上期)", "计算",
             "subtotal（calcSubtotal）→ K13-2-subtotal", "useK13Detail"),
            ("从序时账按月取数", "拉序时账 6711 按明细科目×月聚合(借−贷) 回填 12 月", "取数",
             "applyMonthlyRows（同名覆盖/缺失新增，保留 AJE/RJE/上期）", "useK13Detail"),
        ],
        "K13-3": [
            ("AJE净影响(6711)", "Σ(借−贷)｜AJE 分录", "计算",
             "借方科目净影响=借−贷（ajeNet6711）", "useK13Adjustment"),
            ("RJE净影响(6711)", "Σ(借−贷)｜RJE 分录", "计算",
             "rjeNet6711", "useK13Adjustment"),
            ("借贷平衡", "|Σ借方 − Σ贷方| ≤ 0.01", "logic_check",
             "平衡通过才允许保存+发布（_calcBalance / isBalanced）", "useK13Adjustment"),
            ("净影响回写K13-1", "AJE/RJE 净影响 → K13-1-aje-total / K13-1-rje-total", "取数",
             "供 K13-1 adjustmentReconcile 勾稽消费（saveAndPublish）", "useK13Adjustment"),
            ("发布调整事件+推送A13", "平衡通过 → adjustment:created(K13) + a13:push-misstatement", "logic_check",
             "双向同步 K13-1 + A13 错报汇总", "useK13Adjustment"),
        ],
        "附注上市": [
            ("附注披露金额自动取数", "读 K13-1-rows 按去向名称匹配审定数", "取数",
             "buildAdjAuditedMap / applyAutoFill（订阅 substantive:adjudicated + adjustment:created K13）", "K13TabDisclosureListed"),
        ],
        "附注国企": [
            ("附注披露金额自动取数", "读 K13-1-rows 按去向名称匹配审定数", "取数",
             "buildAdjAuditedMap / applyAutoFill（订阅 substantive:adjudicated + adjustment:created K13）", "K13TabDisclosureSoe"),
        ],
    },
}
