"""H 循环底稿公式 surfacing 目录（与各 useH{n}* composable 同源，不臆造）。

对齐 E1 标准（wp_formula.py::_E1_SHEET_FORMULAS）与 D/F 循环（wp_surfaced_d.py /
wp_surfaced_f.py）：把 H 循环各专属组件底稿（数据存 checklist_responses、无
wp_formula 网格记录）的取数/计算/逻辑审核公式，以只读条目 surface 到公式管理中心，
供审计师查阅每张 sheet 的公式逻辑（可追溯来源 composable）。

每条公式均可在对应前端 composable 中找到依据（calc 引擎函数 / 跨 sheet 键 / TB 核对 /
合计聚合）；找不到依据的 sheet 不写（宁缺勿造）。

覆盖（科目方向以各 composable publishAdjudicated/writeback 的 account_codes 为准）：
- H1 固定资产（原值 1601 借方 / 累计折旧 1602 备抵 / 减值准备 1603 备抵）
- H2 在建工程（1604 借方 / 工程物资 1605；CAS17 利息资本化 + 转固）
- H3 投资性房地产（1503 借方 / 累计折旧 1504 / 减值 1505；成本模式 + 公允模式双计量 + 互转）
- H4 工程物资（1605 借方 / 减值准备 备抵）  ← 平台实为「工程物资」非「使用权资产」
- H5 生产性生物资产/油气资产（油气 1631 借方 / 累计折耗 1632 备抵；单位产量法折耗，IndustryGuard）
- H6 固定资产清理（1606 借方，过渡科目期末应清零）
- H7 生产性生物资产（农/林/牧/渔 1621 借方 / 累计折旧 备抵；成本模式 + 公允模式双计量 + 互转）
- H8 使用权资产（1901 借方 / 累计折旧 1902 / 减值 1903；租赁 CAS21 识别/租赁期/初始计量/折旧）
- H9 租赁负债（2205 贷方 / 未确认融资费用 1802 备抵；实际利率法摊销 + 现值）
- H10 资产处置收益（6115 损益贷方，取发生额；处置损益计算 + 与 H1/H6/H8 处置联动）

科目方向铁律：借方资产科目期末 = 期初审定 + 借 − 贷；备抵/负债科目期末 = 期初审定 +
贷 − 借；损益类（H10）取发生额（贷 − 借），无期初期末余额概念。

分类只用三种：
  - 取数     跨 sheet / 四表库 / 从明细带入
  - 计算     表间计算（审定=未审+AJE+RJE、净值、期末余额、变动额/率、折旧、折耗、
             利息资本化、实际利率法摊销、可收回金额、合计等）
  - logic_check  逻辑审核（TB 核对、审定↔明细勾稽、三角勾稽、借贷平衡、跨底稿勾稽、
             转固勾稽、H8↔H9 联动、CAS8 减值不得转回、过渡科目清零等）

格式：base_code -> sheet_code -> [(项目名, 公式, 分类, 说明, 来源), ...]
"""
from __future__ import annotations

SheetFormula = tuple[str, str, str, str, str]  # (项目名, 公式, 分类, 说明, 来源)

CATALOG: dict[str, dict[str, list[SheetFormula]]] = {
    # ═══════════════════════════════════════════════════════════════════════
    # H1 固定资产（原值 1601 / 累计折旧 1602 / 减值准备 1603；净值三区块 + 折旧四法）
    # ═══════════════════════════════════════════════════════════════════════
    "H1": {
        # H1-1 审定表（一、原值 → 二、累计折旧 → 三、减值准备 → 四、净值）
        "H1-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各行审定金额（calcAuditedAmount）", "useH1Adjudication / useH1FormulaEngine"),
            ("原值期末余额", "期初余额 + 借方发生 − 贷方发生", "计算",
             "借方资产科目 1601 期末（calcAssetEndBalance）", "useH1FormulaEngine"),
            ("累计折旧/减值期末余额", "期初余额 + 贷方发生(增加) − 借方发生(减少)", "计算",
             "备抵类科目 1602/1603 期末（calcContraEndBalance）", "useH1FormulaEngine"),
            ("固定资产净值", "原值审定 − 累计折旧审定 − 减值准备审定", "计算",
             "四、净值按分类派生（calcNetValue / netValueAudited / netRows）", "useH1Adjudication"),
            ("区块小计", "Σ 区块内明细行", "计算",
             "原值/累计折旧/减值各区块小计（calcSubtotal / _sumRows）", "useH1Adjudication"),
            ("变动额", "期末审定净值 − 期初审定净值", "计算",
             "各分类净值变动额（netRows changeAmount）", "useH1Adjudication"),
            ("变动率", "(期末审定净值 − 期初审定净值) ÷ 期初审定净值", "计算",
             "期初=0 返 null；|变动率|≥30% 须说明（calcChangeRate，CHANGE_RATE_THRESHOLD=30）",
             "useH1FormulaEngine / useH1Adjudication"),
            ("三角勾稽校验", "期末 − (期初 + 增加 − 减少)", "logic_check",
             "原值/累计折旧/减值三角勾稽差额应为 0（calcTriangleReconciliation / reconciliationResults）",
             "useH1FormulaEngine / useH1Adjudication"),
            ("从 H1-2 明细聚合", "按分类 Σ(H1-2 原值/累计折旧/减值 期末审定)", "取数",
             "H1-2 合计供审定表交叉验证（adjudicationFromDetail / detailTotals）", "useH1CrossSheet"),
            ("从 H1-3 调整分摊", "按科目码 1601/1602/1603 + 名称关键词分摊 AJE/RJE 至各分类", "取数",
             "H1-3 调整回写审定表（syncAdjustmentsFromH3 / allocateH3AdjustmentsByAccount / adjustmentSync）",
             "useH1Adjudication / useH1CrossSheet"),
            ("从 TB 子科目分类预填", "按 1601/1602/1603 子科目将期初/发生/未审预填各分类区块", "取数",
             "TB 子科目预填（applyCategoryPrefill，手工优先仅填空行）", "useH1Adjudication"),
            ("试算平衡表数核对", "各科目审定合计 − 试算平衡表数(1601/1602/1603/净值)", "logic_check",
             "审定与 TB 核对（differenceRows）", "useH1Adjudication"),
            ("H1-3 调整净额 ↔ 本表 AJE/RJE 勾稽", "H1-3 汇总 AJE/RJE − 本表 AJE/RJE 合计", "logic_check",
             "调整分录合计一致性（adjustmentCheck）", "useH1Adjudication"),
            ("审定回写 TB + 发布事件", "原值(1601)/累计折旧(1602)/减值(1603) 审定数回写 trial_balance", "取数",
             "publishAdjudicated（发布 substantive:adjudicated，account_codes 1601/1602/1603）",
             "useH1Adjudication"),
        ],
        # H1-2 明细表（原值/累计折旧/减值三区块 + 净值，源模板 54 列）
        "H1-2": [
            ("原值期末未审", "期初未审 + 本期增加 − 本期减少", "计算",
             "借方科目期末未审（calcAssetEndBalance / recalcDetailRow costEndUnadj）", "useH1Detail"),
            ("原值期末审定", "审定期初 + 审定增加 − 审定减少（审定=未审+账项调整）", "计算",
             "原值期末审定（recalcDetailRow costEndAud）", "useH1Detail"),
            ("累计折旧期末", "期初 + (计提+其他增) − (处置+其他减)", "计算",
             "备抵类期末（calcContraEndBalance depEndUnadj/depEndAud）", "useH1Detail / useH1FormulaEngine"),
            ("减值准备期末", "期初 + (计提+其他增) − (处置+其他减)", "计算",
             "备抵类期末（结构同折旧；CAS8 一经确认不得转回 UI 提示）", "useH1Detail"),
            ("净值", "原值 − 累计折旧 − 减值准备（期初/期末 × 未审/审定）", "计算",
             "逐行净值（calcNetValue：netBeginUnadj/netBeginAud/netEndUnadj/netEndAud）", "useH1Detail"),
            ("合计", "Σ 各明细行", "计算",
             "明细合计（calcSubtotal / subtotalRow）", "useH1Detail"),
            ("按类别汇总", "按资产类别 Σ(期末审定原值/折旧/减值/净值)", "计算",
             "「其中：」分类行（categorySubtotals）", "useH1Detail"),
            ("H1-2 ↔ H1-1 交叉验证", "H1-2 原值/折旧期末审定合计 − H1-1 审定合计", "logic_check",
             "明细↔审定勾稽（crossValidation，容差 0.01）", "useH1Detail"),
        ],
        # H1-3 调整分录（AJE/RJE 回写 H1-1）
        "H1-3": [
            ("调整净额", "借方调整金额 − 贷方调整金额", "计算",
             "资产类科目净额（adjustmentSync：账项调整→AJE / 报表调整→RJE）", "useH1CrossSheet"),
            ("AJE/RJE 按科目分摊回写审定表", "按 1601/1602/1603 + 名称关键词分摊至 H1-1 各分类", "取数",
             "回写 H1-1（allocateH3AdjustmentsByAccount / syncAdjustmentsFromH3）", "useH1Adjudication"),
        ],
        # H1-6 分析表（比例分析 8 项 + 结构 + 变动 + 折旧整体重算 + 税会差异递延所得税）
        "H1-6": [
            ("固定资产净值/资产总额", "净值 ÷ 资产总额 × 100%", "计算",
             "比率分析①（calcRatioPct）", "useH1Analysis / useH1FormulaEngine"),
            ("本期计提折旧/原值", "本期计提折旧 ÷ 期末原值 × 100%", "计算",
             "比率分析②（calcRatioPct），识别少提/多提", "useH1Analysis"),
            ("累计折旧/原值", "累计折旧 ÷ 期末原值 × 100%", "计算",
             "比率分析③资产老化（calcRatioPct）", "useH1Analysis"),
            ("减值准备/原值", "减值准备余额 ÷ 期末原值 × 100%", "计算",
             "比率分析④减值充分性（calcRatioPct）", "useH1Analysis"),
            ("原值/本期产量", "期末原值 ÷ 本期产品产量", "计算",
             "比率分析⑤产能匹配（calcRatioMultiple）", "useH1Analysis"),
            ("成新率", "净值 ÷ 原值 × 100%", "计算",
             "结构分析成新率（calcNewRate），<20% 老旧资产提示", "useH1FormulaEngine / useH1Analysis"),
            ("平均使用年限 / 剩余年限", "原值 ÷ 年折旧额 / 净值 ÷ 年折旧额", "计算",
             "结构分析（calcAvgUsefulLife / calcRemainingLife）", "useH1FormulaEngine"),
            ("占比", "本类净值 ÷ 净值合计 × 100%", "计算",
             "结构分析占比（calcProportion）", "useH1FormulaEngine"),
            ("增减率 / 净变动率", "本期增加 ÷ 期初原值 / (期末 − 期初) ÷ 期初", "计算",
             "变动分析（calcChangeRate）；>50% 变动幅度提示", "useH1Analysis"),
            ("折旧合理性整体重算", "预期折旧 = 平均原值 × 综合年折旧率；平均原值 = (期初 + 期末原值) ÷ 2", "计算",
             "实质性分析程序独立预期（depreciationRecalc），差异率>10% 须说明", "useH1Analysis"),
            ("折旧税会差异 → 递延所得税", "暂时性差异 = 账面价值 − 计税基础；DTA/DTL = 差异 × 税率", "计算",
             "账面<计税→可抵扣→递延所得税资产(N1)；账面>计税→应纳税→递延所得税负债(N3)（deferredTaxRecalc）",
             "useH1Analysis"),
            ("异常标记", "成新率<20% / 增减率>50% / 比率变动>阈值(pp 5 / 相对 20%)", "logic_check",
             "分析异常追踪（anomalies）", "useH1Analysis"),
            ("从 H1-2 / H1-19 取数", "原值/折旧/减值合计取自 H1-2 明细；租金收入取自 H1-19 经营租出", "取数",
             "分析表取数（faTotals / leaseRentAuto）", "useH1Analysis"),
        ],
        # H1-7 增加检查（vouching/tracing + 折旧起算联动 H1-12 + CIP↔H2 + 现金↔CFS）
        "H1-7": [
            ("净值", "原值 − 累计折旧 − 减值准备", "计算",
             "样本行净值（calcNetValue / _recalcRow）", "useH1AdditionCheck"),
            ("检查覆盖率", "已检查金额 ÷ 本期增加合计 × 100%", "计算",
             "抽查覆盖率（summary.coverageRate）", "useH1AdditionCheck"),
            ("证→账追查差额", "源单据金额 − 账面入账金额", "计算",
             "完整性追查差额（TraceRow amountDiff）", "useH1AdditionCheck"),
            ("金额勾稽", "|账面原值 − 发票/合同金额| > 1 元", "logic_check",
             "账面与外部单据核对（needsAmountMismatchWarning）", "useH1AdditionCheck"),
            ("在建工程转入验收缺失", "增加方式=在建工程转入 ∧ 无验收单索引", "logic_check",
             "CIP 转入验收提示（needsCipAcceptanceWarning）", "useH1AdditionCheck"),
            ("暂估缺折旧起算日", "暂估入账 ∧ 无折旧起算日/验收日/增加日", "logic_check",
             "暂估折旧起算提示（needsProvisionalDepWarning）", "useH1AdditionCheck"),
            ("本期增加合计带入", "取 H1-2 原值本期增加合计（回退 H1-1 原值借方）", "取数",
             "抽样总体带入（linkedIncrease / syncPopulationFromLinked）", "useH1AdditionCheck"),
            ("折旧起算日推送 H1-12", "按资产编号/名称将折旧起算日(暂估转固优先)推送 H1-12", "取数",
             "折旧起算联动（pushDepStartToH12）", "useH1AdditionCheck"),
            ("在建工程转入合计 ↔ H2 转固", "Σ(增加方式=在建工程转入)原值", "logic_check",
             "供与 H2 转固勾稽（cipTransferInTotal）", "useH1AdditionCheck"),
            ("购建固定资产支付现金合计 ↔ CFS", "Σ 样本支付金额", "logic_check",
             "与现金流量表投资活动勾稽（cashPaidTotal）", "useH1AdditionCheck"),
        ],
        # H1-8 减少检查（清理净损益 + 联动 H10/H6）
        "H1-8": [
            ("净值", "原值 − 累计折旧 − 减值准备", "计算",
             "样本行净值（calcNetValue）", "useH1DisposalCheck"),
            ("处置净损益", "处置收入 − 净值 − 处置费用", "计算",
             "处置损益（calcDisposalGainLoss）", "useH1DisposalCheck / useH1FormulaEngine"),
            ("检查覆盖率", "样本原值合计 ÷ 本期减少合计 × 100%", "计算",
             "抽查覆盖率（summary.coverageRate）", "useH1DisposalCheck"),
            ("本期减少合计带入", "取 H1-2 原值本期减少合计（回退 H1-1 原值贷方）", "取数",
             "抽样总体带入（linkedDecrease / syncPopulationFromLinked）", "useH1DisposalCheck"),
            ("出售关联方缺评估报告", "减少方式=出售 ∧ 关联方 ∧ 无评估报告", "logic_check",
             "关联方处置评估提示（needsEvalWarning）", "useH1DisposalCheck"),
            ("报废无收入残值提示", "报废/损毁 ∧ 清理收入=0 ∧ 净值>0", "logic_check",
             "残值回收/废料变卖/保险赔款漏记提示（needsScrapResidualWarning）", "useH1DisposalCheck"),
            ("处置完成联动 H10/H6", "发布处置明细（原值/折旧/减值/净值/收入/费用/损益）", "取数",
             "publishDisposalCompleted（h1:disposal-completed → H10 资产处置收益 / H6 清理）",
             "useH1DisposalCheck"),
        ],
        # H1-12 折旧测算（直线法/双倍余额/年数总和/工作量法 + 含减值分段）
        "H1-12": [
            ("直线法月折旧", "原值 × (1 − 残值率) ÷ 使用年限 ÷ 12", "计算",
             "直线法（calcStraightLine）", "useH1DepreciationEngine"),
            ("双倍余额递减法月折旧", "账面净值 × 2 ÷ 使用年限 ÷ 12；最后 24 个月转直线法(净值 ÷ 剩余月数)", "计算",
             "双倍余额递减（calcDoubleDeclining）", "useH1DepreciationEngine"),
            ("年数总和法月折旧", "原值 × (1 − 残值率) × 剩余年限 ÷ 年数总和 ÷ 12", "计算",
             "年数总和法，年数总和=n(n+1)/2（calcSumOfYears）", "useH1DepreciationEngine"),
            ("工作量法月折旧", "原值 × (1 − 残值率) ÷ 预计总工作量 × 当月工作量", "计算",
             "工作量法（calcUnitsOfProduction）", "useH1DepreciationEngine"),
            ("含减值折旧", "减值后 = (账面净值 − 残值) ÷ 剩余月数；减值前按原月折旧接力", "计算",
             "含单次减值分段（calcDepreciationWithImpairment / calcWithImpairmentTest）", "useH1DepreciationEngine"),
            ("多次减值分段折旧", "各段 = (原值 − 累计折旧 − 累计减值 − 残值) ÷ 剩余月数", "计算",
             "多次减值切段测算（calcMultiImpairmentTest）", "useH1DepreciationEngine"),
            ("本期应提折旧月份", "自「开始使用次月」至资产负债表日月数(处置次月止提)", "计算",
             "CAS/税法惯例（calcMonthsDepreciated / calcPeriodDepMonths）", "useH1DepreciationEngine"),
            ("满折日", "开始使用次月 + 使用月限 − 1 天所在月末", "计算",
             "测算到期日（calcFullDepreciationDate）", "useH1DepreciationEngine"),
            ("累计折旧单调性校验", "累计折旧序列严格递增(排除处置月)", "logic_check",
             "折旧单调性（isMonotonicallyIncreasing）", "useH1DepreciationEngine"),
            ("月折旧/累计折旧差异", "账面月折旧 − 测算月折旧 / 账面累计 − 测算累计", "logic_check",
             "账面与测算核对（monthlyDiff / accDepDiff）", "useH1DepreciationEngine"),
        ],
        # H1-13 折旧分配（矩阵：分类 × 费用科目）
        "H1-13": [
            ("行分配合计", "生产成本 + 制造费用 + 销售费用 + 管理费用 + 研发费用 + 其他", "计算",
             "各分类分配合计（calcRowAllocSum）", "useH1DepreciationAlloc"),
            ("行平衡校验", "行分配合计 = H1-12 该类别折旧总额", "logic_check",
             "横向配平（isRowBalanced / categoryDiffs，容差 0.01）", "useH1DepreciationAlloc"),
            ("从 H1-12 按分类同步折旧总额", "按资产分类 Σ(H1-12 本期折旧合计)", "取数",
             "折旧总额同步（depreciationForAlloc / crossSheetByCategory）", "useH1CrossSheet / useH1DepreciationAlloc"),
            ("列合计", "各费用科目 Σ(各分类分配额)", "计算",
             "生产成本→F5/制造费用→F2/销售费用→K8/管理费用→K9/研发→I6（colTotals）", "useH1DepreciationAlloc"),
            ("分配合计 ↔ H1-12 折旧总额", "Σ 分配 − H1-12 折旧总额", "logic_check",
             "纵向配平（vsH12Diff / isBalancedWithH12）", "useH1DepreciationAlloc"),
            ("列合计 ↔ 对方费用底稿勾稽", "本表各费用列合计 − 对方底稿(F5/F2/K8/K9/I6)折旧数", "logic_check",
             "跨科目勾稽（reconciliationRows / buildCounterpartDiffNote）", "useH1DepreciationAlloc"),
        ],
        # H1-14 减值迹象 + 测算表
        "H1-14": [
            ("减值迹象 6 项判断", "市价下跌/技术法律环境变化/市场利率提高/陈旧损坏/闲置终止使用/绩效低于预期 任一=是→存在迹象", "logic_check",
             "CAS8 减值迹象（indications / INDICATION_DEFINITIONS / hasIndication）", "useH1Impairment"),
            ("可收回金额⑤", "MAX(公允价值减处置费用净额③, 预计未来现金流量现值④)", "计算",
             "可收回金额（recoverableAmount / _recalcCalcRow）", "useH1Impairment"),
            ("期末应计提减值⑥", "MAX(账面价值② − 可收回金额⑤, 0)", "计算",
             "应计提减值（impairmentAmount）", "useH1Impairment"),
            ("本期应补提减值⑧", "MAX(应计提⑥ − 已计提⑦, 0)", "计算",
             "CAS8 减值一经确认不得转回（supplementTotal / totalDiff）", "useH1Impairment"),
            ("按类别汇总", "按固定资产类别 Σ(账面/可收回/应计提/已计提/补提)", "计算",
             "分类汇总（categoryTotals）", "useH1Impairment"),
            ("从 H1-4 闲置带入账面", "取 H1-4 闲置资产净值>0 的行", "取数",
             "闲置资产带入（parseIdleAssetsFromH4 / idleAssetsAvailable）", "useH1Impairment"),
            ("H1-14 ↔ H1-15 DCF 回写校验", "H1-14 行 ③公允净额/④DCF − H1-15 同名资产组测算值", "logic_check",
             "减值测算与可收回金额同步（DcfSyncCheck）", "useH1Impairment"),
            ("编制校验", "分类⑥合计 = 明细⑥合计；分类⑦合计 = 明细⑦合计", "logic_check",
             "分类汇总与明细勾稽（prepValidation）", "useH1Impairment"),
            ("补提 ↔ K11 资产减值损失勾稽", "H1-14 本期补提合计 − K11 固定资产减值损失", "logic_check",
             "跨底稿减值勾稽（K11ReconcileResult）", "useH1Impairment"),
        ],
        # H1-15 可收回金额测算（多资产组 DCF/WACC/敏感性）
        "H1-15": [
            ("公允价值减处置费用净额", "公允价值(销售协议价>活跃市场价>估计价) − 处置费用合计", "计算",
             "公允净额（resolveFairValue / calcDisposalTotal / fairValueLessDisposal）", "useH1Impairment"),
            ("权益资本成本(CAPM)", "无风险利率 + β × (市场收益率 − 无风险利率)", "计算",
             "CAPM（calcCostOfEquity）", "useH1Impairment"),
            ("税后加权平均资本成本(WACC)", "权益占比×权益成本 + 债务占比×债务成本×(1−税率)", "计算",
             "税后 WACC（calcWaccAfterTax）", "useH1Impairment"),
            ("税前折现率", "税后 WACC ÷ (1 − 税率)", "计算",
             "税前折现率还原（calcPreTaxDiscountRate）", "useH1Impairment"),
            ("DCF 现值", "Σ(现金流ᵢ ÷ (1 + 折现率)^ᵢ)", "计算",
             "预计未来现金流量现值（calcDcfPresentValue）", "useH1DepreciationEngine / useH1Impairment"),
            ("终值(永续价值)", "永续现金流 ÷ (折现率 − 增长率)", "计算",
             "Gordon 增长模型（calcTerminalValue），折现率≤增长率返 0", "useH1DepreciationEngine"),
            ("可收回金额", "MAX(公允价值减处置费用净额, DCF 总现值)", "计算",
             "可收回金额（recoverableAmount / recoverableSource）", "useH1Impairment"),
            ("隐含减值", "MAX(账面价值 − 可收回金额, 0)", "计算",
             "隐含减值（impliedImpairment）", "useH1Impairment"),
            ("敏感性矩阵", "折现率 ± 偏移 × 增长率 ± 偏移 → 可收回金额网格", "计算",
             "二维敏感性 + 终值单独敏感轴（sensitivityMatrix / terminalSensitivityByRate）", "useH1Impairment"),
        ],
        # H1-19 经营租出固定资产
        "H1-19": [
            ("租赁收益率", "净收益 ÷ 原值 × 100%", "计算",
             "经营租出收益率（calcLeaseReturnRate）", "useH1FormulaEngine"),
            ("租金收入合计", "Σ 各经营租出资产账面租金", "取数",
             "供 H1-6 分析表引用（leaseRentAuto）", "useH1Analysis"),
        ],
        # H1-20 融资租赁（出租人/承租人初始计量 + 内含利率 + 实际利率法摊销）
        "H1-20": [
            ("应收融资租赁款", "最低租赁收款额 + 初始直接费用", "计算",
             "出租人初始计量（calcFinanceLeaseReceivable）", "useH1FormulaEngine"),
            ("毛投资额", "最低租赁收款额 + 未担保余值 + 初始直接费用", "计算",
             "租赁投资总额（calcGrossLeaseInvestment）", "useH1FormulaEngine"),
            ("未确认融资收益", "(最低租赁收款额 + 未担保余值) − 租赁投资净额", "计算",
             "未确认融资收益（calcUnearnedFinanceIncome）", "useH1FormulaEngine"),
            ("现值/公允价值占比", "租赁付款额现值 ÷ 公允价值 × 100%", "logic_check",
             "≥90% 通常满足融资租赁第④项（calcPvToFvRatio）", "useH1FormulaEngine"),
            ("租赁内含利率", "求解 r 使 NPV(r)=0：−净投资 + Σ租金/(1+r)^t + 未担保余值/(1+r)^n = 0", "计算",
             "牛顿法 + 二分兜底（solveLeaseImplicitRatePct / calcLeaseNpv）", "useH1FormulaEngine"),
            ("融资租赁摊销表", "融资收入 = 期初净投资 × 内含利率；净额减少 = 租金 − 融资收入；期末 = 期初 − 净额减少", "计算",
             "实际利率法分配（buildFinanceLeaseAmortization）", "useH1FormulaEngine"),
        ],
        # 附注披露（上市/国企）
        "附注上市": [
            ("附注变动表取数", "原值/累计折旧/减值 期初/增加/减少/期末取自 H1-2 明细、H1-1 审定", "取数",
             "附注取数（h1ListedDisclosureModel）", "useH1Disclosure / h1DisclosureSections"),
            ("已提足折旧仍继续使用的固定资产", "净值 ≤ 原值 × 残值率(默认5%) ∧ 累计折旧>0 → 按类别汇总账面原值", "计算",
             "CAS 披露项（deriveFullyDepreciatedFromDetail / FullyDepRow）", "useH1Disclosure"),
        ],
        "附注国企": [
            ("附注变动表取数", "原值/累计折旧/减值 期初/增加/减少/期末取自 H1-2 明细、H1-1 审定", "取数",
             "附注取数（h1SoeDisclosureModel）", "useH1Disclosure / h1DisclosureSections"),
            ("已提足折旧仍继续使用的固定资产", "按国企分类标签汇总账面原值（净值≤残值 ∧ 累计折旧>0）", "计算",
             "CAS 披露项（deriveSoeFullyDepreciated）", "useH1Disclosure"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # H2 在建工程（1604 / 工程物资 1605；CAS17 利息资本化 + 转固 + 减值）
    # ═══════════════════════════════════════════════════════════════════════
    "H2": {
        # H2-1 审定表（原值 → 减值 → 净值）
        "H2-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各行审定金额（calcAuditedAmount）", "useH2Adjudication"),
            ("净值", "在建工程原值 − 减值准备", "计算",
             "净值行（netRows / netIdentityDiff）", "useH2Adjudication"),
            ("变动额 / 变动率", "期末审定 − 期初审定 /(期末−期初) ÷ 期初", "计算",
             "变动分析（calcChangeRate），|变动率|≥30% 标红（CHANGE_RATE_THRESHOLD）", "useH2FormulaEngine / useH2Adjudication"),
            ("从 H2-2 明细带入", "按项目 Σ(H2-2 期末未审/期末审定)", "取数",
             "审定表取数（syncFromH22）", "useH2Adjudication"),
            ("从 H2-3 账项调整回写", "H2-3 科目 1604 账项净额(借−贷)分摊回写期末账项调整", "取数",
             "调整回写（syncEndAdjustmentFromH23 / adjustmentSync.cipAjeNet）", "useH2Adjudication / useH2CrossSheet"),
            ("净值身份校验", "净值 − (原值审定 − 减值审定)", "logic_check",
             "净值恒等（netIdentityDiff）", "useH2Adjudication"),
            ("三角勾稽校验", "期末 − (期初 + 增加 − 转固 − 减少)", "logic_check",
             "含转固三角勾稽（triangleErrors / calcTriangleWithTransfer）", "useH2FormulaEngine"),
            ("试算平衡表数核对", "审定合计 − 试算平衡表数(1604 在建工程 / 1605 工程物资)", "logic_check",
             "TB 核对（tbCompareRows / diffRow）", "useH2Adjudication"),
            ("审定表 ↔ H2-2 明细勾稽", "H2-1 审定合计 − H2-2 明细期末合计", "logic_check",
             "明细勾稽（detailDiff）", "useH2Adjudication / useH2CrossSheet"),
            ("审定表 ↔ H2-5 转固勾稽", "H2-1 转固合计 − H2-5 转固检查合计", "logic_check",
             "转固勾稽（transferDiff）", "useH2CrossSheet"),
        ],
        # H2-2 明细表（在建工程项目 roll-forward + 完工进度）
        "H2-2": [
            ("期末未审", "期初 + 本期增加 − 转固 − 其他减少", "计算",
             "在建工程项目期末（calcCipEndBalance）", "useH2FormulaEngine / useH2Detail"),
            ("期末审定", "期末未审 + 账项调整", "计算",
             "明细审定 roll-forward（recalcRow）", "useH2Detail"),
            ("资本化利息期末", "期初资本化利息 + 本期资本化利息", "计算",
             "累计资本化利息（含入在建工程成本）", "useH2Detail"),
            ("完工进度", "累计投入 ÷ 预算总投资 × 100%", "计算",
             "完工进度（calcCompletionRate）", "useH2FormulaEngine"),
            ("合计", "Σ 各项目行", "计算",
             "明细合计（calcSubtotal）", "useH2Detail"),
            ("H2-2 ↔ H2-1 交叉验证", "H2-2 期末合计 − H2-1 审定合计", "logic_check",
             "明细↔审定勾稽（crossValidationH1）", "useH2Detail"),
        ],
        # H2-10 利息资本化（无专门借款，一般借款；CAS17）
        "H2-10": [
            ("累计资产支出加权平均", "半月平均法：Σ(每笔支出 × 占用月数/期间月数)", "计算",
             "月度加权支出链（calcMonthlyWeightedExpChain / calcWeightedPrincipal）", "useH2InterestCapEngine / useH2InterestCap"),
            ("一般借款加权资本化率", "所占用一般借款利息 ÷ 一般借款本金加权平均", "计算",
             "资本化率（calcCapRateFromActualInterest）", "useH2InterestCapEngine"),
            ("一般借款应资本化利息", "累计资产支出加权平均超过专门借款部分 × 加权资本化率", "计算",
             "一般借款补充资本化（calcGeneralLoanSupp / calcExcessWeightedExp）", "useH2InterestCapEngine"),
            ("合计资本化利息", "专门借款资本化 + 一般借款资本化", "计算",
             "合计资本化（calcTotalCapWithBorrow）", "useH2InterestCapEngine"),
            ("差异率", "(测算资本化 − 账面资本化) ÷ 账面资本化", "logic_check",
             "资本化差异（calcCapDiffRate）", "useH2InterestCapEngine"),
            ("从 L1 带入一般借款", "取 L1 短期借款/一般借款本金、利率、账面利息", "取数",
             "跨底稿带入（pullGeneralLoansFromL1）", "useH2InterestCap"),
            ("资本化利息上限校验", "累计资本化利息 ≤ 当期实际发生利息", "logic_check",
             "CAS17 上限（exceedsInterestCeiling）", "useH2InterestCapEngine"),
        ],
        # H2-11 利息资本化（有专门借款）
        "H2-11": [
            ("专门借款应资本化利息", "MAX(0, 专门借款当期利息 − 闲置资金存款收益/投资收益)", "计算",
             "专门借款资本化（calcSpecialLoanCap）", "useH2InterestCapEngine"),
            ("超额支出", "累计资产支出加权平均 − 专门借款本金", "计算",
             "超额支出转一般借款（calcExcessWeightedExp）", "useH2InterestCapEngine"),
            ("差异率", "(测算资本化 − 账面资本化) ÷ 账面资本化", "logic_check",
             "资本化差异（calcCapDiffRate）", "useH2InterestCapEngine"),
        ],
        # H2-5 转固检查（CAS4 达到预定可使用状态）
        "H2-5": [
            ("净值", "转固资产原值 − 减值准备", "计算",
             "转固资产净值（calcNetValue）", "useH2FormulaEngine"),
            ("达到预定可使用状态判定", "实体建造完成/主要支出发生/试运行正常等五条件", "logic_check",
             "CAS4 转固条件（calcTransferCondition）", "useH2TransferCheck"),
            ("延迟转固天数", "资产负债表日 − 达到预定可使用状态日", "计算",
             "延迟转固（calcOverdueDays，阈值 30 天）", "useH2TransferCheck"),
            ("少计折旧", "延迟转固期间应计未计折旧", "计算",
             "少计折旧测算（calcMissedDepreciation）", "useH2TransferCheck"),
            ("转固 ↔ H1 入账勾稽", "H2 转固金额 − H1 固定资产本期在建工程转入入账", "logic_check",
             "转固入账勾稽（h1TransferReconcile / crossValidationH1）", "useH2TransferCheck / useH2CrossSheet"),
        ],
        # H2-8 增加检查
        "H2-8": [
            ("检查覆盖率", "已检查金额 ÷ 本期增加合计 × 100%", "计算",
             "抽查覆盖率（summary.coverageRate）", "useH2AdditionCheck"),
            ("证据缺口标记", "缺合同/发票/验收单/付款凭证 → 异常", "logic_check",
             "证据完整性（needs*Warning）", "useH2AdditionCheck"),
        ],
        # H2-9 减少检查
        "H2-9": [
            ("检查覆盖率", "样本金额 ÷ 本期减少合计 × 100%", "计算",
             "抽查覆盖率（summary.coverageRate）", "useH2DecreaseCheck"),
            ("竣工决算调整回写", "决算差异分录 借 1601 固定资产 / 贷 1604 在建工程", "logic_check",
             "决算 AJE（1601↔1604 勾稽）", "useH2DecreaseCheck"),
        ],
        # H2-15 / H2-16 减值测算（CAS8）
        "H2-15": [
            ("可收回金额", "MAX(公允价值减处置费用净额, 预计未来现金流量现值)", "计算",
             "可收回金额（calcRecoverableAmount / DCF）", "useH2Impairment"),
            ("应计提减值", "MAX(账面价值 − 可收回金额, 0)", "计算",
             "应计提减值（calcRequiredImpairment）", "useH2Impairment"),
            ("本期应补提减值", "MAX(应计提 − 已计提, 0)", "计算",
             "CAS8 不得转回；减值 AJE 借 6701 / 贷 1604（calcImpairmentSupplement）", "useH2Impairment"),
            ("权益成本 / WACC / 税前折现率", "CAPM + 税后 WACC + 税前还原", "计算",
             "折现率（calcCostOfEquity / calcWaccAfterTax / calcPreTaxDiscountRate）", "useH2Impairment"),
            ("减值回写一致性", "减值测算 ↔ 审定表减值段回写状态", "logic_check",
             "回写状态（classifySyncStatus）", "useH2Impairment"),
        ],
        # 附注披露（上市/国企）
        "附注上市": [
            ("附注变动表取数", "期初/期末取自 H2-1 审定；增减/转固取自 H2-2；资本化利息取自 H2-10/H2-11；减值取自 H2-1 减值审定", "取数",
             "附注取数（disclosureAutoFill）", "useH2CrossSheet"),
        ],
        "附注国企": [
            ("附注变动表取数", "期初/期末取自 H2-1 审定；增减/转固取自 H2-2；资本化利息取自 H2-10/H2-11", "取数",
             "附注取数（disclosureAutoFill）", "useH2CrossSheet"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # H3 投资性房地产（1503 / 累计折旧 1504 / 减值 1505；成本模式 + 公允模式双计量 + 互转）
    # ═══════════════════════════════════════════════════════════════════════
    "H3": {
        # H3-1 审定表（成本模式=useH3AdjudicationCost / 公允模式=useH3AdjudicationFair 双版本）
        "H3-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各行审定金额（calcAuditedAmount）", "useH3AdjudicationCost / useH3AdjudicationFair"),
            ("净值（成本模式）", "投资性房地产原值 − 累计折旧 − 减值准备", "计算",
             "成本模式三区块净值（calcNetValue）", "useH3AdjudicationCost / useH3FormulaEngine"),
            ("期末余额（公允模式）", "期初 + 增加 − 减少 + 公允价值变动损益", "计算",
             "公允价值模式审定（calcFairEndBalance）", "useH3AdjudicationFair / useH3FormulaEngine"),
            ("变动额 / 变动率", "期末审定 − 期初审定 /(期末−期初) ÷ 期初", "计算",
             "变动分析（calcChangeRate）", "useH3FormulaEngine"),
            ("从 H3-2 明细带入", "按类别 Σ(H3-2 期末审定/期初审定)", "取数",
             "审定表取数（fillFromH32Detail / aggregateH32CostByCategory）", "useH3CrossSheet"),
            ("三角勾稽校验（成本模式）", "期末 − (期初 + 增加 − 减少)", "logic_check",
             "成本模式三角勾稽", "useH3AdjudicationCost"),
            ("借贷平衡校验", "Σ 借方 = Σ 贷方", "logic_check",
             "调整借贷平衡（isBalanced）", "useH3AdjudicationCost / useH3AdjudicationFair"),
            ("试算平衡表数核对", "审定合计 − 试算平衡表数(1503/1504/1505)", "logic_check",
             "TB 核对（loadTbData）", "useH3CrossSheet"),
            ("H3-2 ↔ H3-1 交叉验证", "H3-2 明细期末合计 − H3-1 审定合计", "logic_check",
             "明细勾稽（crossValidationDiff）", "useH3CrossSheet"),
            ("H3-1 ↔ H3-8 公允复核勾稽", "H3-1 公允审定 − H3-8 公允价值复核合计", "logic_check",
             "公允复核勾稽（h38Reconcile）", "useH3CrossSheet"),
            ("H3-1 ↔ H3-7 折旧勾稽", "H3-1 累计折旧本期计提 − H3-7 折旧测算合计", "logic_check",
             "折旧勾稽（h31DepReconcile）", "useH3CrossSheet"),
        ],
        # H3-2 明细表（成本模式=useH3DetailCost / 公允模式=useH3DetailFair）
        "H3-2": [
            ("期末余额（成本模式）", "原值/折旧/减值各区块 期末 = 期初 + 增加 − 减少", "计算",
             "成本明细期末（useH3DetailCost / calcNetValue）", "useH3DetailCost / useH3FormulaEngine"),
            ("期末余额（公允模式）", "期初 + 增加 − 减少 + 公允价值变动", "计算",
             "公允明细期末（calcFairEndBalance）", "useH3DetailFair / useH3FormulaEngine"),
            ("净值", "原值 − 累计折旧 − 减值准备", "计算",
             "成本明细净值（calcNetValue）", "useH3DetailCost"),
            ("合计", "Σ 各明细行", "计算",
             "明细合计（calcSubtotal）", "useH3FormulaEngine"),
        ],
        # H3-3 调整分录
        "H3-3": [
            ("调整净额", "借方调整金额 − 贷方调整金额（1503/1504/1505 按科目归集）", "计算",
             "调整回写（adjustmentSync）", "useH3CrossSheet"),
            ("借贷平衡校验", "Σ 借方 = Σ 贷方", "logic_check",
             "调整借贷平衡（isBalanced）", "useH3CrossSheet"),
        ],
        # H3-6 互转审核（自用/存货 ↔ 投资性房地产）
        "H3-6": [
            ("互转结转金额", "成本模式按账面价值结转；公允模式差额计入公允价值变动损益/其他综合收益", "计算",
             "四方向互转（useH3TransferEngine 的 OCI/PL 处理）", "useH3TransferEngine"),
            ("互转汇总取数", "读 H1 固定资产 / H2 在建工程 互转对方数", "取数",
             "互转汇总（transferSummary）", "useH3CrossSheet"),
        ],
        # H3-7 折旧测算（成本模式）
        "H3-7": [
            ("直线法折旧", "原值 × (1 − 残值率) ÷ 使用年限", "计算",
             "直线法/含减值折旧（useH3DepreciationEngine）", "useH3DepreciationEngine"),
        ],
        # H3-8 公允价值复核
        "H3-8": [
            ("公允价值复核合计 ↔ H3-1", "H3-8 公允价值合计 − H3-1 公允审定", "logic_check",
             "公允复核勾稽入 H3-1（h38Reconcile）", "useH3CrossSheet"),
        ],
        # H3-10 减值测算（成本模式，CAS8）
        "H3-10": [
            ("可收回金额", "MAX(公允价值减处置费用净额, 预计未来现金流量现值)", "计算",
             "可收回金额（DCF）", "useH3Impairment"),
            ("应计提减值", "MAX(账面价值 − 可收回金额, 0)", "计算",
             "应计提减值（CAS8 不得转回）", "useH3Impairment"),
            ("H3-10 ↔ H3-11 DCF 回写校验", "H3-10 ④DCF/⑤可收回 − H3-11 资产组测算值", "logic_check",
             "减值测算与可收回金额同步（dcfSyncChecks）", "useH3CrossSheet"),
            ("补提 ↔ K11 资产减值损失勾稽", "H3-10 本期补提 − K11 投资性房地产减值损失", "logic_check",
             "跨底稿减值勾稽（k11Reconcile）", "useH3CrossSheet"),
        ],
        # H3-11 可收回金额（DCF/WACC）
        "H3-11": [
            ("DCF 现值 / 终值 / WACC", "Σ(现金流/(1+r)^t) + 终值现值；税后 WACC 折现", "计算",
             "预计未来现金流量现值（DCF/终值/WACC）", "useH3Impairment"),
        ],
        # H3-14 租金收入
        "H3-14": [
            ("应计租金", "租赁月数 × 月租金", "计算",
             "应计租金（useH3RentalIncome）", "useH3RentalIncome"),
            ("租金已计 ↔ D4-3 勾稽", "H3-14 已计租金 − D4-3 其他业务收入(投房租金)", "logic_check",
             "跨底稿收入勾稽（d43Reconcile）", "useH3RentalCrossSheet"),
            ("租金 ↔ TB 6051 勾稽", "H3-14 租金合计 − 试算平衡表 6051 其他业务收入", "logic_check",
             "损益勾稽（plReconcile）", "useH3RentalCrossSheet"),
        ],
        # 附注披露（上市/国企）
        "附注上市": [
            ("附注变动表取数", "成本模式(原值/折旧/减值)或公允模式(公允价值变动)取自 H3-1/H3-2 多源", "取数",
             "附注取数（disclosureAutoFill）", "useH3Disclosure / useH3CrossSheet"),
            ("公允价值层次", "从 H3-8 公允复核带入公允价值层次", "取数",
             "公允层次披露取数", "useH3Disclosure"),
        ],
        "附注国企": [
            ("附注变动表取数", "成本模式(原值/折旧/减值)或公允模式取自 H3-1/H3-2 多源", "取数",
             "附注取数（disclosureAutoFill）", "useH3Disclosure / useH3CrossSheet"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # H4 工程物资（1605 借方 / 减值准备 备抵；净值两区块 + 减值可收回）
    #    注：平台 H4 实为「工程物资」，非「使用权资产」（使用权资产在 H8）。
    # ═══════════════════════════════════════════════════════════════════════
    "H4": {
        # H4-1 审定表（一、原值 → 二、减值准备 → 三、净值）
        "H4-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各行审定金额（calcAuditedAmount）", "useH4Adjudication"),
            ("原值期末余额", "期初余额 + 借方发生 − 贷方发生", "计算",
             "借方资产科目 1605 期末（calcAssetEndBalance）", "useH4FormulaEngine"),
            ("净值", "工程物资原值审定 − 减值准备审定", "计算",
             "两区块净值（calcNetValue）", "useH4FormulaEngine / useH4Adjudication"),
            ("变动额 / 变动率", "期末审定 − 期初审定 /(期末−期初) ÷ 期初", "计算",
             "变动分析（calcH4ChangeRate），|变动率|≥30% 标红", "useH4FormulaEngine"),
            ("净值身份校验", "净值 − (原值审定 − 减值审定)", "logic_check",
             "净值恒等校验", "useH4Adjudication"),
            ("试算平衡表数核对", "审定合计 − 试算平衡表数(1605)", "logic_check",
             "TB 核对（1605 工程物资）", "useH4Adjudication"),
            ("报表核对", "(工程物资净值 + 在建工程) − 报表数", "logic_check",
             "与经审计财务报表核对（涉 1604 在建工程）", "useH4Adjudication"),
            ("审定表 ↔ H4-2 明细勾稽", "H4-1 审定合计 − H4-2 明细期末合计", "logic_check",
             "明细勾稽（adjudicationVsDetail）", "useH4CrossSheet"),
            ("附注自动取数", "分类表期末/上期取自 H4-1 审定", "取数",
             "附注取数", "useH4Adjudication"),
        ],
        # H4-2 明细表
        "H4-2": [
            ("期末原值", "期初 + 本期入库(借) − 本期减少(贷)", "计算",
             "工程物资明细期末（calcAssetEndBalance）", "useH4Detail / useH4FormulaEngine"),
            ("入库/减少小计", "Σ 本期入库 / Σ 本期减少", "计算",
             "增减小计", "useH4Detail"),
            ("单价", "金额 ÷ 数量（数量为 0 防除零返 0）", "计算",
             "单价（防除零）", "useH4FormulaEngine"),
            ("净值", "原值 − 减值准备", "计算",
             "明细净值（calcNetValue）", "useH4FormulaEngine"),
            ("审定原值期末", "审定期初 + 审定入库 − 审定减少", "计算",
             "审定 roll-forward", "useH4Detail"),
            ("净值差异勾稽", "明细净值合计 − 审定净值", "logic_check",
             "净值勾稽", "useH4Detail"),
            ("分类小计", "按类别 Σ 各明细行", "计算",
             "分类小计", "useH4Detail"),
        ],
        # H4-3 调整分录
        "H4-3": [
            ("调整净额", "借方调整金额 − 贷方调整金额（减值段取反）", "计算",
             "调整净额（减值备抵取反）", "useH4CrossSheet"),
        ],
        # H4-4 增加检查
        "H4-4": [
            ("检查比例", "已检查金额 ÷ 本期增加合计 × 100%", "计算",
             "抽查覆盖率", "useH4AdditionCheck"),
            ("发票差异", "|账面金额 − 发票金额| > 阈值", "logic_check",
             "账面与发票核对", "useH4AdditionCheck"),
            ("从 H4-2 增加带入", "取 H4-2 本期增加合计作总体", "取数",
             "总体带入", "useH4AdditionCheck"),
            ("增加 ↔ 借方发生勾稽", "样本增加合计 − H4-2 借方发生", "logic_check",
             "增加勾稽", "useH4AdditionCheck"),
        ],
        # H4-5 减少检查
        "H4-5": [
            ("净值 / 清理净损益", "原值 − 减值 / 处置收入 − 净值 − 费用", "计算",
             "减少样本净值与损益", "useH4DisposalCheck"),
            ("检查比例", "样本减少金额 ÷ 本期减少合计 × 100%", "计算",
             "抽查覆盖率", "useH4DisposalCheck"),
            ("从 H4-2 减少带入", "取 H4-2 本期减少合计作总体", "取数",
             "总体带入", "useH4DisposalCheck"),
            ("减少 ↔ 贷方发生勾稽", "样本减少合计 − H4-2 贷方发生", "logic_check",
             "减少勾稽", "useH4DisposalCheck"),
        ],
        # H4-7 减值测算（CAS8）
        "H4-7": [
            ("可收回金额⑤", "MAX(公允价值减处置费用净额③, 预计未来现金流量现值④)", "计算",
             "可收回金额（calcRecoverableAmount）", "useH4Recoverable / useH4Impairment"),
            ("应计提减值⑥", "MAX(账面价值② − 可收回金额⑤, 0)", "计算",
             "应计提减值", "useH4Impairment"),
            ("本期应补提减值⑧", "MAX(应计提⑥ − 已计提⑦, 0)", "计算",
             "CAS8 不得转回；补提 AJE 借 6701 / 贷 1605", "useH4Impairment"),
            ("从 H4-1 带入 ②账面 / ⑦已计提", "取 H4-1 原值净值 / 减值段审定", "取数",
             "减值测算带入", "useH4Impairment"),
            ("应计提 ↔ H4-1 减值段勾稽", "H4-7 应计提合计 − H4-1 减值审定", "logic_check",
             "减值勾稽", "useH4Impairment"),
        ],
        # H4-8 可收回金额（DCF/WACC）
        "H4-8": [
            ("公允价值减处置费用净额", "公允价值(优先级取值) − 处置费用", "计算",
             "公允净额", "useH4Recoverable"),
            ("权益成本 / 税后 WACC / 税前折现率", "CAPM + WACC + 税前还原", "计算",
             "折现率（calcCostOfEquity / calcWaccAfterTax / calcPreTaxDiscountRate）", "useH4Recoverable"),
            ("可收回金额", "MAX(公允净额, DCF 总现值)", "计算",
             "可收回金额 + 终值现值", "useH4Recoverable"),
            ("隐含减值", "MAX(账面 − 可收回, 0)", "计算",
             "隐含减值", "useH4Recoverable"),
            ("H4-8 ↔ H4-7 勾稽", "H4-8 可收回 − H4-7 ⑤可收回", "logic_check",
             "可收回同步核对", "useH4Recoverable"),
        ],
        # 附注披露（上市/国企）
        "附注上市": [
            ("附注分类表取数", "期末/上期取自 H4-1 审定", "取数",
             "分类表取数", "useH4Disclosure"),
            ("净值", "原值 − 减值准备", "计算",
             "净值披露", "useH4Disclosure"),
            ("附注 ↔ 审定勾稽", "附注合计 − H4-1 审定合计", "logic_check",
             "披露勾稽", "useH4Disclosure"),
        ],
        "附注国企": [
            ("附注分类表取数", "期末/上期取自 H4-1 审定", "取数",
             "分类表取数", "useH4Disclosure"),
            ("附注 ↔ 审定勾稽", "附注合计 − H4-1 审定合计", "logic_check",
             "披露勾稽", "useH4Disclosure"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # H5 生产性生物资产/油气资产（油气 1631 / 累计折耗 1632 备抵；单位产量法折耗，IndustryGuard）
    # ═══════════════════════════════════════════════════════════════════════
    "H5": {
        # H5-1 审定表（原值 → 累计折耗 → 减值 → 净值）
        "H5-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各行审定金额（calcAuditedAmount）", "useH5Adjudication / useH5FormulaEngine"),
            ("原值期末余额", "期初余额 + 借方发生 − 贷方发生", "计算",
             "借方资产科目 1631 期末（calcAssetEndBalance）", "useH5FormulaEngine"),
            ("累计折耗期末余额", "期初余额 + 贷方发生(计提) − 借方发生(转销)", "计算",
             "备抵类 1632 期末（calcContraEndBalance）", "useH5FormulaEngine"),
            ("净值", "原值 − 累计折耗 − 减值准备", "计算",
             "三区块净值（calcNetValue）", "useH5FormulaEngine"),
            ("区块小计", "Σ 区块内明细行", "计算",
             "各区块小计（calcSubtotal）", "useH5Adjudication"),
            ("三角勾稽校验", "期末 − (期初 + 增加 − 减少)", "logic_check",
             "原值/折耗三角勾稽", "useH5FormulaEngine"),
            ("审定 ↔ H5-2 明细交叉验证", "H5-1 审定合计 − H5-2 明细期末合计", "logic_check",
             "明细勾稽（adjudicationVsDetail）", "useH5CrossSheet"),
            ("行业适用性守卫", "科目/行业 ∈ {oil_gas, mining} 才启用油气/采矿口径", "logic_check",
             "行业适用性（useH5IndustryGuard）", "useH5IndustryGuard"),
            ("审定回写 TB", "原值(1631)/累计折耗(1632) 审定数回写 trial_balance", "取数",
             "publishAdjudicated（account_codes 1631/1632）", "useH5Adjudication"),
        ],
        # H5-2 明细表
        "H5-2": [
            ("原值期末", "期初 + 本期增加 − 本期减少", "计算",
             "明细原值期末（calcAssetEndBalance）", "useH5Detail / useH5FormulaEngine"),
            ("累计折耗期末", "期初 + 本期计提 − 本期转回/转销", "计算",
             "明细折耗期末（calcContraEndBalance）", "useH5Detail"),
            ("净值", "原值 − 累计折耗 − 减值准备", "计算",
             "明细净值（calcNetValue）", "useH5FormulaEngine"),
            ("合计", "Σ 各明细行", "计算",
             "明细合计（calcSubtotal）", "useH5Detail"),
            ("明细 ↔ 审定交叉验证", "H5-2 期末合计 − H5-1 审定合计", "logic_check",
             "明细↔审定勾稽（adjudicationVsDetail）", "useH5CrossSheet"),
        ],
        # H5-12 折耗测算（单位产量法）
        "H5-12": [
            ("剩余可采储量", "预计总储量 − 累计产量", "计算",
             "剩余可采储量（useH5DepletionEngine）", "useH5DepletionEngine"),
            ("单位产量法折耗", "(原值 − 预计净残值) × 当期产量 ÷ 剩余可采储量", "计算",
             "单位产量法（useH5DepletionEngine）", "useH5DepletionEngine / useH5Depletion"),
            ("含减值后折耗", "(减值后账面 − 残值) × 当期产量 ÷ 剩余可采储量", "计算",
             "减值后折耗重算（useH5DepletionEngine）", "useH5DepletionEngine"),
            ("折耗封顶", "累计折耗 ≤ 原值 − 预计净残值", "logic_check",
             "折耗上限（折耗封顶）", "useH5DepletionEngine"),
            ("折耗率", "本期折耗 ÷ 原值 × 100%", "计算",
             "折耗率", "useH5FormulaEngine"),
            ("本期折耗合计", "Σ 各资产本期折耗", "计算",
             "折耗合计（calcSubtotal）", "useH5Depletion"),
            ("折耗计提 ↔ 累计折耗贷方勾稽", "H5-12 本期折耗合计 − H5-1 累计折耗本期贷方发生", "logic_check",
             "折耗勾稽", "useH5CrossSheet"),
        ],
        # H5-13 折耗分配
        "H5-13": [
            ("折耗分配合计", "Σ 各费用科目分配额", "计算",
             "折耗分配合计", "useH5CrossSheet"),
            ("分配合计 ↔ 折耗合计勾稽", "H5-13 分配合计 − H5-12 本期折耗合计", "logic_check",
             "折耗分配勾稽", "useH5CrossSheet"),
        ],
        # H5-14 减值测算（CAS8）
        "H5-14": [
            ("可收回金额", "MAX(公允价值减处置费用净额, 预计未来现金流量现值)", "计算",
             "可收回金额", "useH5Impairment"),
            ("应计提减值", "MAX(账面价值 − 可收回金额, 0)", "计算",
             "应计提减值", "useH5Impairment"),
            ("本期应补提减值", "MAX(应计提 − 已计提, 0)", "计算",
             "CAS8 不得转回", "useH5Impairment"),
            ("减值 ↔ 审定减值段勾稽", "H5-14 应计提 − H5-1 减值审定", "logic_check",
             "减值勾稽", "useH5Impairment"),
        ],
        # H5-6 分析表
        "H5-6": [
            ("变动率 / 折耗率", "(本期 − 上期) ÷ 上期 / 本期折耗 ÷ 原值", "计算",
             "分析比率（calcChangeRate）", "useH5Analysis / useH5FormulaEngine"),
            ("重大变动异常项", "|变动率| > 30% → 异常项须说明", "logic_check",
             "重大变动标记", "useH5Analysis"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # H6 固定资产清理（1606 借方过渡科目，期末应清零；清理净损益 ↔ H10）
    # ═══════════════════════════════════════════════════════════════════════
    "H6": {
        "H6-1": [
            ("审定数", "期初/期末审定 = 对应未审数 + 账项调整（AJE）", "计算",
             "审定表各行审定金额（calcAuditedAmount，_applyFormulas）/审定表H6-1", "useH6Adjudication"),
            ("变动额", "变动额 = 期末审定数 − 期初审定数", "计算",
             "本期审定与上期审定比较（auditedChange，_applyFormulas）/审定表H6-1", "useH6Adjudication"),
            ("变动率", "变动率 = 变动额 ÷ |期初审定|×100%；期初=0且变动=0→0，期初=0且变动≠0→±100%", "计算",
             "变动率（calcH6ChangeRate）/审定表H6-1", "useH6FormulaEngine"),
            ("合计", "合计 = Σ各清理项目（期初/期末未审、账项调整、审定）", "计算",
             "审定表合计行（calcSubtotal，_sumRow）/审定表H6-1", "useH6Adjudication"),
            ("清理净损益", "清理净损益 = 处置收入 − 净值 − 清理费用 − 税费（优先取自 H6-2 合计）", "计算",
             "固定资产清理净损益（calcDisposalGainLoss / disposalGainLoss）/审定表H6-1", "useH6Adjudication"),
            ("从明细表带入", "各清理项目金额（期初/期末未审、期初/期末账项调整）自 H6-2 明细表带入", "取数",
             "从 H6-2 回填审定表行（syncFromH62 / mapH62RowToAdjudication，跨 sheet 键 H6-2-rows）/审定表H6-1", "useH6Adjudication"),
            ("从调整分录回写", "期末账项调整自 H6-3 科目1606账项/报表净额按未审权重分摊回写", "取数",
             "从 H6-3 回写期末账项调整（syncEndAdjFromH63 / syncAjeRjeFromAdjustment，跨 sheet 键 H6-3-rows）/审定表H6-1", "useH6Adjudication"),
            ("固定资产净值带入", "报表核对·固定资产净值 = Σ(原值 − 累计折旧 − 减值准备)，自 H1-1 审定行带入", "取数",
             "从 H1-1 带入固定资产净值（seedFaNetFromH11 / summarizeH11NetValue，跨底稿 H1）/审定表H6-1", "useH6Adjudication"),
            ("未审数取数", "审定表未审数（1606）自试算平衡表 unadjusted_amount 取数", "取数",
             "TB 自动取数（loadTbData，account_code=1606）/审定表H6-1", "useH6FormData"),
            ("过渡科目零余额核对", "1606 为过渡科目，期末审定余额应为 0（|余额|<0.01 判清理完毕）", "logic_check",
             "过渡科目期末余额判定（isTransitBalanceZero / transitCheck / transitAccountStatus）/审定表H6-1", "useH6CrossSheet"),
            ("审定表↔明细表勾稽", "H6-1 清理净损益 应等于 H6-2 明细净损益合计（差额<0.01 视为一致）", "logic_check",
             "审定表 vs 明细表勾稽（adjudicationVsDetail，键 H6-1-disposal-gain-loss / H6-2-subtotal-gain-loss）/审定表H6-1", "useH6CrossSheet"),
            ("清理净损益↔H10勾稽", "H6 清理净损益 应等于 H10 资产处置损益（差额<0.01 视为一致）", "logic_check",
             "H6 vs H10 处置损益勾稽（h10CrossCheck / disposalGainLossVsH10，键 H10-disposal-income）/审定表H6-1", "useH6CrossSheet"),
            ("报表核对", "差异 = (固定资产净值审定 + 固定资产清理审定合计) − 报表数", "logic_check",
             "与经审计财务报表核对（fsCompareRows）/审定表H6-1", "useH6Adjudication"),
            ("审定数回写试算表", "期末审定合计回写试算平衡表科目1606（借方/资产类过渡科目）", "logic_check",
             "审定确认回写 TB（publishAdjudicated / writebackTrialBalance，account_code=1606）/审定表H6-1", "useH6FormData"),
        ],
        "H6-2": [
            ("净值", "净值 = 原值 − 累计折旧 − 减值准备", "计算",
             "固定资产净值（calcNetBookValue）/明细表H6-2", "useH6FormulaEngine"),
            ("清理净损益", "清理净损益 = 处置收入 − 净值 − 清理费用 − 税费", "计算",
             "逐项清理净损益（calcDisposalGainLoss）/明细表H6-2", "useH6FormulaEngine"),
            ("未审期末", "未审期末 = 期初 + 本期增加 − 本期减少", "计算",
             "余额变动未审期末（calcH62EndUnadjusted）/明细表H6-2", "useH6FormulaEngine"),
            ("审定期初", "审定期初 = 期初未审 + 期初调整", "计算",
             "余额变动审定期初（calcH62BeginAudited）/明细表H6-2", "useH6FormulaEngine"),
            ("期末账项调整", "期末账项调整 = 期初调整 + 账项增加 − 账项减少", "计算",
             "余额变动期末账项调整（calcH62EndAdjustment）/明细表H6-2", "useH6FormulaEngine"),
            ("审定期末", "审定期末 = 审定期初 + 审定增加 − 审定减少（审定增减=未审增减+账项增减）", "计算",
             "余额变动审定期末（calcH62EndAudited / applyH62BalanceFormulas）/明细表H6-2", "useH6Detail"),
            ("合计", "合计 = Σ各清理项目（原值/折旧/减值/净值/收入/费用/税费/净损益/余额各列）", "计算",
             "明细表合计行（calcSubtotal，subtotalRow）/明细表H6-2", "useH6Detail"),
            ("从H1处置带入", "自 H1 处置事件创建清理项目行（原值/累计折旧/减值/净值），本期增加=净值", "取数",
             "从 H1 处置创建明细行（createFromH1Disposal，跨底稿 H1）/明细表H6-2", "useH6Detail"),
            ("超1年挂账关注", "转入清理起始日至资产负债表日已超过1年 → 关注未结转进展并披露", "logic_check",
             "超1年挂账判定（isClearingOverOneYear / getDetailRowWarnings）/明细表H6-2", "useH6FormulaEngine"),
            ("未结转过渡余额风险", "状态非「已结转」→ 过渡科目1606仍有余额风险提示", "logic_check",
             "行级审计警告（getDetailRowWarnings）/明细表H6-2", "useH6Detail"),
        ],
        "H6-3": [
            ("科目1606账项净额", "账项调整净额 = Σ(借方 − 贷方)（类别=账项调整/其他，科目1606）", "计算",
             "H6-3 调整分录汇总账项净额（h63AdjustmentSync.clearingAjeNet，键 H6-3-rows）/调整分录H6-3", "useH6CrossSheet"),
            ("科目1606报表净额", "报表(重分类)调整净额 = Σ(借方 − 贷方)（类别=报表调整/RJE，科目1606）", "计算",
             "H6-3 调整分录汇总报表净额（h63AdjustmentSync.clearingRjeNet，键 H6-3-rows）/调整分录H6-3", "useH6CrossSheet"),
        ],
        "H6-4": [
            ("净值", "净值 = 原值 − 累计折旧 − 减值准备", "计算",
             "检查表行净值（recalcH6CheckRow / calcNetBookValue）/检查表H6-4", "useH6Check"),
            ("清理净损益", "清理净损益 = 清理收入 − 清理费用 − 净值", "计算",
             "检查表行清理净损益（recalcH6CheckRow / calcDisposalGainLoss）/检查表H6-4", "useH6Check"),
            ("检查比例", "检查比例 = 样本净值合计 ÷ H6-2本期减少净值合计 ×100%", "计算",
             "样本覆盖率（summary.coverageRate = netValueTotal ÷ totalPopulation）/检查表H6-4", "useH6Check"),
            ("合计", "合计 = Σ样本各列（原值/净值/费用/收入/净损益/转营业外/转处置收益/期末余额）", "计算",
             "检查表合计（summary，calcSubtotal）/检查表H6-4", "useH6Check"),
            ("检查比例总体带入", "检查比例分母（本期清理减少净值合计）自 H6-2 明细带入", "取数",
             "总体自 H6-2 带入（syncPopulationFromH62 / _calcLinkedPopulation，键 H6-2-rows）/检查表H6-4", "useH6Check"),
            ("从明细同步样本", "样本行自 H6-2 明细行增量同步（名称/原值/折旧/收入/费用/结转科目等）", "取数",
             "从明细同步样本（syncFromDetailRows）/检查表H6-4", "useH6Check"),
            ("结转分摊勾稽", "已结转样本：|转营业外| + |转处置收益| 应约等于 |清理净损益|（容差0.5）", "logic_check",
             "结转分摊勾稽（isTransferMismatch）/检查表H6-4", "useH6Check"),
            ("期末余额清零核对", "过渡科目1606样本期末余额应清零（统计期末非零笔数）", "logic_check",
             "期末余额清零核对（summary.nonZeroEndingCount）/检查表H6-4", "useH6Check"),
            ("与H10处置损益勾稽", "差额 = 检查表转处置收益合计 − H10处置损益取数（差额>0.5 提示核对）", "logic_check",
             "与 H10 勾稽（summary.h10GainLossDiff / _calcH10GainLoss，键 H10-2-rows 等）/检查表H6-4", "useH6Check"),
        ],
        "附注披露": [
            ("从H6-1/H6-2带入", "清理明细行、期末/上期余额、超1年项目自 H6-1/H6-2 带入", "取数",
             "本底稿取数（pullFromLocalSources / pullClearingFromH6Responses）/附注披露", "useH6Disclosure"),
            ("从H1带入固定资产", "跨底稿从 H1 带入固定资产期末/上期汇总金额", "取数",
             "从 H1 取固定资产汇总（pullFaFromH1 / extractFaFromH1Map，跨底稿 H1）/附注披露", "useH6Disclosure"),
            ("清理明细↔审定勾稽", "清理明细期末合计 应等于 H6-1 审定期末（差额>0 告警）", "logic_check",
             "清理明细 vs 审定勾稽（crossWarnings / clearingVsAdjudication）/附注披露", "useH6Disclosure"),
            ("过渡科目未清零披露", "1606期末未清零 → 附注需披露清理项目及超1年进展", "logic_check",
             "过渡科目零余额与超1年完整性（crossWarnings，autoFill.transitZero / overOneYearCount）/附注披露", "useH6Disclosure"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # H7 生产性生物资产（农/林/牧/渔 1621 借方 / 累计折旧 备抵；成本 + 公允双计量 + 互转）
    # ═══════════════════════════════════════════════════════════════════════
    "H7": {
        "H7-1": [
            ("审定表未审数（取数）", "从试算平衡表科目1621生产性生物资产 unadjusted_amount 带入审定表未审数（资产负债表科目取期末余额，非发生额）", "取数",
             "TB取数 loadTbData（account_codes=1621）", "useH7FormData"),
            ("审定数", "审定数 = 未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "各行审定金额（calcAuditedAmount）", "useH7FormulaEngine"),
            ("生产性生物资产原值期末余额（成本模式）", "原值期末余额 = 期初 + 借方发生 - 贷方发生（1621借方/资产类）", "计算",
             "calcAssetEndBalance", "useH7FormulaEngine / useH7AdjudicationCost"),
            ("累计折旧期末余额", "累计折旧期末余额 = 期初 + 贷方发生 - 借方发生（累计折旧贷方/备抵类）", "计算",
             "calcContraEndBalance", "useH7FormulaEngine / useH7AdjudicationCost"),
            ("净值", "净值 = 原值 - 累计折旧 - 减值准备", "计算",
             "calcNetValue", "useH7FormulaEngine"),
            ("公允价值模式期末余额", "公允模式期末余额 = 期初 + 增加 - 减少 + 公允价值变动（公允价值计量模式审定表）", "计算",
             "calcFairEndBalance", "useH7FormulaEngine / useH7AdjudicationFair"),
            ("公允价值差异率", "公允价值差异率(%) = (评估值 - 账面值) / 账面值 × 100（账面值为0时取0）", "计算",
             "calcFairValueDiffRate", "useH7FormulaEngine / useH7AdjudicationFair"),
            ("合计", "合计 = 各项金额之和（Σ）", "计算",
             "calcSubtotal", "useH7FormulaEngine"),
            ("变动率", "变动率(%) = (本期审定 - 上期) / 上期 × 100（上期为0时取0）", "计算",
             "calcChangeRate", "useH7FormulaEngine"),
            ("审定合计回写试算平衡表", "审定原值与累计折旧回写 TB 科目1621（audited_amount），并发布 EventBus 'substantive:adjudicated' 通知附注刷新", "取数",
             "writebackTB → substantive:adjudicated", "useH7FormData"),
            ("审定表原值合计↔明细表期末合计勾稽", "H7-1 审定表原值合计（H7-1-cost-total）应与 H7-2 明细表期末合计（H7-2-cost-total）一致，|差额|<0.01", "logic_check",
             "adjudicationVsDetail", "useH7CrossSheet"),
            ("累计折旧本期计提勾稽", "H7-11 折旧测算本期计提合计（H7-11-dep-total）应与 H7-1 审定表累计折旧本期贷方发生（H7-1-dep-credit）一致，|差额|<0.01", "logic_check",
             "depreciationVsAdjudication", "useH7CrossSheet"),
        ],
        "H7-2": [
            ("明细净值", "净值 = 原值 - 累计折旧 - 减值准备", "计算",
             "calcNetValue", "useH7DetailCost / useH7FormulaEngine"),
            ("明细合计", "合计 = 各明细行金额之和（Σ）", "计算",
             "calcSubtotal", "useH7DetailCost / useH7FormulaEngine"),
            ("公允模式明细期末余额", "公允模式期末余额 = 期初 + 增加 - 减少 + 公允价值变动（公允价值计量模式明细表）", "计算",
             "calcFairEndBalance", "useH7DetailFair / useH7FormulaEngine"),
            ("关联交易价差率", "价差率(%) = (交易价格 - 市场价格) / 市场价格 × 100（市场价格为0时取0）", "计算",
             "calcPriceDiffRate", "useH7FormulaEngine"),
        ],
        "H7-11": [
            ("年折旧额（成本模式直线法）", "年折旧额 = 原值 × (1 - 预计残值率) / 预计使用寿命(年)", "计算",
             "calcStraightLine", "useH7DepreciationEngine"),
            ("月折旧额", "月折旧额 = 年折旧额 / 12", "计算",
             "calcMonthlyDep", "useH7DepreciationEngine"),
            ("累计折旧", "累计折旧 = 月折旧额 × 已使用月数", "计算",
             "calcAccDep", "useH7DepreciationEngine"),
            ("减值后年折旧额", "减值后年折旧额 = 减值后净值 × (1 - 预计残值率) / 剩余使用寿命(年)", "计算",
             "calcDepAfterImpairment", "useH7DepreciationEngine"),
        ],
        "H7-14": [
            ("生产性→消耗性互转", "生产性生物资产转消耗性生物资产：按账面价值结转，转出金额 = 转入金额 = 账面价值", "计算",
             "calcProdToConsumable", "useH7TransferEngine"),
            ("生产性→公益性互转", "生产性生物资产转公益性生物资产：按账面价值结转，转出金额 = 转入金额 = 账面价值", "计算",
             "calcProdToPublic", "useH7TransferEngine"),
            ("互转差额校验", "互转差额 = 转出金额 - 转入金额（应为0，差额≠0时红色高亮提示异常）", "logic_check",
             "calcTransferDiff", "useH7TransferEngine"),
            ("互转转出↔转入合计勾稽", "H7-14 转出金额合计（H7-14-transfer-out-total）应与转入金额合计（H7-14-transfer-in-total）一致，|差额|<0.01", "logic_check",
             "transferDiffCheck", "useH7CrossSheet"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # H8 使用权资产（1901 / 累计折旧 1902 / 减值 1903；租赁 CAS21 识别/租赁期/初始计量/折旧）
    # ═══════════════════════════════════════════════════════════════════════
    "H8": {
        "H8-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "期初/期末审定金额（calcAuditedAmount）", "useH8Adjudication / useH8FormulaEngine"),
            ("使用权资产原值期末余额", "原值期初 + 借方发生额 − 贷方发生额（借方资产类1901）", "计算",
             "原值行期末（calcAssetEndBalance）", "useH8Adjudication / useH8FormulaEngine"),
            ("累计折旧期末余额", "折旧期初 + 贷方发生额 − 借方发生额（贷方备抵类1902）", "计算",
             "累计折旧行期末（calcContraEndBalance）", "useH8Adjudication / useH8FormulaEngine"),
            ("净额", "使用权资产原值 − 累计折旧 − 减值准备", "计算",
             "四、净额行（calcNetValue / netAudited）", "useH8Adjudication / useH8FormulaEngine"),
            ("变动额", "期末审定数 − 期初审定数", "计算",
             "变动额列（changeAmount）", "useH8Adjudication"),
            ("变动率", "变动额 ÷ |期初审定数| × 100%（≥30%须说明）", "计算",
             "变动率列（calcChangeRate）", "useH8Adjudication / useH8FormulaEngine"),
            ("合计", "各资产分类金额求和", "计算",
             "原值/折旧/减值合计行（calcSubtotal / _sumBlock）", "useH8Adjudication / useH8FormulaEngine"),
            ("从明细表带入未审数", "按资产类别汇总 H8-2 明细期初/期末原值、累计折旧、减值", "取数",
             "从 H8-2 明细带入（fillFromH82Detail / aggregateH82ByCategory）", "useH8Adjudication"),
            ("账项调整回写", "读取 H8-3 调整分录 1901/1902 账项净额(借−贷)分摊至期末账项调整列", "取数",
             "从 H8-3 回写期末账项调整（syncEndAdjFromH83 / h83AdjustmentSync）", "useH8Adjudication / useH8CrossSheet"),
            ("试算平衡表核对", "审定期末(1901使用权资产/1902累计折旧/1903减值准备) 与试算平衡表数核对，差额应为0", "logic_check",
             "TB 核对行（tbDiffRows）", "useH8Adjudication"),
            ("审定数回写试算平衡表", "使用权资产原值(1901)、累计折旧(1902)、减值准备(1903)审定数回写 TB", "logic_check",
             "TB 回写（onWritebackTB / writebackTrialBalance）", "useH8Adjudication"),
            ("审定合计与明细表核对", "H8-1 原值审定合计 与 H8-2 明细入账值合计 应一致", "logic_check",
             "H8-1↔H8-2 勾稽（adjudicationVsDetail）", "useH8CrossSheet"),
        ],
        "H8-2": [
            ("使用权资产初始计量(入账值)", "租赁负债初始确认(H9) + 初始直接费用 − 租赁激励（CAS21第16条）", "计算",
             "入账值列（calcInitialMeasurement / initialAmount）", "useH8Detail / useH8CAS21Engine"),
            ("原值期末未审", "原值期初 + (本期租入+重估调整+其他增) − (转租融资+转让待售+其他减)", "计算",
             "原值期末（recalcH8DetailRow / calcAssetEndBalance）", "useH8Detail / useH8FormulaEngine"),
            ("原值审定", "期初审定=期初未审+期初调整；期末审定=期初审定+审定增−审定减", "计算",
             "原值审定列（recalcH8DetailRow）", "useH8Detail"),
            ("累计折旧期末", "折旧期初 + (本期计提+其他增) − (转租融资+转让待售+其他减)（备抵）", "计算",
             "累计折旧期末（calcContraEndBalance）", "useH8Detail / useH8FormulaEngine"),
            ("减值准备期末", "减值期初 + 计提 − 处置转出（备抵，CAS8不得转回）", "计算",
             "减值期末（calcContraEndBalance）", "useH8Detail / useH8FormulaEngine"),
            ("期末净值", "原值 − 累计折旧 − 减值准备", "计算",
             "净值列（calcNetValue）", "useH8Detail / useH8FormulaEngine"),
            ("明细合计", "各明细行金额求和", "计算",
             "合计行（calcSubtotal / subtotalRow）", "useH8Detail / useH8FormulaEngine"),
            ("从折旧测算表回填本期计提", "按合同号从 H8-8 回填本期计提折旧额", "取数",
             "从 H8-8 回填（pullDepFromH88）", "useH8Detail"),
            ("与审定表期末勾稽", "H8-2 明细审定期末(原值/折旧/减值/净额) 与 H8-1 审定合计核对", "logic_check",
             "H8-2↔H8-1 勾稽（crossValidation）", "useH8Detail"),
        ],
        "H8-3": [
            ("使用权资产账项调整净额", "H8-3 分录中 1901 借方合计 − 贷方合计（账项调整AJE）", "计算",
             "1901账项净额（h83AdjustmentSync.rouCostAjeNet）", "useH8CrossSheet"),
            ("累计折旧账项调整净额", "H8-3 分录中 1902 借方合计 − 贷方合计（账项调整AJE）", "计算",
             "1902账项净额（h83AdjustmentSync.rouDepAjeNet）", "useH8CrossSheet"),
            ("重分类调整净额", "H8-3 报表调整类(RJE) 1901/1902 借贷净额", "计算",
             "1901/1902重分类净额（h83AdjustmentSync.rouCostRjeNet/rouDepRjeNet）", "useH8CrossSheet"),
            ("调整分录汇总回写审定表", "按 1901/1902 科目净额同步至 H8-1 期末账项/报表调整列", "logic_check",
             "H8-3→H8-1 联动（h83AdjustmentSync）", "useH8CrossSheet"),
        ],
        "H8-4": [
            ("已识别资产判定", "物理可区分=是 ∧ 供应方实质性替换权=否 → 已识别资产=是（F11）", "logic_check",
             "已识别资产（calcIdentifiedAsset）", "useH8LeaseIdentification"),
            ("主导使用权判定", "有权主导使用目的方式=是；或(使用预先确定=是 ∧ (有权运营=是 或 客户设计=是))", "logic_check",
             "主导使用权（calcDirectUseRight / resolveDirectUse）", "useH8LeaseIdentification"),
            ("租赁识别结论", "已识别资产=是 ∧ 主导使用权=是 ∧ 几乎全部经济利益=是 → 合同为租赁或包含租赁（C21）", "logic_check",
             "租赁识别结论（calcLeaseIdentificationConclusion）", "useH8LeaseIdentification"),
            ("租赁分拆结论", "可单独获利=是 ∧ 与其他资产非高度依赖=是 → 构成单独租赁（C27）", "logic_check",
             "分拆结论（calcSplitConclusion）", "useH8LeaseIdentification"),
            ("租赁合并结论", "一揽子商业目的/对价相互依赖/合起来构成单独租赁 任一为是 → 合并为一份合同（C36）", "logic_check",
             "合并结论（calcCombineConclusion）", "useH8LeaseIdentification"),
            ("短期租赁判定", "考虑续租后≤12月 ∧ 续签后≤12月(F41) ∧ 不含购买选择权 → 属于短期租赁（C45，CAS21第32条）", "logic_check",
             "短期租赁（calcTermWithin12 / calcShortTermConclusion）", "useH8LeaseIdentification"),
            ("低价值资产租赁判定", "全新价值较低(如≤4万) ∧ 未/不预期转租 → 属于低价值资产租赁（C54，CAS21第32条）", "logic_check",
             "低价值判定（calcLowValueConclusion / LOW_VALUE_THRESHOLD）", "useH8LeaseIdentification"),
        ],
        "H8-5": [
            ("租赁期确定", "不可撤销期间 + 续租选择权期间(合理确定行使) + 终止选择权期间(合理确定不行使)（CAS21第14-17条）", "计算",
             "确定的租赁期月数（calcLeaseTermMonths）", "useH8LeaseTerm"),
            ("有效租赁期", "重新确定租赁期 优先于 确定租赁期 优先于 公式推算值", "计算",
             "有效租赁期（resolveEffectiveLeaseTermMonths）", "useH8LeaseTerm"),
            ("重新评估结论", "重大改良/重大定制化/相关经营决策 任一为是 → 应当重新评估租赁期(C29)", "logic_check",
             "重新评估结论（calcReassessmentConclusion）", "useH8LeaseTerm"),
            ("租赁期回写计量/折旧", "有效租赁期回写 H8-6 计量参数、H8-8 折旧行、H8-13 简化处理行", "取数",
             "推送租赁期（pushLeaseTermToH86 / pushLeaseTermToH88 / pushShortTermToH813）", "useH8LeaseTerm"),
        ],
        "H8-6": [
            ("使用权资产初始计量", "租赁负债初始确认(H9) + 初始直接费用 − 租赁激励（CAS21第16条）", "计算",
             "初始计量（calcInitialMeasurement / initialMeasurement）", "useH8Measurement / useH8CAS21Engine"),
            ("租赁负债摊销表", "实际利率法：期初余额×折现率=利息，期末余额=期初+利息−付款额", "计算",
             "摊销表（buildH86AmortSchedule / generateSchedule）", "useH8Measurement"),
            ("折现率与期数换算", "按年计量：年利率、期数=ceil(月/12)、年付款=月租金×12；按月计量：月利率=年利率/12、期数=月数", "计算",
             "计量参数换算（buildH86AmortSchedule）", "useH8Measurement"),
            ("从租赁期确定表带入租赁期", "读取 H8-5 有效租赁期填入 H8-6 计量参数", "取数",
             "从 H8-5 带入（pullLeaseTermFromH85）", "useH8Measurement"),
        ],
        "H8-7": [
            ("变更类型判定", "扩大范围∧对价相当单独价格→单独租赁；减少范围→范围减少；否则→其他变更（CAS21第28-30条）", "logic_check",
             "变更类型（deriveModificationType / isSeparateLease）", "useH8CAS21Engine"),
            ("变更后租赁付款额现值", "Σ(每期付款额 × 折现系数)；折现系数=1/(1+r)^n", "计算",
             "付款额现值（calcLeasePaymentsPV / calcAnnuityPV / calcDiscountFactor）", "useH8CAS21Engine"),
            ("租赁负债调整额", "变更后付款额现值 − 变更日账面租赁负债（CAS21第29条）", "计算",
             "负债调整额（calcLiabilityAdjustment）", "useH8CAS21Engine"),
            ("范围减少终止损益", "终止部分租赁负债 − 终止部分使用权资产净值（按减少比例分摊）", "计算",
             "范围减少（calcScopeReduction / calcTerminationGainLoss）", "useH8CAS21Engine"),
            ("使用权资产重新计量", "旧使用权资产 + 调整额（CAS21第28条）", "计算",
             "重新计量（calcRemeasurement）", "useH8CAS21Engine"),
        ],
        "H8-8": [
            ("折旧期确定", "min(租赁期月数, 使用寿命月数)；合理确定取得所有权时取使用寿命（CAS21第21条）", "计算",
             "折旧期（calcDepreciationPeriod / resolveH8DepPeriodMonths）", "useH8Depreciation / useH8CAS21Engine"),
            ("月折旧额(直线法)", "(原值 − 预计净残值) ÷ 折旧期", "计算",
             "月折旧（calcStraightLine / calcStraightLineTest）", "useH8Depreciation / useH8DepreciationEngine"),
            ("本期折旧与累计折旧", "本期折旧=月折旧×本期计提月数；累计折旧按起止日期分段计算", "计算",
             "折旧测算(不含减值)（calcStraightLineTest）", "useH8Depreciation / useH8DepreciationEngine"),
            ("含减值分段折旧", "减值日前按原月折旧、减值日后按(账面−残值)÷剩余折旧期重算", "计算",
             "折旧测算(含减值)（calcWithImpairmentTest）", "useH8Depreciation / useH8DepreciationEngine"),
            ("本期折旧合计", "各资产本期测算折旧额求和", "计算",
             "折旧合计（depTotal / calcSubtotal）", "useH8Depreciation / useH8FormulaEngine"),
            ("从明细表带入折旧基础", "按合同号从 H8-2 带入原值、账面累计折旧、开始使用日期、租赁期", "取数",
             "从 H8-2 带入（importFromH82）", "useH8Depreciation"),
            ("从租赁期确定表同步租赁期", "按合同号从 H8-5 同步有效租赁期并重算折旧", "取数",
             "从 H8-5 同步（syncLeaseTermFromH85）", "useH8Depreciation"),
            ("折旧合计与审定表核对", "H8-8 本期折旧合计 与 H8-1 累计折旧本期计提(贷方发生额) 核对", "logic_check",
             "折旧勾稽（h81DepReconcile / depreciationVsAdjudication）", "useH8Depreciation / useH8CrossSheet"),
        ],
        "H8-9": [
            ("折旧费用分配合计", "各费用项目(生产成本/制造费用/销售费用/管理费用/研发费用/其他)分配额求和", "计算",
             "分配合计（allocationTotal）", "useH8CrossSheet"),
            ("分配合计与折旧合计核对", "H8-9 费用分配合计 应等于 H8-8 本期折旧合计(累计折旧贷方→费用借方闭环)", "logic_check",
             "分配勾稽（allocationVsDepreciation）", "useH8CrossSheet"),
        ],
        "H8-10": [
            ("减值测算账面价值②", "使用权资产原值 − 累计折旧(不含减值准备)", "计算",
             "账面价值②（calcImpairmentBookValue）", "useH8Impairment / useH8FormulaEngine"),
            ("可收回金额⑤", "有减值迹象时 max(公允价值减处置费用③, 预计未来现金流量现值④)；无迹象为0（CAS8）", "计算",
             "可收回金额⑤（calcImpairmentRecoverableAmount）", "useH8Impairment / useH8FormulaEngine"),
            ("期末应计提减值⑥", "max(账面价值② − 可收回金额⑤, 0)；无迹象为0", "计算",
             "应计提减值⑥（calcRequiredImpairment）", "useH8Impairment / useH8FormulaEngine"),
            ("本期应补提减值⑧", "max(应计提⑥ − 已计提⑦, 0)（CAS8减值一经确认不得转回）", "计算",
             "本期补提⑧（calcImpairmentSupplement）", "useH8Impairment / useH8FormulaEngine"),
            ("多提待查⑨", "max(已计提⑦ − 应计提⑥, 0)（仅提示调查，不得转回）", "计算",
             "多提待查⑨（calcImpairmentOverProvision）", "useH8Impairment / useH8FormulaEngine"),
            ("从明细表带入账面价值②", "从 H8-2 明细(入账值−累计折旧期末)带入减值测算账面价值", "取数",
             "从 H8-2 带入（seedRowsFromH82 / importFromH82）", "useH8Impairment"),
            ("从折旧测算表带入已计提⑦", "按合同号/资产名称从 H8-8(含减值)带入已计提减值额", "取数",
             "从 H8-8 带入⑦（mapAlreadyProvidedFromH88 / pullAlreadyProvidedFromH88）", "useH8Impairment"),
            ("从可收回金额表回填③④⑤", "从 H8-11 各资产组回填公允净额③、DCF现值④、可收回金额⑤", "取数",
             "从 H8-11 回填（applyH811GroupsToRows / pullRecoverableFromH811）", "useH8Impairment"),
            ("本期补提与资产减值损失核对", "H8-10 本期补提⑧ 与 K11 资产减值损失(使用权资产行)核对", "logic_check",
             "H8-10↔K11 勾稽（reconcileWithK11 / extractK11RouAmount）", "useH8Impairment"),
            ("减值迹象与索引完整性检查", "有减值迹象行须填迹象说明且索引号含 H8-11，否则告警", "logic_check",
             "编制完整性校验（validateH8ImpairmentPrep）", "useH8Impairment"),
        ],
        "H8-11": [
            ("公允价值减处置费用", "公允价值(销售协议价/活跃市场价/估计价) − 处置费用合计", "计算",
             "公允净额（resolveH8FairValue / calcH8DisposalTotal）", "useH8Recoverable"),
            ("权益资本成本(CAPM)", "无风险利率 + β×(市场收益率 − 无风险利率)", "计算",
             "权益成本（calcCostOfEquity）", "useH8Recoverable"),
            ("税后加权平均资本成本", "(权益/(债务+权益))×Ke + (债务/(债务+权益))×Kd×(1−税率)", "计算",
             "税后WACC（calcWaccAfterTax）", "useH8Recoverable"),
            ("税前折现率", "由税后WACC按税率还原为税前折现率", "计算",
             "税前折现率（calcPreTaxDiscountRate）", "useH8Recoverable"),
            ("预计未来现金流量现值", "Σ(净现金流量 × 折现系数) + 终值现值", "计算",
             "DCF现值（totalPV / pvTotal + tvPresent）", "useH8Recoverable"),
            ("可收回金额", "max(公允价值减处置费用, 预计未来现金流量现值)", "计算",
             "可收回金额（calcRecoverableAmount / recoverableAmount）", "useH8Recoverable"),
            ("可收回金额回写减值测算", "将各资产组公允净额③、DCF现值④、可收回金额⑤回写 H8-10", "取数",
             "回写 H8-10（applyRecoverableWriteback / upsertH810RowFromRecoverable）", "useH8Recoverable / useH8Impairment"),
            ("与减值测算表核对", "H8-11 可收回金额 与 H8-10 各行可收回金额⑤核对", "logic_check",
             "H8-11↔H8-10 同步核对（syncChecks / classifyH810SyncStatus）", "useH8Recoverable"),
        ],
        "H8-12": [
            ("终止(减少)损益", "终止时点租赁负债余额 − 使用权资产净值（结果>0为收益，<0为损失）", "计算",
             "终止损益（calcTerminationGainLoss）", "useH8CAS21Engine"),
        ],
        "H8-13": [
            ("短期/低价值租赁费用", "短期租赁及低价值资产租赁付款额按直线法计入相关成本或损益（CAS21第32条）", "计算",
             "简化处理费用登记（H8-13-rows）", "useH8LeaseTerm / useH8LeaseIdentification"),
            ("从租赁期确定表带入短期候选", "从 H8-5 短期租赁候选(有效租赁期≤12月且无购买选择权)带入检查行", "取数",
             "从 H8-5 带入（pushShortTermToH813 / upsertH85ShortTermIntoH813Rows）", "useH8LeaseTerm"),
        ],
        "附注上市": [
            ("使用权资产变动表取数", "从 H8-1 审定/H8-2 明细/H8-10 减值/H8-13 简化按类别带入原值、累计折旧、减值变动", "取数",
             "附注取数（pullFromSources / disclosureAutoFill）", "useH8Disclosure / useH8CrossSheet"),
            ("减值披露按类别汇总", "H8-10 已计提⑦→期初、本期补提⑧→本期计提，按披露类别汇总", "取数",
             "减值披露聚合（aggregateH810ImpairmentByCategory）", "useH8Disclosure"),
            ("账面价值", "使用权资产原值 − 累计折旧 − 减值准备", "计算",
             "净值披露（disclosureAutoFill.disc_net_value）", "useH8Disclosure / useH8CrossSheet"),
        ],
        "附注国企": [
            ("使用权资产分层变动表取数", "从 H8-1 审定/H8-2 明细/H8-10 减值按原值、累计折旧、减值三层期初/增/减/期末带入", "取数",
             "附注取数（pullFromSources）", "useH8Disclosure"),
            ("期末余额(备抵分层)", "各层期末 = 期初 + 增加 − 减少（减值层由 H8-10 权威覆盖）", "计算",
             "分层期末（recomputeDerivedLayers）", "useH8Disclosure / h8SoeDisclosureModel"),
        ],
        "H8↔H9联动": [
            ("使用权资产与租赁负债初始确认联动", "使用权资产初始计量 = 租赁负债初始确认(H9) + 初始直接费用 − 租赁激励（±1元容差，CAS21核心）", "logic_check",
             "H8↔H9 联动校验（h8VsH9Linkage / calcInitialMeasurement）", "useH8CrossSheet / useH8CAS21Engine"),
            ("按合同号 H8↔H9 初始计量差额", "逐合同：H8 入账值 − (H9 初始负债 + 直接费用 − 激励)，差额>1元列示", "logic_check",
             "合同级差额（buildH8H9ContractVariance / h8H9ContractVariance）", "useH8CrossSheet"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # H9 租赁负债（2205 贷方 / 未确认融资费用 1802 备抵；实际利率法摊销 + 现值）
    # ═══════════════════════════════════════════════════════════════════════
    "H9": {
        "H9-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "calcAuditedAmount（审定数 D=B+C / I=G+H）", "useH9Adjudication"),
            ("租赁负债期末余额", "期初余额 + 贷方发生额(增加) − 借方发生额(减少)（负债贷方科目2205）", "计算",
             "calcLiabilityEndBalance（审定期末 L=I−J+K）", "useH9Adjudication"),
            ("未确认融资费用期末余额", "期初余额 + 借方发生额(增加) − 贷方发生额(摊销确认减少)（负债备抵借方科目1802）", "计算",
             "calcContraLiabilityEndBalance（审定期末 M=J+K−L）", "useH9Adjudication"),
            ("租赁负债净额", "租赁负债原值审定合计 − 未确认融资费用审定合计（附注披露金额）", "计算",
             "calcNetLiability / netAudited（row18=row8−row13）", "useH9Adjudication"),
            ("报表数", "审定数 − 减一年内到期重分类", "计算",
             "calcFsAmount（F=D−E / K=I−J）", "useH9Adjudication"),
            ("变动额", "本期期末报表数 − 期初报表数", "计算",
             "calcChangeAmount（L=K−F）", "useH9Adjudication"),
            ("变动率", "变动额 ÷ 期初报表数（期初为0特殊处理，>30%高亮）", "计算",
             "calcChangeRate（M列）", "useH9Adjudication"),
            ("区块小计", "各区块(租赁负债原值/未确认融资费用)各列求和", "计算",
             "calcSubtotal / liabilitySubtotal / unearnedSubtotal", "useH9Adjudication"),
            ("从明细带入", "从 H9-2 租赁负债明细、H9-3 未确认融资费用明细汇总带入期初/发生额/未审/重分类", "取数",
             "fillFromDetail（H9-1←H9-2/H9-3）", "useH9Adjudication"),
            ("从调整分录回写AJE/RJE", "读 H9-4 调整分录：租赁负债(2205)按贷方−借方、未确认融资费用(1802)按借方−贷方，按 AJE/RJE 分类回写审定表", "取数",
             "syncAjeRjeFromAdjustment（H9-4-rows）", "useH9Adjudication"),
            ("TB回写", "审定合计回写试算平衡表：租赁负债(2205) + 未确认融资费用(1802)", "logic_check",
             "publishAdjudicated / onWritebackTB（发布 substantive:adjudicated）", "useH9Adjudication"),
            ("审定表↔明细表勾稽", "H9-1 审定合计 − H9-2 明细审定合计，|差额|≤1元 视为一致", "logic_check",
             "adjudicationVsDetail", "useH9CrossSheet"),
            ("H9↔H8联动核对(CAS21)", "H9 租赁负债初始确认 ≈ H8 使用权资产初始计量 − 初始直接费用 + 租赁激励，|差额|≤1元", "logic_check",
             "h9VsH8Linkage", "useH9CrossSheet"),
            ("摊销表利息↔审定表本期利息勾稽", "摊销表本期利息合计 − H9-1 审定表本期利息费用，|差额|≤1元", "logic_check",
             "amortizationVsAdjudication（H9-amort-current-interest）", "useH9CrossSheet"),
        ],
        "H9-2": [
            ("期末余额", "期初余额 − 本期偿还(借方减少) + 本期利息(贷方增加)（负债贷方 E=B−C+D）", "计算",
             "calcLiabilityEndBalance", "useH9Detail"),
            ("审定期初", "期初余额 + 期初AJE（I=B+F）", "计算",
             "useH9Detail（_normalizeRow）", "useH9Detail"),
            ("审定偿还", "本期偿还 + 偿还AJE（J=C+G）", "计算",
             "useH9Detail（_normalizeRow）", "useH9Detail"),
            ("审定利息", "本期利息 + 利息AJE（K=D+H）", "计算",
             "useH9Detail（_normalizeRow）", "useH9Detail"),
            ("审定期末", "审定期初 − 审定偿还 + 审定利息（L=I−J+K）", "计算",
             "calcLiabilityEndBalance", "useH9Detail"),
            ("最终审定", "审定期末 − 重分类（N=L−M）", "计算",
             "useH9Detail（_normalizeRow）", "useH9Detail"),
            ("合计", "各明细行各列求和", "计算",
             "totalRow / calcSubtotal", "useH9Detail"),
            ("初始确认合计", "Σ 各合同审定期初（供 H8 使用权资产联动核对取数）", "取数",
             "_persist（H9-1-initial-liability / H9-initial-recognition）", "useH9Detail"),
            ("到期日分析四档合计", "1年以内 + 1–2年 + 2–3年 + 3年以上，应等于最终审定（±1元容差）", "logic_check",
             "calcMaturityBucketsSum", "useH9FormulaEngine"),
            ("H8-12终止结清", "按合同号匹配 H8-12 终止事件，标记终止并结清审定期末负债归零", "logic_check",
             "applyH8TerminationToH92Rows / markTerminatedFromH8", "useH9Detail"),
        ],
        "H9-3": [
            ("期末余额", "期初余额 + 本期增加(借方) − 本期确认(贷方转利息费用)（借方备抵 E=B+C−D）", "计算",
             "calcContraLiabilityEndBalance", "useH9FinanceCost"),
            ("审定期初", "期初余额（无调整，J=B）", "计算",
             "useH9FinanceCost（_normalizeRow）", "useH9FinanceCost"),
            ("审定增加", "本期增加 + 期初AJE + 增加AJE（K=C+F+H）", "计算",
             "useH9FinanceCost（_normalizeRow）", "useH9FinanceCost"),
            ("审定确认", "本期确认 + 确认AJE + 其他AJE（L=D+G+I）", "计算",
             "useH9FinanceCost（_normalizeRow）", "useH9FinanceCost"),
            ("审定期末", "审定期初 + 审定增加 − 审定确认（M=J+K−L）", "计算",
             "calcContraLiabilityEndBalance", "useH9FinanceCost"),
            ("最终审定", "审定期末 − 重分类（O=M−N）", "计算",
             "useH9FinanceCost（_normalizeRow）", "useH9FinanceCost"),
            ("合计", "各明细行各列求和", "计算",
             "totalRow / calcSubtotal", "useH9FinanceCost"),
            ("从H9-2同步出租方", "按合同号/出租方从 H9-2 明细同步行骨架（出租方、合同号、关联方标识）", "取数",
             "syncLessorsFromH92", "useH9FinanceCost"),
        ],
        "H9摊销表": [
            ("本期利息", "期初余额 × 实际利率(增量借款利率，CAS21实际利率法)", "计算",
             "calcInterest（CAS21 §18）", "useH9AmortizationEngine"),
            ("本金偿还", "每期租金付款额 − 利息费用", "计算",
             "calcPrincipal（CAS21 §19）", "useH9AmortizationEngine"),
            ("期末余额", "期初余额 − 本金偿还（等价 期初 + 利息 − 付款）", "计算",
             "calcEndBalance / generateSchedule", "useH9AmortizationEngine"),
            ("增量借款利率(IBR)", "市场基准利率 + 信用利差 + 期限调整（CAS21 §15）", "计算",
             "calcIBR", "useH9PVEngine"),
            ("租赁负债现值", "Σ(各期付款额ᵢ ÷ (1+折现率)^ᵢ)（CAS21 §14 最低租赁付款额按增量借款利率折现）", "计算",
             "calcPresentValue", "useH9PVEngine"),
            ("等额年金现值", "每期付款 × (1 − (1+折现率)^−期数) ÷ 折现率", "计算",
             "calcAnnuityPV", "useH9PVEngine"),
            ("利息合计", "全期利息合计 = Σ各期利息；本期利息 = 前min(12,期数)期利息之和(年报口径)", "计算",
             "validation / calcSubtotal", "useH9Amortization"),
            ("从合同带入摊销参数", "从 H9-2 选定合同带入初始余额、增量借款利率(IBR归一)、租赁期、每期付款", "取数",
             "useH9Amortization.load / normalizeIbrRate", "useH9Amortization"),
            ("摊销表尾差校验", "最后一期期末余额应≈0（|尾差|<1元视为有效）", "logic_check",
             "validateSchedule", "useH9AmortizationEngine"),
        ],
        "H9-6": [
            ("关联租赁价差率", "价差率(%) = (实际租金 − 市场租金) ÷ 市场租金 × 100（评估关联方租赁定价公允性）", "计算",
             "calcPriceDiffRate", "useH9FormulaEngine"),
        ],
        "附注上市": [
            ("从审定表/明细带入", "从 H9-1 审定表(按类目)、H9-2 明细带入分类金额、一年内到期、本期利息", "取数",
             "pullFromSources", "useH9ListedDisclosure"),
            ("一年内到期金额", "H9-2 本期重分类合计（无则取 H9-1 RJE合计）", "取数",
             "_sumReclass / _blockTotals.rje", "useH9ListedDisclosure"),
            ("本期利息费用", "Σ H9-2 各合同审定利息(审定利息优先，否则 本期利息+利息AJE)", "取数",
             "_sumInterest", "useH9ListedDisclosure"),
        ],
        "附注国企": [
            ("从审定表/明细带入", "从 H9-1 带入租赁负债原值、未确认融资费用(期末/期初)，从 H9-2 带入一年内到期重分类", "取数",
             "pullFromSources / _blockTotals", "useH9SoeDisclosure"),
        ],
    },
    # ═══════════════════════════════════════════════════════════════════════
    # H10 资产处置收益（6115 损益贷方，取发生额；处置损益计算 + 与 H1/H6/H8 处置联动）
    # ═══════════════════════════════════════════════════════════════════════
    "H10": {
        "H10-1": [
            ("审定数", "未审数 + 账项调整(AJE) + 重分类调整(RJE)", "计算",
             "损益类各处置分项本期/上期审定金额（calcAuditedAmount）", "useH10FormulaEngine/useH10Adjudication"),
            ("损益类净发生额", "贷方发生额 − 借方发生额（6115 贷方科目）", "计算",
             "资产处置收益发生额净额（calcIncomeStatementNet）", "useH10FormulaEngine"),
            ("变动额", "本期审定数 − 上期审定数", "计算",
             "本期审定较上期变动额（calcChangeAmount）", "useH10FormulaEngine/useH10Adjudication"),
            ("变动率", "(本期审定数 − 上期审定数) ÷ |上期审定数|，上期为0时不计算；|变动率|>20%高亮并要求填写原因分析", "计算",
             "变动率及阈值判断（calcChangeRate/isChangeRateExceeding，H10_CHANGE_RATE_THRESHOLD=0.2）", "useH10FormulaEngine/useH10Adjudication"),
            ("审定合计", "各处置分项本期审定数之和（合计行）", "计算",
             "审定表合计聚合（calcSubtotal/totalRow）", "useH10FormulaEngine/useH10Adjudication"),
            ("从H10-2明细带入未审数", "按来源底稿(H1固定资产/H2在建工程/H5油气/H6清理/H7生物资产/H8使用权/I1无形资产/债务重组DR/非货币交换NM)汇总H10-2处置损益 → 对应审定分项未审数（保留AJE/RJE）；试运行行取附注试运行明细净额", "取数",
             "审定表未审数从明细带入（fillFromDetail / applyH10DetailToAdjStore / aggregateH10DetailByAdjRowKey）", "useH10Adjudication/h10FillFromDetail"),
            ("试算平衡表取数", "按科目6115查询试算平衡表：贷方发生额 − 借方发生额", "取数",
             "6115 资产处置收益试算平衡表数（loadTrialBalanceFromApi）", "useH10Adjudication"),
            ("与试算平衡表核对", "审定合计 − 试算平衡表数(6115)，差异>0.01高亮", "logic_check",
             "审定合计与试算平衡表核对（variance/hasVarianceHighlight）", "useH10Adjudication"),
            ("与H10-2明细勾稽", "H10-1审定合计 − H10-2明细处置损益合计，差异>0.01告警", "logic_check",
             "审定表↔明细表勾稽（detailCrossValidation / adjudicationVsDetail）", "useH10Adjudication/useH10CrossSheet"),
            ("与H6固定资产清理勾稽", "H10-1固定资产处置审定数 − H6固定资产清理净损益，差异>0.01告警", "logic_check",
             "与H6处置联动核对（h10VsH6 / pullH6ClearingNetForH10）", "useH10CrossSheet"),
            ("与来源底稿处置勾稽", "按来源底稿(H1/H2/H5/H6/H7/H8/I1/DR/NM)分类：H10-2明细汇总 − H10-1对应审定分项，差异>0.01告警", "logic_check",
             "与H1/H6/H8等来源底稿处置勾稽（sourceWpMismatches / H10_SOURCE_WP_TO_ROW_KEY）", "useH10CrossSheet"),
            ("审定合计回写试算平衡表", "审定合计回写6115审定数并发布 substantive:adjudicated 跨底稿事件", "取数",
             "审定数回写TB及联动（publishAdjudicated/writebackTB）", "useH10Adjudication"),
        ],
        "H10-2": [
            ("净账面价值", "原值 − 累计折旧 − 减值准备", "计算",
             "处置资产净账面价值（calcNetBookValue）", "useH10DisposalCalcEngine/useH10Detail"),
            ("处置净损益", "处置收入 − 净账面价值 − 处置费用 − 相关税费", "计算",
             "单项资产处置损益（calcDisposalGainLoss）", "useH10DisposalCalcEngine/useH10Detail"),
            ("处置损益率", "处置损益 ÷ 原值 × 100，原值为0或非有限数时不计算", "计算",
             "处置损益率（calcGainLossRate）", "useH10DisposalCalcEngine"),
            ("明细合计", "各处置明细行处置收入合计、处置损益合计（含盈利/亏损笔数统计）", "计算",
             "明细统计汇总（statsSummary）", "useH10Detail"),
        ],
        "H10-3": [
            ("借贷平衡校验", "Σ借方调整金额 = Σ贷方调整金额（差异<0.01）", "logic_check",
             "调整分录借贷平衡（isDebitCreditBalanced）", "useH10FormulaEngine/useH10Adjustment"),
            ("调整分录回写审定表", "调整分录金额回写H10-1对应处置分项(默认fixed_asset_disposal)的账项调整(AJE)/重分类调整(RJE)", "计算",
             "H10-3调整分录联动H10-1审定（applyAdjustmentWriteback，H10_ADJ_WRITEBACK_ROW_KEY）", "useH10Adjustment/useH10Adjudication"),
        ],
        "H10-4": [
            ("抽查比例", "已挂凭证索引检查行数(或抽凭样本数) ÷ H10-2明细总体行数，低于20%告警", "计算",
             "检查表抽查比例及门槛（sampleRatio/sampleRatioLow，H10_CHECK_MIN_SAMPLE_RATIO=0.2）", "useH10Check"),
            ("合规率", "合规检查行数 ÷ 检查行总数", "计算",
             "检查表合规率（complianceRate）", "useH10Check"),
            ("不合规判断", "任一核对项(审批流程/评估依据/定价合理性/税务处理/会计期间/收入确认/费用归集/关联方)为不合规 → 该行不合规", "logic_check",
             "处置合规性检查判断（isNonCompliant/nonCompliantSummary）", "useH10Check"),
        ],
        "附注上市": [
            ("披露主表从H10-1带入", "披露主表各处置分项本期/上期金额取H10-1审定分项审定数（试运行销售损益行优先取试运行明细净额）", "取数",
             "上市披露从审定表带入（pullFromAdjudication）", "useH10Disclosure"),
            ("试运行销售净额", "试运行销售收入 − 试运行销售成本，回写披露主表「试运行销售损益」行（本期/上期）", "计算",
             "试运行收支净额并回写主表（trialNet/applyTrialNetToMain，企业会计准则解释第15号）", "useH10Disclosure"),
            ("变动额/变动率", "本期金额 − 上期金额；(本期 − 上期) ÷ |上期金额|", "计算",
             "披露表变动分析（calcChangeAmount/calcChangeRate）", "useH10Disclosure"),
            ("披露合计", "各披露分项本期/上期金额之和（合计始终按全量行）", "计算",
             "披露表合计行（calcSubtotal/displayRows）", "useH10Disclosure"),
            ("披露与审定勾稽", "披露主表本期合计 − H10-1审定数，四舍五入至0.01", "logic_check",
             "附注披露与审定表核对（reconcileDiff）", "useH10Disclosure"),
        ],
        "附注国企": [
            ("披露主表从H10-1带入", "披露主表各处置分项本期/上期金额取H10-1审定分项审定数；非经常性损益列默认取本期审定数", "取数",
             "国企披露从审定表带入（pullFromAdjudication）", "useH10Disclosure"),
            ("变动额/变动率", "本期金额 − 上期金额；(本期 − 上期) ÷ |上期金额|", "计算",
             "披露表变动分析（calcChangeAmount/calcChangeRate）", "useH10Disclosure"),
            ("披露合计", "各披露分项本期/上期/非经常性损益金额之和", "计算",
             "披露表合计行（calcSubtotal/displayRows）", "useH10Disclosure"),
            ("非经常性损益勾稽", "本期合计 − 非经常性损益合计，四舍五入至0.01", "logic_check",
             "国企非经常性损益差额（soeNonRecurringDiff）", "useH10Disclosure"),
            ("披露与审定勾稽", "披露主表本期合计 − H10-1审定数", "logic_check",
             "附注披露与审定表核对（reconcileDiff）", "useH10Disclosure"),
        ],
    },
}
