"""Property-Based Tests for 截止测试自动提取 — Backend (hypothesis)

Feature: cutoff-test-auto-sampling

Properties tested:
- P3: 查询安全隔离不变量
- P4: 查询过滤条件构建正确性
- P5: 统计摘要准确性
- P6: 截断阈值行为
- P7: 金额 Decimal 序列化 Round-Trip
- P9: 排除已提取凭证去重

Uses hypothesis with max_examples=100.
"""
from __future__ import annotations

import uuid
from datetime import date, timedelta
from decimal import Decimal
from typing import Any
from unittest.mock import AsyncMock, patch

import pytest
import sqlalchemy as sa
from hypothesis import given, settings
from hypothesis import strategies as st

from app.services.ledger_sampling_service import (
    LedgerQueryFilters,
    LedgerSamplingService,
    StatsResult,
)


# ═══════════════════════════════════════════════════════════════════════════════
# Custom Strategies
# ═══════════════════════════════════════════════════════════════════════════════

# Strategy for account codes (1-6 digit prefixes)
st_account_codes = st.lists(
    st.text(
        alphabet="0123456789",
        min_size=1,
        max_size=6,
    ),
    min_size=1,
    max_size=5,
)

# Strategy for direction_filter
st_direction = st.sampled_from(["debit", "credit", "all"])

# Strategy for amount threshold
st_threshold = st.decimals(
    min_value=Decimal("0"),
    max_value=Decimal("999999999.99"),
    places=2,
    allow_nan=False,
    allow_infinity=False,
)

# Strategy for summary keyword
# 关键词取真实搜索字符集：断言 #4 校验关键词逐字出现在 literal_binds 渲染的 SQL 中，
# 而反斜杠会被 PostgreSQL 字面量渲染转义为双反斜杠、单引号会被转义为两个单引号，
# 使「逐字子串」判定对这两类字符不成立（属断言前提而非产品缺陷）。故排除 \ 与 '。
# 说明：`summary.ilike('%<kw>%')` 未转义 LIKE 元字符(%/_/\)是独立的既有产品加固项。
st_keyword = st.one_of(
    st.just(""),
    st.text(
        alphabet="abcdeABCDE01234 -采购付款销售转账费用工程往来",
        min_size=1,
        max_size=10,
    ),
)

# Strategy for voucher type filter
st_voucher_types = st.lists(
    st.sampled_from(["记", "收", "付", "转"]),
    min_size=0,
    max_size=4,
    unique=True,
)

# Strategy for exclude voucher nos
st_exclude_nos = st.lists(
    st.text(min_size=1, max_size=20, alphabet="0123456789-"),
    min_size=0,
    max_size=10,
)


@st.composite
def st_ledger_query_filters(draw):
    """Composite strategy for LedgerQueryFilters."""
    base_date = draw(st.dates(min_value=date(2020, 1, 1), max_value=date(2030, 12, 31)))
    days_range = draw(st.integers(min_value=1, max_value=60))
    end_date = base_date + timedelta(days=days_range)

    return LedgerQueryFilters(
        date_start=base_date,
        date_end=end_date,
        account_codes=draw(st_account_codes),
        amount_threshold=draw(st_threshold),
        direction_filter=draw(st_direction),
        voucher_type_filter=draw(st_voucher_types),
        summary_keyword=draw(st_keyword),
        exclude_voucher_nos=draw(st_exclude_nos),
    )


# ═══════════════════════════════════════════════════════════════════════════════
# Property 3: 查询安全隔离不变量
# Feature: cutoff-test-auto-sampling, Property 3: 查询安全隔离不变量
# ═══════════════════════════════════════════════════════════════════════════════


class TestProperty3QuerySecurityIsolation:
    """**Validates: Requirements 2.2, 2.3, 10.3**

    For any project_id and year, the SQL query generated by build_ledger_query
    SHALL always contain project_id and year conditions regardless of optional filters.
    """

    @pytest.mark.asyncio
    @settings(max_examples=100)
    @given(
        project_id=st.uuids(),
        year=st.integers(min_value=2020, max_value=2030),
        filters=st_ledger_query_filters(),
    )
    async def test_query_always_contains_project_id_and_year(
        self, project_id: uuid.UUID, year: int, filters: LedgerQueryFilters
    ):
        """**Validates: Requirements 2.2, 2.3, 10.3**

        The SQL generated by build_ledger_query always contains project_id and year
        conditions regardless of optional filter parameters.
        """
        # Mock db session and get_active_filter
        mock_db = AsyncMock()

        # Mock get_active_filter to return a basic filter that includes
        # project_id + year + is_deleted conditions (simulating the real behavior)
        from app.models.audit_platform_models import TbLedger

        mock_filter = sa.and_(
            TbLedger.project_id == project_id,
            TbLedger.year == year,
            TbLedger.is_deleted == sa.false(),
        )

        with patch(
            "app.services.ledger_sampling_service.get_active_filter",
            new=AsyncMock(return_value=mock_filter),
        ):
            query = await LedgerSamplingService.build_ledger_query(
                db=mock_db,
                project_id=project_id,
                year=year,
                filters=filters,
            )

        # Compile query to SQL string for inspection
        compiled = query.compile(
            compile_kwargs={"literal_binds": True},
            dialect=sa.dialects.postgresql.dialect(),
        )
        sql_str = str(compiled)

        # Assert project_id condition is present
        assert "project_id" in sql_str, (
            f"SQL must contain project_id condition. Got: {sql_str}"
        )

        # Assert year condition is present
        assert "year" in sql_str, (
            f"SQL must contain year condition. Got: {sql_str}"
        )

        # Assert is_deleted condition is present (from get_active_filter)
        assert "is_deleted" in sql_str, (
            f"SQL must contain is_deleted condition. Got: {sql_str}"
        )


# ═══════════════════════════════════════════════════════════════════════════════
# Property 4: 查询过滤条件构建正确性
# Feature: cutoff-test-auto-sampling, Property 4: 查询过滤条件构建正确性
# ═══════════════════════════════════════════════════════════════════════════════


class TestProperty4QueryFilterConstruction:
    """**Validates: Requirements 1.4, 2.4, 2.6, 2.7, 2.8**

    Each filter field correctly maps to SQL clause presence/absence.
    """

    @pytest.mark.asyncio
    @settings(max_examples=100)
    @given(filters=st_ledger_query_filters())
    async def test_filter_fields_map_to_sql_clauses(
        self, filters: LedgerQueryFilters
    ):
        """**Validates: Requirements 1.4, 2.4, 2.6, 2.7, 2.8**

        Each filter field in LedgerQueryFilters correctly maps to SQL clause
        presence or absence.
        """
        project_id = uuid.uuid4()
        year = 2025
        mock_db = AsyncMock()

        from app.models.audit_platform_models import TbLedger

        mock_filter = sa.and_(
            TbLedger.project_id == project_id,
            TbLedger.year == year,
            TbLedger.is_deleted == sa.false(),
        )

        with patch(
            "app.services.ledger_sampling_service.get_active_filter",
            new=AsyncMock(return_value=mock_filter),
        ):
            query = await LedgerSamplingService.build_ledger_query(
                db=mock_db,
                project_id=project_id,
                year=year,
                filters=filters,
            )

        compiled = query.compile(
            compile_kwargs={"literal_binds": True},
            dialect=sa.dialects.postgresql.dialect(),
        )
        sql_str = str(compiled).lower()

        # 1. account_codes → LIKE prefix conditions
        if filters.account_codes:
            for code in filters.account_codes:
                assert f"like '{code}%" in sql_str or f"like '{code.lower()}%" in sql_str, (
                    f"account_code prefix '{code}%' must appear in SQL. Got: {sql_str}"
                )

        # 2. direction_filter mapping
        # Check that the WHERE clause contains the specific direction condition
        if filters.direction_filter == "debit":
            assert "tb_ledger.debit_amount > 0" in sql_str, (
                f"debit direction must add 'debit_amount > 0'. Got: {sql_str}"
            )
        elif filters.direction_filter == "credit":
            assert "tb_ledger.credit_amount > 0" in sql_str, (
                f"credit direction must add 'credit_amount > 0'. Got: {sql_str}"
            )

        # 3. amount_threshold > 0 → greatest/coalesce condition
        if filters.amount_threshold > 0:
            assert "greatest" in sql_str, (
                f"Non-zero threshold must add GREATEST condition. Got: {sql_str}"
            )
            assert "coalesce" in sql_str, (
                f"Non-zero threshold must use COALESCE. Got: {sql_str}"
            )

        # 4. summary_keyword → ILIKE condition
        if filters.summary_keyword:
            assert "ilike" in sql_str or "like" in sql_str, (
                f"Non-empty keyword must add ILIKE/LIKE condition. Got: {sql_str}"
            )
            assert filters.summary_keyword.lower() in sql_str, (
                f"Keyword '{filters.summary_keyword}' must appear in SQL. Got: {sql_str}"
            )

        # 5. voucher_type_filter → IN condition
        if filters.voucher_type_filter:
            assert "voucher_type" in sql_str and "in" in sql_str, (
                f"voucher_type_filter must add IN condition. Got: {sql_str}"
            )

        # 6. exclude_voucher_nos → NOT IN condition
        if filters.exclude_voucher_nos:
            assert "voucher_no" in sql_str and "not in" in sql_str, (
                f"exclude_voucher_nos must add NOT IN condition. Got: {sql_str}"
            )


# ═══════════════════════════════════════════════════════════════════════════════
# Property 5: 统计摘要准确性
# Feature: cutoff-test-auto-sampling, Property 5: 统计摘要准确性
# ═══════════════════════════════════════════════════════════════════════════════


# Strategy for voucher entry dictionaries
@st.composite
def st_voucher_entries(draw):
    """Generate a list of voucher entries for stats calculation testing."""
    entries = draw(
        st.lists(
            st.fixed_dictionaries({
                "debit_amount": st.one_of(
                    st.none(),
                    st.decimals(
                        min_value=Decimal("0.01"),
                        max_value=Decimal("9999999.99"),
                        places=2,
                        allow_nan=False,
                        allow_infinity=False,
                    ),
                ),
                "credit_amount": st.one_of(
                    st.none(),
                    st.decimals(
                        min_value=Decimal("0.01"),
                        max_value=Decimal("9999999.99"),
                        places=2,
                        allow_nan=False,
                        allow_infinity=False,
                    ),
                ),
                "voucher_type": st.sampled_from(["记", "收", "付", "转", None]),
            }),
            min_size=0,
            max_size=50,
        )
    )
    return entries


class TestProperty5StatsAccuracy:
    """**Validates: Requirements 2.9**

    For any query result set, the StatsResult SHALL satisfy:
    - debit_total == sum of all debit_amount (NULL as 0)
    - credit_total == sum of all credit_amount (NULL as 0)
    - sum(by_voucher_type.values()) == total_count
    """

    @settings(max_examples=100)
    @given(entries=st_voucher_entries())
    def test_stats_computation_accuracy(self, entries: list[dict[str, Any]]):
        """**Validates: Requirements 2.9**

        Test pure stats calculation logic:
        debit_total = sum(debit), credit_total = sum(credit), by_type counts match.
        """
        # Compute expected stats
        total_count = len(entries)
        expected_debit = sum(
            e["debit_amount"] for e in entries if e["debit_amount"] is not None
        )
        expected_credit = sum(
            e["credit_amount"] for e in entries if e["credit_amount"] is not None
        )

        # Compute by_voucher_type
        expected_by_type: dict[str, int] = {}
        for e in entries:
            key = e["voucher_type"] if e["voucher_type"] is not None else "未分类"
            expected_by_type[key] = expected_by_type.get(key, 0) + 1

        # Build StatsResult matching the computation logic in execute_with_stats
        stats = StatsResult(
            total_count=total_count,
            debit_total=expected_debit,
            credit_total=expected_credit,
            by_voucher_type=expected_by_type,
            truncated=total_count > 500,
        )

        # Assert properties
        assert stats.total_count == total_count
        assert stats.debit_total == expected_debit
        assert stats.credit_total == expected_credit
        assert sum(stats.by_voucher_type.values()) == total_count, (
            f"Sum of by_voucher_type counts ({sum(stats.by_voucher_type.values())}) "
            f"must equal total_count ({total_count})"
        )

        # Each voucher type key corresponds to entries with that type
        for vtype, count in stats.by_voucher_type.items():
            if vtype == "未分类":
                actual = sum(1 for e in entries if e["voucher_type"] is None)
            else:
                actual = sum(1 for e in entries if e["voucher_type"] == vtype)
            assert count == actual, (
                f"by_voucher_type['{vtype}'] = {count} but actual count = {actual}"
            )


# ═══════════════════════════════════════════════════════════════════════════════
# Property 6: 截断阈值行为
# Feature: cutoff-test-auto-sampling, Property 6: 截断阈值行为
# ═══════════════════════════════════════════════════════════════════════════════


class TestProperty6TruncationThreshold:
    """**Validates: Requirements 2.10**

    > 500 → truncated=true + items <= 500
    <= 500 → truncated=false + items == total_count
    """

    @settings(max_examples=100)
    @given(total_count=st.integers(min_value=0, max_value=1000))
    def test_truncation_behavior(self, total_count: int):
        """**Validates: Requirements 2.10**

        Test truncation threshold logic as a pure property:
        - total > 500 → truncated=True, items capped at 500
        - total <= 500 → truncated=False, items == total
        """
        max_total = 500

        # Simulate the truncation logic from execute_with_stats
        truncated = total_count > max_total
        if truncated:
            returned_items_count = min(total_count, max_total)
        else:
            returned_items_count = total_count

        # Assert properties
        if total_count > 500:
            assert truncated is True, (
                f"total_count={total_count} > 500 must set truncated=True"
            )
            assert returned_items_count <= 500, (
                f"When truncated, items count ({returned_items_count}) must be <= 500"
            )
        else:
            assert truncated is False, (
                f"total_count={total_count} <= 500 must set truncated=False"
            )
            assert returned_items_count == total_count, (
                f"When not truncated, items count ({returned_items_count}) "
                f"must equal total_count ({total_count})"
            )


# ═══════════════════════════════════════════════════════════════════════════════
# Property 7: 金额 Decimal 序列化 Round-Trip
# Feature: cutoff-test-auto-sampling, Property 7: 金额 Decimal 序列化 Round-Trip
# ═══════════════════════════════════════════════════════════════════════════════


class TestProperty7DecimalRoundTrip:
    """**Validates: Requirements 2.11**

    Decimal(str(d)) == d for any Decimal with precision (20,2).
    """

    @settings(max_examples=100)
    @given(
        d=st.decimals(
            min_value=Decimal("-1e18"),
            max_value=Decimal("1e18"),
            places=2,
            allow_nan=False,
            allow_infinity=False,
        )
    )
    def test_decimal_serialization_round_trip(self, d: Decimal):
        """**Validates: Requirements 2.11**

        Serializing a Decimal to string then parsing back produces an equivalent value.
        """
        serialized = str(d)
        deserialized = Decimal(serialized)
        assert deserialized == d, (
            f"Round-trip failed: original={d}, serialized='{serialized}', "
            f"deserialized={deserialized}"
        )


# ═══════════════════════════════════════════════════════════════════════════════
# Property 9: 排除已提取凭证去重
# Feature: cutoff-test-auto-sampling, Property 9: 排除已提取凭证去重
# ═══════════════════════════════════════════════════════════════════════════════


class TestProperty9ExcludeExtractedDedup:
    """**Validates: Requirements 2.12**

    After filtering, result ∩ extracted = ∅; all non-extracted items preserved.
    """

    @settings(max_examples=100)
    @given(
        extracted_nos=st.lists(
            st.text(min_size=1, max_size=20, alphabet="0123456789-ABCabc"),
            min_size=0,
            max_size=30,
        ),
        query_result_nos=st.lists(
            st.text(min_size=1, max_size=20, alphabet="0123456789-ABCabc"),
            min_size=0,
            max_size=30,
        ),
    )
    def test_exclude_extracted_dedup(
        self,
        extracted_nos: list[str],
        query_result_nos: list[str],
    ):
        """**Validates: Requirements 2.12**

        When exclude_extracted=True:
        - Filtered result has no overlap with extracted set
        - All non-extracted items from query result are preserved (no false exclusions)
        """
        extracted_set = set(extracted_nos)

        # Simulate the exclusion logic: filter out voucher_nos in extracted set
        filtered_result = [
            no for no in query_result_nos if no not in extracted_set
        ]

        # Property 1: intersection with extracted must be empty
        filtered_set = set(filtered_result)
        intersection = filtered_set & extracted_set
        assert intersection == set(), (
            f"Filtered result must not contain extracted voucher_nos. "
            f"Intersection: {intersection}"
        )

        # Property 2: all non-extracted items from query result must be preserved
        expected_preserved = [
            no for no in query_result_nos if no not in extracted_set
        ]
        assert filtered_result == expected_preserved, (
            f"All non-extracted items must be preserved in order. "
            f"Expected: {expected_preserved}, Got: {filtered_result}"
        )

        # Property 3: no false exclusions — every item in query_result that
        # is NOT in extracted must appear in filtered
        non_extracted_from_query = {no for no in query_result_nos if no not in extracted_set}
        assert non_extracted_from_query <= filtered_set, (
            f"Some non-extracted items were falsely excluded. "
            f"Missing: {non_extracted_from_query - filtered_set}"
        )
