-- V033: 全量 schema 同步（消除 ORM-vs-DB 列级漂移）
-- Auto-generated by gen_schema_sync_migration.py
-- 所有语句幂等，可重复执行

-- ============================================
-- Enum 类型创建/补值
-- ============================================

DO $$ BEGIN
    CREATE TYPE knowledge_access_level AS ENUM ('public', 'project_group', 'private');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
ALTER TYPE knowledge_access_level ADD VALUE IF NOT EXISTS 'public';
ALTER TYPE knowledge_access_level ADD VALUE IF NOT EXISTS 'project_group';
ALTER TYPE knowledge_access_level ADD VALUE IF NOT EXISTS 'private';
DO $$ BEGIN
    CREATE TYPE template_type_enum AS ENUM ('report_soe', 'report_listed', 'workpaper_preset', 'workpaper_custom');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
ALTER TYPE template_type_enum ADD VALUE IF NOT EXISTS 'report_soe';
ALTER TYPE template_type_enum ADD VALUE IF NOT EXISTS 'report_listed';
ALTER TYPE template_type_enum ADD VALUE IF NOT EXISTS 'workpaper_preset';
ALTER TYPE template_type_enum ADD VALUE IF NOT EXISTS 'workpaper_custom';

-- ============================================
-- 缺失表（ORM 定义但 DB 不存在）
-- ============================================

-- Table: audit_log_entries
CREATE TABLE IF NOT EXISTS audit_log_entries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    ts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    user_id UUID,
    session_id VARCHAR(128),
    action_type VARCHAR(64) NOT NULL DEFAULT '',
    object_type VARCHAR(64) NOT NULL DEFAULT '',
    object_id UUID,
    payload JSONB,
    ip VARCHAR(45),
    ua TEXT,
    trace_id VARCHAR(64),
    prev_hash VARCHAR(64) NOT NULL DEFAULT '',
    entry_hash VARCHAR(64) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
);

-- Table: chain_executions
CREATE TABLE IF NOT EXISTS chain_executions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL DEFAULT gen_random_uuid(),
    year INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT '',
    steps JSONB NOT NULL DEFAULT '{}',
    trigger_type VARCHAR(20) NOT NULL DEFAULT '',
    triggered_by UUID,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    total_duration_ms INTEGER,
    snapshot_before JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: config_references
CREATE TABLE IF NOT EXISTS config_references (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL DEFAULT gen_random_uuid(),
    template_id UUID NOT NULL DEFAULT gen_random_uuid(),
    config_type VARCHAR(50) NOT NULL DEFAULT '',
    applied_at TIMESTAMP WITH TIME ZONE,
    applied_by UUID,
    is_customized BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: cross_check_results
CREATE TABLE IF NOT EXISTS cross_check_results (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL DEFAULT gen_random_uuid(),
    year INTEGER NOT NULL DEFAULT 0,
    rule_id VARCHAR(30) NOT NULL DEFAULT '',
    left_amount NUMERIC(20, 2),
    right_amount NUMERIC(20, 2),
    difference NUMERIC(20, 2),
    status VARCHAR(20) NOT NULL DEFAULT '',
    details JSONB,
    checked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: custom_query_templates
CREATE TABLE IF NOT EXISTS custom_query_templates (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL DEFAULT '',
    description TEXT,
    data_source VARCHAR(50),
    config JSONB NOT NULL DEFAULT '{}',
    scope VARCHAR(16) NOT NULL DEFAULT 'private',
    tags TEXT[] NOT NULL DEFAULT '{}',
    use_count INTEGER NOT NULL DEFAULT 0,
    last_used_at TIMESTAMP WITH TIME ZONE,
    creator_id UUID,
    created_by UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: evidence_links
CREATE TABLE IF NOT EXISTS evidence_links (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    wp_id UUID NOT NULL DEFAULT gen_random_uuid(),
    sheet_name VARCHAR(100),
    cell_ref VARCHAR(20),
    attachment_id UUID NOT NULL DEFAULT gen_random_uuid(),
    page_ref VARCHAR(50),
    evidence_type VARCHAR(30),
    check_conclusion VARCHAR(200),
    created_by UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: handover_records
CREATE TABLE IF NOT EXISTS handover_records (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    from_staff_id UUID NOT NULL DEFAULT gen_random_uuid(),
    to_staff_id UUID NOT NULL DEFAULT gen_random_uuid(),
    scope VARCHAR(20) NOT NULL DEFAULT '',
    project_ids JSONB,
    reason_code VARCHAR(30) NOT NULL DEFAULT '',
    reason_detail TEXT,
    effective_date DATE NOT NULL DEFAULT CURRENT_DATE,
    workpapers_moved INTEGER NOT NULL DEFAULT 0,
    issues_moved INTEGER NOT NULL DEFAULT 0,
    assignments_moved INTEGER NOT NULL DEFAULT 0,
    executed_by UUID NOT NULL DEFAULT gen_random_uuid(),
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: knowledge_documents
CREATE TABLE IF NOT EXISTS knowledge_documents (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    folder_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(500) NOT NULL DEFAULT '',
    file_type VARCHAR(20),
    file_size BIGINT NOT NULL DEFAULT 0,
    storage_path TEXT,
    content_text TEXT,
    content_summary TEXT,
    access_level knowledge_access_level,
    project_ids JSONB,
    tags JSONB,
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    version INTEGER NOT NULL DEFAULT 1,
    previous_version_id UUID,
    PRIMARY KEY (id)
);

-- Table: knowledge_folders
CREATE TABLE IF NOT EXISTS knowledge_folders (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(200) NOT NULL DEFAULT '',
    parent_id UUID,
    category VARCHAR(50),
    description TEXT,
    access_level knowledge_access_level NOT NULL DEFAULT 'public',
    project_ids JSONB,
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

-- Table: note_account_mappings
CREATE TABLE IF NOT EXISTS note_account_mappings (
    id VARCHAR(36) NOT NULL DEFAULT '',
    template_type VARCHAR(20) NOT NULL DEFAULT '',
    report_row_code VARCHAR(50) NOT NULL DEFAULT '',
    note_section_code VARCHAR(100) NOT NULL DEFAULT '',
    table_index INTEGER NOT NULL DEFAULT 0,
    validation_role VARCHAR(30),
    wp_code VARCHAR(30),
    fetch_mode VARCHAR(30),
    PRIMARY KEY (id)
);

-- Table: partner_rotation_overrides
CREATE TABLE IF NOT EXISTS partner_rotation_overrides (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    staff_id UUID NOT NULL DEFAULT gen_random_uuid(),
    client_name VARCHAR(255) NOT NULL DEFAULT '',
    original_years INTEGER NOT NULL DEFAULT 0,
    override_reason TEXT NOT NULL DEFAULT '',
    approved_by_compliance_partner UUID,
    approved_by_chief_risk_partner UUID,
    override_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: project_quality_ratings
CREATE TABLE IF NOT EXISTS project_quality_ratings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL DEFAULT gen_random_uuid(),
    year INTEGER NOT NULL DEFAULT 0,
    rating VARCHAR(1) NOT NULL DEFAULT '',
    score INTEGER NOT NULL DEFAULT 0,
    dimensions JSONB,
    computed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    computed_by_rule_version INTEGER NOT NULL DEFAULT 1,
    override_by UUID,
    override_rating VARCHAR(1),
    override_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: project_template_selections
CREATE TABLE IF NOT EXISTS project_template_selections (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL DEFAULT gen_random_uuid(),
    template_id UUID NOT NULL DEFAULT gen_random_uuid(),
    template_type template_type_enum,
    pulled_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    linked_trial_balance BOOLEAN NOT NULL DEFAULT false,
    linked_adjustments BOOLEAN NOT NULL DEFAULT false,
    linked_attachments BOOLEAN NOT NULL DEFAULT false,
    last_sync_at TIMESTAMP WITH TIME ZONE,
    selected_by UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: qc_case_library
CREATE TABLE IF NOT EXISTS qc_case_library (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    title VARCHAR(200) NOT NULL DEFAULT '',
    category VARCHAR(50) NOT NULL DEFAULT '',
    severity VARCHAR(20) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    lessons_learned TEXT,
    related_wp_refs JSONB,
    related_standards JSONB,
    published_by UUID NOT NULL DEFAULT gen_random_uuid(),
    published_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    review_count INTEGER NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: qc_inspection_items
CREATE TABLE IF NOT EXISTS qc_inspection_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    inspection_id UUID NOT NULL DEFAULT gen_random_uuid(),
    wp_id UUID NOT NULL DEFAULT gen_random_uuid(),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    findings JSONB,
    qc_verdict VARCHAR(20),
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: qc_inspection_records
CREATE TABLE IF NOT EXISTS qc_inspection_records (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    inspection_item_id UUID NOT NULL DEFAULT gen_random_uuid(),
    comment TEXT NOT NULL DEFAULT '',
    severity VARCHAR(20) NOT NULL DEFAULT '',
    cell_ref VARCHAR(20),
    created_by UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: qc_inspections
CREATE TABLE IF NOT EXISTS qc_inspections (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL DEFAULT gen_random_uuid(),
    strategy VARCHAR(30) NOT NULL DEFAULT '',
    params JSONB,
    reviewer_id UUID NOT NULL DEFAULT gen_random_uuid(),
    status VARCHAR(20) NOT NULL DEFAULT 'created',
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    report_url VARCHAR(500),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: reviewer_metrics_snapshots
CREATE TABLE IF NOT EXISTS reviewer_metrics_snapshots (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    reviewer_id UUID NOT NULL DEFAULT gen_random_uuid(),
    year INTEGER NOT NULL DEFAULT 0,
    snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
    avg_review_time_min FLOAT,
    avg_comments_per_wp FLOAT,
    rejection_rate FLOAT,
    qc_rule_catch_rate FLOAT,
    sampled_rework_rate FLOAT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: shared_config_templates
CREATE TABLE IF NOT EXISTS shared_config_templates (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(200) NOT NULL DEFAULT '',
    description TEXT,
    config_type VARCHAR(50) NOT NULL DEFAULT '',
    owner_type VARCHAR(20) NOT NULL DEFAULT '',
    owner_user_id UUID,
    owner_project_id UUID,
    owner_project_name VARCHAR(200),
    config_data JSONB NOT NULL DEFAULT '{}',
    config_version INTEGER,
    applicable_standard VARCHAR(50),
    is_public BOOLEAN,
    allowed_project_ids JSONB,
    reference_count INTEGER,
    last_referenced_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

-- Table: workpaper_editing_locks
CREATE TABLE IF NOT EXISTS workpaper_editing_locks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    wp_id UUID NOT NULL DEFAULT gen_random_uuid(),
    staff_id UUID NOT NULL DEFAULT gen_random_uuid(),
    acquired_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    heartbeat_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    released_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: workpaper_procedures
CREATE TABLE IF NOT EXISTS workpaper_procedures (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    wp_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL DEFAULT gen_random_uuid(),
    procedure_id VARCHAR(20) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    category VARCHAR(30) NOT NULL DEFAULT 'routine',
    is_mandatory BOOLEAN NOT NULL DEFAULT true,
    applicable_project_types JSONB DEFAULT '["all"]',
    depends_on JSONB DEFAULT '[]',
    evidence_type VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    completed_by UUID,
    completed_at TIMESTAMP WITH TIME ZONE,
    trimmed_by UUID,
    trimmed_at TIMESTAMP WITH TIME ZONE,
    trim_reason TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- Table: workpaper_snapshots
CREATE TABLE IF NOT EXISTS workpaper_snapshots (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    wp_id UUID NOT NULL DEFAULT gen_random_uuid(),
    trigger_event VARCHAR(50) NOT NULL DEFAULT '',
    snapshot_data JSONB NOT NULL DEFAULT '{}',
    created_by UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    is_locked BOOLEAN NOT NULL DEFAULT false,
    bound_dataset_id UUID,
    PRIMARY KEY (id)
);

-- Table: wp_template_metadata
CREATE TABLE IF NOT EXISTS wp_template_metadata (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    template_id UUID,
    wp_code VARCHAR(20) NOT NULL DEFAULT '',
    component_type VARCHAR(20) NOT NULL DEFAULT 'univer',
    audit_stage VARCHAR(30) NOT NULL DEFAULT '',
    cycle VARCHAR(10),
    file_format VARCHAR(10),
    procedure_steps JSONB DEFAULT '[]',
    guidance_text TEXT,
    formula_cells JSONB DEFAULT '[]',
    required_regions JSONB DEFAULT '[]',
    linked_accounts JSONB DEFAULT '[]',
    note_section VARCHAR(20),
    conclusion_cell JSONB,
    audit_objective TEXT,
    related_assertions JSONB DEFAULT '[]',
    procedure_flow_config TEXT,
    header_cells JSONB DEFAULT '{}',
    llm_prompts JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

-- ============================================
-- 缺失列（ORM 定义但 DB 不存在）
-- ============================================

-- Table: gate_rule_configs
ALTER TABLE gate_rule_configs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE gate_rule_configs ADD COLUMN IF NOT EXISTS description VARCHAR(200);

-- Table: import_column_mapping_history
ALTER TABLE import_column_mapping_history ADD COLUMN IF NOT EXISTS file_fingerprint VARCHAR(40);
ALTER TABLE import_column_mapping_history ADD COLUMN IF NOT EXISTS override_parent_id UUID;

-- Table: qc_rule_definitions
ALTER TABLE qc_rule_definitions ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE qc_rule_definitions ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT false;

-- Table: staff_members
ALTER TABLE staff_members ADD COLUMN IF NOT EXISTS role_level VARCHAR(20);

-- Table: t_account_entries
ALTER TABLE t_account_entries ADD COLUMN IF NOT EXISTS amount NUMERIC(20, 2) NOT NULL DEFAULT 0;
ALTER TABLE t_account_entries ADD COLUMN IF NOT EXISTS entry_type VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE t_account_entries ADD COLUMN IF NOT EXISTS reference_id UUID;

-- Table: t_accounts
ALTER TABLE t_accounts ADD COLUMN IF NOT EXISTS created_by UUID;
ALTER TABLE t_accounts ADD COLUMN IF NOT EXISTS description TEXT;

-- Table: time_machine_snapshots
ALTER TABLE time_machine_snapshots ADD COLUMN IF NOT EXISTS diff_json JSONB NOT NULL DEFAULT '{}';
ALTER TABLE time_machine_snapshots ADD COLUMN IF NOT EXISTS instance_type VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE time_machine_snapshots ADD COLUMN IF NOT EXISTS parent_snapshot_id UUID;
ALTER TABLE time_machine_snapshots ADD COLUMN IF NOT EXISTS project_id UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE time_machine_snapshots ADD COLUMN IF NOT EXISTS user_id UUID NOT NULL DEFAULT gen_random_uuid();

-- Table: word_export_task
ALTER TABLE word_export_task ADD COLUMN IF NOT EXISTS cache_key VARCHAR(64);

-- Table: work_hours
ALTER TABLE work_hours ADD COLUMN IF NOT EXISTS purpose VARCHAR(20);