import http from '@/utils/http'

type Loose = Record<string, unknown>

export type ReportType = 'balance_sheet' | 'income_statement' | 'cash_flow'
export type ReviewStatus = 'draft' | 'pending_review' | 'approved' | 'rejected'
export type ArApReconciliationStatus = 'matched' | 'unmatched' | 'adjusted' | 'tolerance'
export type EliminationEntryType = 'investment' | 'ar_ap' | 'transaction' | 'internal_income' | 'other' | 'equity' | 'internal_trade' | 'internal_ar_ap' | 'unrealized_profit'

export interface CompanyTreeNode extends Loose { id: string; companyCode: string; companyName: string; company_code?: string; company_name?: string; parent_code?: string | null; shareholding?: number | null; consol_method?: string | null; children: CompanyTreeNode[] }
export type CompanyCreatePayload = Loose & { project_id: string; company_code: string; company_name: string }
export type CompanyUpdatePayload = Loose
export interface ConsolScopeRow extends Loose { id: string; year: number; companyCode: string; companyName: string; company_code?: string; company_name?: string; isIncluded: boolean; is_included?: boolean; shareholding?: number | string | null; consol_method?: string | null; scope_change_type?: string | null; exclusion_reason?: string | null; inclusion_reason?: string | null }
export type ConsolScope = ConsolScopeRow
export interface ConsolTrialRow extends Loose { id: string; year: number; account_code: string; account_name: string; account_category?: string | null; individual_sum: number; consol_adjustment: number; consolidation_adjustment: number; consol_elimination: number; consol_amount: number }
export interface ConsistencyCheckResult { is_balanced: boolean; total_debit: number; total_credit: number; difference: number; errors: string[]; warnings: string[] }
export interface ConsolTrialBalanceEntry extends ConsolTrialRow { company_amounts?: Record<string, { debit?: number; credit?: number }>; elimination_details?: Array<{ id: string; entry_no?: string; entry_type?: string; amount?: number }> }
export interface ConsolTrialBalanceFilter { year?: number; account_category?: string; company_codes?: string[] }
export interface InternalTradeDetail extends Loose { id: string; year: number; seller_company_code: string; buyer_company_code: string; trade_type?: string | null; trade_amount: number; cost_amount: number; unrealized_profit: number; inventory_remaining_ratio: number }
export type InternalTrade = InternalTradeDetail
export interface TransactionMatrix { company_codes: string[]; matrix: Record<string, Record<string, number>> }
export interface TradeEliminationStatus { generated_count: number; entry_ids: string[]; message?: string }
export interface InternalArApRow extends Loose { id: string; year: number; company_code: string; counterparty_code: string; arap_type?: 'ar' | 'ap'; debit_balance: number; credit_balance: number; after_elimination: number; difference_amount: number; reconciliation_status: ArApReconciliationStatus }
export interface GoodwillRow extends Loose { id: string; project_id: string; year: number; cash_generating_unit?: string; acquisition_name?: string; initial_amount?: string; cumulative_impairment?: string; net_amount?: string; recoverable_amount?: string; impairment_test_date?: string; acquisition_cost?: number; identifiable_net_assets_fv?: number; parent_share_ratio?: number; goodwill_amount?: number; accumulated_impairment?: number; current_year_impairment?: number; carrying_amount?: number; is_negative_goodwill?: boolean; notes?: string }
export interface ForexRow extends Loose { id: string; project_id: string; year: number; company_code?: string; entity_name?: string; currency?: string; functional_currency?: string; reporting_currency?: string; exchange_rate_used?: string; monetary_assets?: string; monetary_liabilities?: string; translation_differences?: string; bs_closing_rate?: number; pl_average_rate?: number; equity_historical_rate?: number; notes?: string }
export interface MinorityInterestRow extends Loose { id: string; project_id: string; year: number; subsidiary_name?: string; ownership_percentage?: string; minority_percentage?: string; total_equity?: string; minority_interest_amount?: string; changes?: string; notes?: string; subsidiary_net_assets?: number; minority_share_ratio?: number; minority_equity?: number; minority_profit?: number }
export interface ComponentAuditor extends Loose { id: string; project_id: string; component_name?: string; auditor_name?: string; auditor_email?: string; scope?: string; status: string; company_code?: string; firm_name?: string; contact_person?: string; contact_info?: string; competence_rating?: string; rating_basis?: string }
export interface Instruction extends Loose { id: string; project_id: string; component_auditor_id: string; instruction_no?: string; content?: string; issued_date?: string; due_date?: string; scope?: string; status: string; attachments?: string[] }
export interface InstructionResult extends Loose { id: string; project_id: string; component_auditor_id: string; instruction_id?: string; result_no?: string; summary?: string; received_date?: string; status: string; attachments?: string[]; opinion_type?: string; findings?: string; recommendations?: string; evaluation_rating?: string }
export interface ComponentDashboard extends Loose { total_auditors: number; pending_instructions: number; pending_results: number; received_results: number; non_standard_opinions: number }
export interface EliminationLine extends Loose { account_code: string; account_name?: string; debit_amount?: number; credit_amount?: number; direction?: 'debit' | 'credit'; amount?: number }
export interface EliminationEntry extends Loose { id: string; year: number; entry_no: string; entry_type: EliminationEntryType; description: string; review_status: ReviewStatus; lines: EliminationLine[]; related_company_codes?: string[]; debit_amount: number; credit_amount: number }
export interface EliminationEntryCreatePayload extends Loose { year: string | number; entry_type: EliminationEntryType; description?: string; related_company_codes?: string[]; lines: EliminationLine[] }
export interface EliminationEntryUpdatePayload extends Partial<EliminationEntryCreatePayload> {}
export interface EliminationListFilter { year?: number; entry_type?: EliminationEntryType; review_status?: ReviewStatus }
export interface EliminationSummary extends Loose { total_debit: number; total_credit: number; total_count: number; by_type?: Array<{ entry_type: EliminationEntryType; count: number; total_debit: number; total_credit: number }> }
export interface ConsolReportRow extends Loose { line_no: string; account_name: string; before_amount: number; adjustment: number; after_amount: number; consol_amount: number; current_period_amount: number; prior_period_amount: number }
export interface ConsolReportData { report_type: ReportType; period: string; rows: ConsolReportRow[] }
export interface YoYAnalysis { account_name: string; current_amount: number; prior_amount: number; change: number; change_pct: number }
export interface ConsolScopeNote { seq: number; company_name: string; shareholding: string; voting_rights: string; is_included: boolean; inclusion_date?: string; exit_date?: string; notes?: string }
export interface SubsidiaryNote { company_name: string; registration_place?: string; business_nature?: string; registered_capital?: number | string; paid_capital?: number | string; shareholding?: string; minority_equity_end?: number | string }
export interface GoodwillNote { acquiree: string; opening_balance: number; current_increase: number; current_decrease: number; current_impairment: number; closing_balance: number }
export interface MinorityInterestNote { subsidiary_name: string; opening_balance: number; share_of_profit: number; share_of_loss: number; dividends_paid: number; other_changes: number; closing_balance: number }
export interface InternalTradeNote { trade_type: string; trade_amount: number; elimination_amount: number }
export interface InternalArApNote { arap_type: string; debit_balance: number; credit_balance: number; after_elimination: number }
export interface ForexTranslationNote { currency: string; statement_rate: number | string; income_expense_avg_rate: number | string; translation_diff: number }

interface ConsolDisclosureSection { section_code: string; rows: Loose[]; summary?: string | null }

const rec = (v: unknown): Loose => (v && typeof v === 'object' ? (v as Loose) : {})
const arr = <T = Loose>(v: unknown): T[] => (Array.isArray(v) ? (v as T[]) : [])
const str = (v: unknown, f = '') => (v == null ? f : String(v))
const num = (v: unknown, f = 0) => { const x = typeof v === 'number' ? v : Number(v); return Number.isFinite(x) ? x : f }
const bool = (v: unknown) => v === true || v === 'true' || v === 1
const yr = (v?: string | number) => { const m = str(v).match(/\d{4}/); return typeof v === 'number' && Number.isFinite(v) ? v : m ? Number(m[0]) : new Date().getFullYear() }
const unwrap = <T,>(r: { data: unknown }): T => ((rec(r.data).data ?? r.data) as T)
const pct = (v: unknown) => str(v).replace(/%/g, '')
const ratio = (v: unknown) => { const x = num(v); return x > 1 ? x / 100 : x }
const toFrontType = (v: unknown): EliminationEntryType => ({ equity: 'investment', internal_trade: 'transaction', internal_ar_ap: 'ar_ap', unrealized_profit: 'internal_income' } as Record<string, EliminationEntryType>)[str(v)] ?? (str(v) as EliminationEntryType) ?? 'other'
const toBackType = (v: EliminationEntryType) => ({ investment: 'equity', transaction: 'internal_trade', ar_ap: 'internal_ar_ap', internal_income: 'unrealized_profit' } as Partial<Record<EliminationEntryType, string>>)[v] ?? v
const unsupported = (m: string): never => { throw new Error(m) }
const blobUrl = async (url: string, params?: Loose) => { const r = await http.get(url, { params, responseType: 'blob' }); return URL.createObjectURL(r.data as Blob) }

const node = (v: unknown): CompanyTreeNode => { const r = rec(v); const code = str(r.companyCode ?? r.company_code); const name = str(r.companyName ?? r.company_name); return { ...r, id: str(r.id), companyCode: code, companyName: name, company_code: code, company_name: name, parent_code: r.parent_code == null ? null : str(r.parent_code), shareholding: r.shareholding == null ? null : num(r.shareholding), consol_method: str(r.consol_method) || null, children: arr(r.children).map(node) } }
const scope = (v: unknown): ConsolScopeRow => { const r = rec(v); const code = str(r.companyCode ?? r.company_code); const name = str(r.companyName ?? r.company_name); const included = bool(r.isIncluded ?? r.is_included); return { ...r, id: str(r.id), year: num(r.year, new Date().getFullYear()), companyCode: code, companyName: name, company_code: code, company_name: name, isIncluded: included, is_included: included, shareholding: (r.shareholding ?? r.ownership_ratio ?? null) as number | string | null, consol_method: str(r.consol_method ?? r.consolMethod) || null, scope_change_type: str(r.scope_change_type ?? r.scopeChangeType) || null, exclusion_reason: str(r.exclusion_reason ?? r.exclusionReason) || null, inclusion_reason: str(r.inclusion_reason ?? r.inclusionReason) || null } }
const trial = (v: unknown): ConsolTrialRow => { const r = rec(v); const adj = num(r.consol_adjustment ?? r.consolidation_adjustment); return { ...r, id: str(r.id), year: num(r.year, new Date().getFullYear()), account_code: str(r.account_code ?? r.standard_account_code), account_name: str(r.account_name), account_category: str(r.account_category) || null, individual_sum: num(r.individual_sum), consol_adjustment: adj, consolidation_adjustment: adj, consol_elimination: num(r.consol_elimination), consol_amount: num(r.consol_amount) } }
const trade = (v: unknown): InternalTradeDetail => { const r = rec(v); return { ...r, id: str(r.id), year: num(r.year, new Date().getFullYear()), seller_company_code: str(r.seller_company_code), buyer_company_code: str(r.buyer_company_code), trade_type: str(r.trade_type) || null, trade_amount: num(r.trade_amount), cost_amount: num(r.cost_amount), unrealized_profit: num(r.unrealized_profit), inventory_remaining_ratio: num(r.inventory_remaining_ratio) } }
const arap = (v: unknown): InternalArApRow => { const r = rec(v); const debit = num(r.debit_balance ?? r.debtor_amount); const credit = num(r.credit_balance ?? r.creditor_amount); return { ...r, id: str(r.id), year: num(r.year, new Date().getFullYear()), company_code: str(r.company_code ?? r.debtor_company_code), counterparty_code: str(r.counterparty_code ?? r.creditor_company_code), arap_type: (str(r.arap_type) as 'ar' | 'ap') || 'ar', debit_balance: debit, credit_balance: credit, after_elimination: num(r.after_elimination, debit - credit), difference_amount: num(r.difference_amount, debit - credit), reconciliation_status: (str(r.reconciliation_status) as ArApReconciliationStatus) || 'unmatched' } }
const goodwill = (v: unknown): GoodwillRow => { const r = rec(v); const cgu = str(r.cash_generating_unit ?? r.subsidiary_company_code ?? r.acquisition_name); const cost = num(r.acquisition_cost ?? r.initial_amount); const imp = num(r.accumulated_impairment ?? r.cumulative_impairment); const net = num(r.carrying_amount ?? r.net_amount ?? r.goodwill_amount); return { ...r, id: str(r.id), project_id: str(r.project_id), year: num(r.year, new Date().getFullYear()), cash_generating_unit: cgu, acquisition_name: cgu, initial_amount: str(r.initial_amount ?? cost), cumulative_impairment: str(r.cumulative_impairment ?? imp), net_amount: str(r.net_amount ?? net), recoverable_amount: str(r.recoverable_amount), impairment_test_date: str(r.impairment_test_date), acquisition_cost: cost, identifiable_net_assets_fv: num(r.identifiable_net_assets_fv), parent_share_ratio: num(r.parent_share_ratio, 1), goodwill_amount: num(r.goodwill_amount ?? net), accumulated_impairment: imp, current_year_impairment: num(r.current_year_impairment), carrying_amount: net, is_negative_goodwill: bool(r.is_negative_goodwill), notes: str(r.notes) } }
const forex = (v: unknown): ForexRow => { const r = rec(v); const code = str(r.company_code ?? r.entity_name ?? r.currency); const fc = str(r.functional_currency ?? r.currency); return { ...r, id: str(r.id), project_id: str(r.project_id), year: num(r.year, new Date().getFullYear()), company_code: code, entity_name: str(r.entity_name ?? code), currency: str(r.currency ?? fc), functional_currency: fc, reporting_currency: str(r.reporting_currency), exchange_rate_used: str(r.exchange_rate_used ?? r.bs_closing_rate), monetary_assets: str(r.monetary_assets ?? r.bs_closing_assets), monetary_liabilities: str(r.monetary_liabilities ?? r.bs_closing_liabilities), translation_differences: str(r.translation_differences ?? r.translation_difference ?? r.translation_difference_oci), bs_closing_rate: num(r.bs_closing_rate), pl_average_rate: num(r.pl_average_rate), equity_historical_rate: num(r.equity_historical_rate), notes: str(r.notes ?? r.translation_description) } }
const mi = (v: unknown): MinorityInterestRow => { const r = rec(v); const mr = ratio(r.minority_share_ratio ?? r.minority_percentage); const own = (1 - mr) * 100; return { ...r, id: str(r.id), project_id: str(r.project_id), year: num(r.year, new Date().getFullYear()), subsidiary_name: str(r.subsidiary_name ?? r.subsidiary_company_code), ownership_percentage: str(r.ownership_percentage ?? own), minority_percentage: str(r.minority_percentage ?? mr * 100), total_equity: str(r.total_equity ?? r.subsidiary_net_assets), minority_interest_amount: str(r.minority_interest_amount ?? r.minority_equity), changes: str(r.changes), notes: str(r.notes), subsidiary_net_assets: num(r.subsidiary_net_assets ?? r.total_equity), minority_share_ratio: mr, minority_equity: num(r.minority_equity ?? r.minority_interest_amount), minority_profit: num(r.minority_profit) } }
const auditor = (v: unknown): ComponentAuditor => { const r = rec(v); const name = str(r.auditor_name ?? r.contact_person ?? r.firm_name); const email = str(r.auditor_email ?? r.contact_info); const component = str(r.component_name ?? r.company_code); const scopeText = str(r.scope ?? r.rating_basis); return { ...r, id: str(r.id), project_id: str(r.project_id), component_name: component, auditor_name: name, auditor_email: email, scope: scopeText, status: str(r.status) || 'active', company_code: str(r.company_code ?? component), firm_name: str(r.firm_name ?? name), contact_person: str(r.contact_person ?? name), contact_info: email, competence_rating: str(r.competence_rating) || 'reliable', rating_basis: str(r.rating_basis ?? scopeText) || 'frontend' } }
const instruction = (v: unknown): Instruction => { const r = rec(v); return { ...r, id: str(r.id), project_id: str(r.project_id), component_auditor_id: str(r.component_auditor_id), instruction_no: str(r.instruction_no ?? r.id), content: str(r.content ?? r.special_attention_items ?? r.audit_scope_description), issued_date: str(r.issued_date ?? r.instruction_date), due_date: str(r.due_date), scope: str(r.scope ?? r.reporting_format ?? r.audit_scope_description), status: str(r.status) || 'draft', attachments: arr<string>(r.attachments) } }
const result = (v: unknown): InstructionResult => { const r = rec(v); const status = str(r.status) || (str(r.evaluation_status) === 'accepted' ? 'reviewed_result' : 'pending'); return { ...r, id: str(r.id), project_id: str(r.project_id), component_auditor_id: str(r.component_auditor_id), instruction_id: str(r.instruction_id), result_no: str(r.result_no ?? r.id), summary: str(r.summary ?? r.significant_findings), received_date: str(r.received_date), status, attachments: arr<string>(r.attachments), opinion_type: str(r.opinion_type), findings: str(r.findings ?? r.significant_findings), recommendations: str(r.recommendations ?? r.group_team_evaluation), evaluation_rating: str(r.evaluation_rating ?? r.evaluation_status) } }
const entry = (v: unknown): EliminationEntry => { const r = rec(v); const lines = arr<Loose>(r.lines).map(line => ({ ...line, account_code: str(line.account_code), account_name: str(line.account_name), debit_amount: num(line.debit_amount), credit_amount: num(line.credit_amount) })); return { ...r, id: str(r.id), year: num(r.year, new Date().getFullYear()), entry_no: str(r.entry_no), entry_type: toFrontType(r.entry_type), description: str(r.description), review_status: (str(r.review_status) as ReviewStatus) || 'draft', lines, related_company_codes: arr<string>(r.related_company_codes), debit_amount: num(r.debit_amount, lines.reduce((s, line) => s + num(line.debit_amount), 0)), credit_amount: num(r.credit_amount, lines.reduce((s, line) => s + num(line.credit_amount), 0)) } }
const reportRow = (v: unknown): ConsolReportRow => { const r = rec(v); const current = num(r.current_period_amount ?? r.consol_amount ?? r.after_amount); const prior = num(r.prior_period_amount ?? r.before_amount); return { ...r, line_no: str(r.line_no ?? r.row_code), account_name: str(r.account_name ?? r.row_name), before_amount: prior, adjustment: num(r.adjustment), after_amount: num(r.after_amount, current), consol_amount: num(r.consol_amount, current), current_period_amount: current, prior_period_amount: prior } }
const reviewPayload = (action: 'approve' | 'reject', reason?: string) => ({ action, rejection_reason: reason })
const auditorPayload = (p: Loose) => ({ company_code: str(p.company_code ?? p.component_name), firm_name: str(p.firm_name ?? p.auditor_name), contact_person: str(p.contact_person ?? p.auditor_name), contact_info: str(p.contact_info ?? p.auditor_email), competence_rating: str(p.competence_rating) || 'reliable', rating_basis: str(p.rating_basis ?? p.scope) || 'frontend', independence_confirmed: p.independence_confirmed == null ? true : bool(p.independence_confirmed), independence_date: str(p.independence_date) || undefined })
const instructionPayload = (p: Loose, includeStatus = false) => ({ component_auditor_id: str(p.component_auditor_id), instruction_date: str(p.instruction_date ?? p.issued_date) || undefined, due_date: str(p.due_date) || undefined, materiality_level: p.materiality_level, audit_scope_description: str(p.audit_scope_description ?? p.scope ?? p.content) || undefined, reporting_format: str(p.reporting_format ?? p.scope) || undefined, special_attention_items: str(p.special_attention_items ?? p.content) || undefined, instruction_file_path: str(p.instruction_file_path) || undefined, ...(includeStatus ? { status: str(p.status) || undefined } : {}) })
const resultPayload = (p: Loose) => ({ component_auditor_id: str(p.component_auditor_id), received_date: str(p.received_date) || undefined, opinion_type: str(p.opinion_type) || undefined, identified_misstatements: p.identified_misstatements, significant_findings: str(p.significant_findings ?? p.summary ?? p.findings) || undefined, result_file_path: str(p.result_file_path) || undefined, group_team_evaluation: str(p.group_team_evaluation ?? p.recommendations) || undefined, needs_additional_procedures: bool(p.needs_additional_procedures), evaluation_status: str(p.evaluation_status ?? p.evaluation_rating) || undefined, instruction_id: str(p.instruction_id) || undefined })

export async function createCompany(payload: CompanyCreatePayload) { const r = await http.post(`/api/projects/${payload.project_id}/companies`, payload); return node(unwrap(r)) }
export async function updateCompany(companyId: string, projectId: string, payload: CompanyUpdatePayload) { const r = await http.put(`/api/projects/${projectId}/companies/${companyId}`, payload); return node(unwrap(r)) }
export async function deleteCompany(companyId: string, projectId: string) { await http.delete(`/api/projects/${projectId}/companies/${companyId}`) }
export async function getCompanyTree(projectId: string, _year?: number) { const r = await http.get(`/api/projects/${projectId}/companies/tree`); const data = unwrap<unknown>(r); return arr(rec(data).nodes ?? data).map(node) }

export async function getConsolScope(projectId: string, year = new Date().getFullYear()) { const r = await http.get('/api/consolidation/scope', { params: { project_id: projectId, year } }); return arr(unwrap(r)).map(scope) }
export async function updateConsolScope(projectId: string, payload: Loose) { const id = str(payload.id); if (!id) return batchUpdateConsolScope(projectId, yr(payload.year as string | number | undefined), [payload]); const r = await http.put(`/api/consolidation/scope/${id}`, payload, { params: { project_id: projectId } }); return scope(unwrap(r)) }
export async function batchUpdateConsolScope(projectId: string, year: number, items: Loose[]) { const r = await http.post('/api/consolidation/scope/batch', { scope_items: items.map(item => ({ ...item, project_id: projectId, year })) }, { params: { project_id: projectId } }); return arr(unwrap(r)).map(scope) }

export async function getConsolTrial(projectId: string, year: number) { return getConsolTrialBalance(projectId, year) }
export async function getConsolTrialBalance(projectId: string, year: number) { const r = await http.get('/api/consolidation/trial', { params: { project_id: projectId, year } }); return arr(unwrap(r)).map(trial) }
export async function updateConsolTrialRow(trialId: string, projectId: string, payload: Loose) { const r = await http.put(`/api/consolidation/trial/${trialId}`, { ...payload, consol_adjustment: payload.consol_adjustment ?? payload.consolidation_adjustment }, { params: { project_id: projectId } }); return trial(unwrap(r)) }
export async function deleteConsolTrialRow(trialId: string, projectId: string) { await http.delete(`/api/consolidation/trial/${trialId}`, { params: { project_id: projectId } }) }
export async function recalcConsolTrial(projectId: string, year: number) { const r = await http.post('/api/consolidation/trial/recalculate', null, { params: { project_id: projectId, year } }); return arr(unwrap(r)).map(trial) }
export async function checkConsolTrialConsistency(projectId: string, year: number): Promise<ConsistencyCheckResult> { const r = await http.get('/api/consolidation/trial/consistency-check', { params: { project_id: projectId, year } }); const d = rec(unwrap(r)); return { is_balanced: bool(d.is_balanced), total_debit: num(d.total_debit), total_credit: num(d.total_credit), difference: num(d.difference), errors: arr<string>(d.errors), warnings: arr<string>(d.warnings) } }
export async function getConsolTrialBalanceFull(projectId: string, filter: ConsolTrialBalanceFilter) { return (await getConsolTrialBalance(projectId, filter.year ?? new Date().getFullYear())).filter(row => !filter.account_category || row.account_category === filter.account_category).map(row => ({ ...row, company_amounts: {}, elimination_details: [] })) }
export async function exportConsolTrialExcel(projectId: string, year: number) { return blobUrl(`/api/consolidation/reports/${projectId}/${year}/workpaper/download`) }

export async function getInternalTrades(projectId: string, year: number) { return getInternalTradeList(projectId, year) }
export async function getInternalTradeList(projectId: string, year: number) { const r = await http.get('/api/consolidation/internal-trade/trades', { params: { project_id: projectId, year } }); return arr(unwrap(r)).map(trade) }
export async function getTransactionMatrix(projectId: string, year: number): Promise<TransactionMatrix> { const r = await http.get('/api/consolidation/internal-trade/matrix', { params: { project_id: projectId, year } }); const d = rec(unwrap(r)); return { company_codes: arr<string>(d.company_codes), matrix: rec(d.matrix) as Record<string, Record<string, number>> } }
export async function generateAutoElimination(_projectId: string, _year: number): Promise<TradeEliminationStatus> { return unsupported('后端未提供内部交易自动生成抵消接口') }
export async function getInternalArApList(projectId: string, year: number) { const r = await http.get('/api/consolidation/internal-trade/ar-ap', { params: { project_id: projectId, year } }); return arr(unwrap(r)).map(arap) }
export async function reconcileAllInternalArAp(projectId: string, year: number) { const rows = await getInternalArApList(projectId, year); const matched = rows.filter(row => Math.abs(row.difference_amount) < 0.005).length; return { total_count: rows.length, matched_count: matched, unmatched_count: rows.length - matched } }
export async function generateArApElimination(_projectId: string, _year: number): Promise<TradeEliminationStatus> { return unsupported('后端未提供内部往来自动生成抵消接口') }

export async function getMinorityInterest(projectId: string, year: number) { return getMinorityInterestRows(projectId, year) }
export async function getMinorityInterestRows(projectId: string, year: number) { const r = await http.get('/api/consolidation/minority-interest', { params: { project_id: projectId, year } }); return arr(unwrap(r)).map(mi) }
export async function createMinorityInterestRow(projectId: string, payload: Loose) { const r = await http.post('/api/consolidation/minority-interest', payload, { params: { project_id: projectId, year: yr(payload.year as string | number | undefined), company_code: str(payload.company_code ?? payload.subsidiary_name) } }); return mi(unwrap(r)) }
export async function updateMinorityInterestRow(miId: string, projectId: string, payload: Loose) { return createMinorityInterestRow(projectId, { ...payload, id: miId }) }
export async function deleteMinorityInterestRow(miId: string, projectId: string) { await http.delete(`/api/consolidation/minority-interest/${miId}`, { params: { project_id: projectId } }) }

export async function getGoodwill(projectId: string, year: number) { return getGoodwillRows(projectId, year) }
export async function getGoodwillRows(projectId: string, year: number) { const r = await http.get('/api/consolidation/goodwill', { params: { project_id: projectId, year } }); return arr(unwrap(r)).map(goodwill) }
export async function createGoodwillRow(projectId: string, payload: Loose) { const r = await http.post('/api/consolidation/goodwill', payload, { params: { project_id: projectId } }); return goodwill(unwrap(r)) }
export async function updateGoodwillRow(goodwillId: string, projectId: string, payload: Loose) { const r = await http.put(`/api/consolidation/goodwill/${goodwillId}`, payload, { params: { project_id: projectId } }); return goodwill(unwrap(r)) }
export async function deleteGoodwillRow(goodwillId: string, projectId: string) { await http.delete(`/api/consolidation/goodwill/${goodwillId}`, { params: { project_id: projectId } }) }

export async function getForex(projectId: string, year: number) { return getForexRows(projectId, year) }
export async function getForexRows(projectId: string, year: number) { const r = await http.get('/api/consolidation/forex', { params: { project_id: projectId, year } }); return arr(unwrap(r)).map(forex) }
export async function createForexRow(projectId: string, payload: Loose) { const r = await http.post('/api/consolidation/forex', { rates: payload.rates, worksheet: payload.worksheet }, { params: { project_id: projectId, company_code: str(payload.company_code ?? payload.entity_name), year: yr(payload.year as string | number | undefined), functional_currency: str(payload.functional_currency ?? payload.currency), reporting_currency: str(payload.reporting_currency) || 'CNY' } }); return forex(unwrap(r)) }
export async function updateForexRow(_forexId: string, projectId: string, payload: Loose) { return createForexRow(projectId, payload) }
export async function deleteForexRow(forexId: string, projectId: string) { await http.delete(`/api/consolidation/forex/${forexId}`, { params: { project_id: projectId } }) }

export async function getComponentAuditors(projectId: string) { const r = await http.get('/api/consolidation/component-auditor/auditors', { params: { project_id: projectId } }); return arr(unwrap(r)).map(auditor) }
export async function createComponentAuditor(projectId: string, payload: Loose) { const r = await http.post('/api/consolidation/component-auditor/auditors', auditorPayload(payload), { params: { project_id: projectId } }); return auditor(unwrap(r)) }
export async function updateComponentAuditor(auditorId: string, projectId: string, payload: Loose) { const r = await http.put(`/api/consolidation/component-auditor/auditors/${auditorId}`, auditorPayload(payload), { params: { project_id: projectId } }); return auditor(unwrap(r)) }
export async function deleteComponentAuditor(auditorId: string, projectId: string) { await http.delete(`/api/consolidation/component-auditor/auditors/${auditorId}`, { params: { project_id: projectId } }) }
export async function getInstructions(projectId: string, componentAuditorId?: string) { const r = await http.get('/api/consolidation/component-auditor/instructions', { params: { project_id: projectId, component_auditor_id: componentAuditorId } }); return arr(unwrap(r)).map(instruction) }
export async function createInstruction(projectId: string, payload: Loose) { const r = await http.post('/api/consolidation/component-auditor/instructions', instructionPayload(payload), { params: { project_id: projectId } }); return instruction(unwrap(r)) }
export async function updateInstruction(instructionId: string, projectId: string, payload: Loose) { const r = await http.put(`/api/consolidation/component-auditor/instructions/${instructionId}`, instructionPayload(payload, true), { params: { project_id: projectId } }); return instruction(unwrap(r)) }
export async function deleteInstruction(instructionId: string, projectId: string) { await http.delete(`/api/consolidation/component-auditor/instructions/${instructionId}`, { params: { project_id: projectId } }) }
export async function getResults(projectId: string, componentAuditorId?: string) { const r = await http.get('/api/consolidation/component-auditor/results', { params: { project_id: projectId, component_auditor_id: componentAuditorId } }); return arr(unwrap(r)).map(result) }
export async function createResult(projectId: string, payload: Loose) { const r = await http.post('/api/consolidation/component-auditor/results', resultPayload(payload), { params: { project_id: projectId } }); return result(unwrap(r)) }
export async function updateResult(resultId: string, projectId: string, payload: Loose) { const r = await http.put(`/api/consolidation/component-auditor/results/${resultId}`, resultPayload(payload), { params: { project_id: projectId } }); return result(unwrap(r)) }
export async function deleteResult(resultId: string, projectId: string) { await http.delete(`/api/consolidation/component-auditor/results/${resultId}`, { params: { project_id: projectId } }) }
export async function getComponentDashboard(projectId: string): Promise<ComponentDashboard> { const r = await http.get('/api/consolidation/component-auditor/dashboard', { params: { project_id: projectId } }); const d = rec(unwrap(r)); return { total_auditors: num(d.total_auditors), pending_instructions: num(d.pending_instructions), pending_results: num(d.pending_results), received_results: num(d.received_results), non_standard_opinions: num(d.non_standard_opinions) } }

export async function getConsolNotes(projectId: string, year: number): Promise<ConsolDisclosureSection[]> { const r = await http.get(`/api/consolidation/notes/${projectId}/${year}`); return arr(unwrap(r)).map(v => ({ section_code: str(rec(v).section_code), rows: arr(rec(v).rows), summary: str(rec(v).summary) })) }
const noteRows = async (projectId: string, period: string | number, sectionCode: string) => (await getConsolNotes(projectId, yr(period))).find(section => section.section_code === sectionCode)?.rows ?? []
export async function getConsolScopeNotes(projectId: string, period: string | number) { return (await noteRows(projectId, period, 'consol_scope')).map((row, i) => ({ seq: i + 1, company_name: str(rec(row)['公司名称']), shareholding: pct(rec(row)['持股比例']), voting_rights: pct(rec(row)['持股比例']), is_included: str(rec(row)['是否纳入']) === '是', inclusion_date: str(rec(row)['纳入日期']), exit_date: str(rec(row)['退出日期']), notes: str(rec(row)['排除原因'] ?? rec(row)['纳入原因']) })) }
export async function getSubsidiaryNotes(projectId: string, period: string | number) { return (await noteRows(projectId, period, 'important_subsidiaries')).map(row => ({ company_name: str(rec(row)['公司名称']), registration_place: str(rec(row)['注册地']), business_nature: str(rec(row)['业务性质']), registered_capital: rec(row)['注册资本'] ?? 0, paid_capital: 0, shareholding: pct(rec(row)['母公司持股比例']), minority_equity_end: 0 })) }
export async function getGoodwillNotes(projectId: string, period: string | number) { return (await noteRows(projectId, period, 'goodwill')).map(row => ({ acquiree: str(rec(row)['被投资单位']), opening_balance: num(rec(row)['初始确认金额']), current_increase: num(rec(row)['本期增加']), current_decrease: num(rec(row)['本期减少']), current_impairment: num(rec(row)['累计减值']), closing_balance: num(rec(row)['期末账面价值']) })) }
export async function getMinorityInterestNotes(projectId: string, period: string | number) { return (await noteRows(projectId, period, 'minority_interest')).map(row => { const closing = num(rec(row)['期末少数股东权益']); const profit = num(rec(row)['本期少数股东损益']); return { subsidiary_name: str(rec(row)['子公司']), opening_balance: closing - profit, share_of_profit: profit, share_of_loss: 0, dividends_paid: 0, other_changes: 0, closing_balance: closing } }) }
export async function getInternalTradeNotes(projectId: string, period: string | number) { const rows = await noteRows(projectId, period, 'internal_trade_elimination'); return { trades: rows.filter(row => str(rec(row)['类型']) === '内部交易').map(row => ({ trade_type: str(rec(row)['交易类型']), trade_amount: num(rec(row)['交易金额']), elimination_amount: num(rec(row)['未实现利润']) })), arap: rows.filter(row => str(rec(row)['类型']) === '内部往来').map(row => ({ arap_type: str(rec(row)['交易类型']), debit_balance: num(rec(row)['交易金额']), credit_balance: 0, after_elimination: 0 })) } }
export async function getForexTranslationNotes(projectId: string, period: string | number) { return (await noteRows(projectId, period, 'forex_translation')).map(row => ({ currency: str(rec(row)['功能货币']), statement_rate: rec(row)['资产负债表期末汇率'] ?? '—', income_expense_avg_rate: rec(row)['利润表平均汇率'] ?? '—', translation_diff: num(rec(row)['汇率变动影响']) })) }
export async function saveConsolNotes(projectId: string, period: string | number, _payload: Loose) { const year = yr(period); const r = await http.post(`/api/consolidation/notes/${projectId}/${year}/save`); return unwrap(r) }
export async function downloadConsolNotesExcel(_projectId: string, _period: string | number): Promise<string> { return unsupported('后端未提供合并附注 Excel 导出接口') }
export async function downloadConsolNotesPDF(_projectId: string, _period: string | number): Promise<string> { return unsupported('后端未提供合并附注 PDF 导出接口') }

export async function getConsolReport(projectId: string, reportType: ReportType, period: string): Promise<ConsolReportData> { const year = yr(period); const r = await http.get(`/api/consolidation/reports/${projectId}/${year}`, { params: { report_type: reportType } }); return { report_type: reportType, period, rows: arr(unwrap(r)).map(reportRow) } }
export async function getConsolReports(projectId: string, year: number) { return (await getConsolReport(projectId, 'balance_sheet', `${year}-12`)).rows }
export async function saveConsolReport(_projectId: string, _reportType: ReportType, _period: string, _payload: Loose): Promise<ConsolReportData> { return unsupported('后端未提供合并报表保存接口') }
export async function downloadConsolReportExcel(projectId: string, reportType: ReportType, period: string) { return reportType === 'cash_flow' ? unsupported('后端未提供该报表导出接口') : blobUrl(`/api/consolidation/reports/${projectId}/${yr(period)}/workpaper/download`) }
export async function downloadConsolReportPDF(_projectId: string, _reportType: ReportType, _period: string): Promise<string> { return unsupported('后端未提供合并报表 PDF 导出接口') }
export async function getYoYAnalysis(projectId: string, reportType: ReportType, period: string): Promise<YoYAnalysis[]> { return (await getConsolReport(projectId, reportType, period)).rows.map(row => { const change = row.current_period_amount - row.prior_period_amount; return { account_name: row.account_name, current_amount: row.current_period_amount, prior_amount: row.prior_period_amount, change, change_pct: row.prior_period_amount === 0 ? 0 : Number(((change / row.prior_period_amount) * 100).toFixed(2)) } }) }

export async function getEliminationEntries(projectId: string, filter: EliminationListFilter = {}) { const r = await http.get('/api/consolidation/eliminations', { params: { project_id: projectId, year: filter.year, entry_type: filter.entry_type ? toBackType(filter.entry_type) : undefined, review_status: filter.review_status } }); return arr(unwrap(r)).map(entry) }
export async function createEliminationEntry(projectId: string, payload: EliminationEntryCreatePayload) { const r = await http.post('/api/consolidation/eliminations', { ...payload, year: yr(payload.year), entry_type: toBackType(payload.entry_type), lines: payload.lines.map(line => ({ ...line, debit_amount: line.debit_amount ?? (line.direction === 'debit' ? num(line.amount) : 0), credit_amount: line.credit_amount ?? (line.direction === 'credit' ? num(line.amount) : 0) })) }, { params: { project_id: projectId } }); return entry(unwrap(r)) }
export async function updateEliminationEntry(entryId: string, projectId: string, payload: EliminationEntryUpdatePayload) { const r = await http.put(`/api/consolidation/eliminations/${entryId}`, { ...payload, year: payload.year == null ? undefined : yr(payload.year), entry_type: payload.entry_type ? toBackType(payload.entry_type) : undefined, lines: payload.lines?.map(line => ({ ...line, debit_amount: line.debit_amount ?? (line.direction === 'debit' ? num(line.amount) : 0), credit_amount: line.credit_amount ?? (line.direction === 'credit' ? num(line.amount) : 0) })) }, { params: { project_id: projectId } }); return entry(unwrap(r)) }
export async function deleteEliminationEntry(entryId: string, projectId: string) { await http.delete(`/api/consolidation/eliminations/${entryId}`, { params: { project_id: projectId } }) }
export async function approveEliminationEntry(entryId: string, projectId: string) { const r = await http.post(`/api/consolidation/eliminations/${entryId}/review`, reviewPayload('approve'), { params: { project_id: projectId } }); return entry(unwrap(r)) }
export async function rejectEliminationEntry(entryId: string, projectId: string, reason: string) { const r = await http.post(`/api/consolidation/eliminations/${entryId}/review`, reviewPayload('reject', reason), { params: { project_id: projectId } }); return entry(unwrap(r)) }
export async function carryForwardElimination(_entryId: string, _projectId: string, _targetYear: number) { return unsupported('后端未提供抵消分录结转接口') }
export async function batchApproveEliminationEntries(projectId: string, ids: string[]) { return Promise.all(ids.map(id => approveEliminationEntry(id, projectId))) }
export async function batchRejectEliminationEntries(projectId: string, ids: string[], reason: string) { return Promise.all(ids.map(id => rejectEliminationEntry(id, projectId, reason))) }
export async function getEliminationSummary(projectId: string, year: number): Promise<EliminationSummary> { const r = await http.get('/api/consolidation/eliminations/summary/year', { params: { project_id: projectId, year } }); const rows = arr<Loose>(unwrap(r)).map(item => ({ entry_type: toFrontType(item.entry_type), count: num(item.count), total_debit: num(item.total_debit), total_credit: num(item.total_credit) })); return { total_debit: rows.reduce((s, item) => s + item.total_debit, 0), total_credit: rows.reduce((s, item) => s + item.total_credit, 0), total_count: rows.reduce((s, item) => s + item.count, 0), by_type: rows } }
