"""Generate dSheetLabels.ts from global_catalog.json (D-cycle sheet labels).

读取 catalog 中所有 cycle=D 的 sheet 条目，提取 sheet_code → sheet_name 映射，
生成 TypeScript 文件供前端 SDK 使用。

Usage:
    python backend/scripts/acnr/generate_sheet_labels.py

Output:
    audit-platform/frontend/src/generated/dSheetLabels.ts

Requirements: 3.2, 18.1
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# 路径设置
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
_CATALOG_PATH = _REPO_ROOT / "backend" / "data" / "acnr" / "global_catalog.json"
_OUTPUT_PATH = (
    _REPO_ROOT
    / "audit-platform"
    / "frontend"
    / "src"
    / "generated"
    / "dSheetLabels.ts"
)


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------


def load_d_cycle_sheets(catalog_path: Path) -> list[dict]:
    """从 catalog 读取 D-cycle sheet 条目，按 sheet_code 排序返回。"""
    with open(catalog_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    sheets = [s for s in data.get("sheets", []) if s.get("cycle") == "D"]
    # 按自然排序：先按 parent_wp_code 字母+数字，再按 sheet_code
    sheets.sort(key=lambda s: (s.get("parent_wp_code", ""), s.get("sheet_code", "")))
    return sheets


def generate_ts_content(sheets: list[dict]) -> str:
    """生成 TypeScript 文件内容。"""
    lines: list[str] = []

    # 文件头
    lines.append("/**")
    lines.append(" * D-Cycle Sheet Labels — 自动生成，禁手改")
    lines.append(" *")
    lines.append(" * Generated by: backend/scripts/acnr/generate_sheet_labels.py")
    lines.append(" * Source: backend/data/acnr/global_catalog.json")
    lines.append(" *")
    lines.append(" * @generated DO NOT EDIT")
    lines.append(" */")
    lines.append("")
    lines.append("export const D_SHEET_LABELS: Record<string, string> = {")

    # 条目
    for sheet in sheets:
        code = sheet["sheet_code"]
        name = sheet["sheet_name"]
        # 转义单引号
        escaped_code = code.replace("'", "\\'")
        escaped_name = name.replace("'", "\\'")
        lines.append(f"  '{escaped_code}': '{escaped_name}',")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    """生成 dSheetLabels.ts。"""
    if not _CATALOG_PATH.exists():
        print(
            f"[generate_sheet_labels] ERROR: {_CATALOG_PATH} 不存在。",
            file=sys.stderr,
        )
        return 1

    sheets = load_d_cycle_sheets(_CATALOG_PATH)
    if not sheets:
        print(
            "[generate_sheet_labels] ERROR: catalog 中无 D-cycle sheet 条目。",
            file=sys.stderr,
        )
        return 1

    content = generate_ts_content(sheets)

    # 确保输出目录存在
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(content, encoding="utf-8")

    print(
        f"[generate_sheet_labels] OK — 生成 {len(sheets)} 条 D-cycle labels → {_OUTPUT_PATH.relative_to(_REPO_ROOT)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
