#!/usr/bin/env python
"""
规模快照脚本：统计平台后端/前端模块数量，输出 JSON 或 Markdown 表。

用法（从仓库根目录运行）：
    python backend/scripts/analyze/snapshot_scale.py          # JSON 输出到 stdout
    python backend/scripts/analyze/snapshot_scale.py --markdown  # Markdown 表输出到 stdout
    python backend/scripts/analyze/snapshot_scale.py --write     # 写入 docs/architecture/scale-snapshot.md

Property 1: 同一提交重复运行输出一致（确定性排序，不含时间戳比对）。
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def _count_py_files(directory: Path, *, exclude_init: bool = True) -> int:
    """统计目录下 .py 文件数量（不递归），可排除 __init__.py。"""
    if not directory.exists():
        return 0
    count = 0
    for f in sorted(directory.iterdir()):
        if f.is_file() and f.suffix == ".py":
            if exclude_init and f.name == "__init__.py":
                continue
            count += 1
    return count


def _count_files_recursive(directory: Path, pattern: str) -> int:
    """递归统计匹配 pattern 的文件数量。"""
    if not directory.exists():
        return 0
    return len(sorted(directory.rglob(pattern)))


def _count_composables(directory: Path) -> int:
    """统计 composables 目录下 .ts 文件数量（不递归，排除 __tests__ 子目录内容）。"""
    if not directory.exists():
        return 0
    count = 0
    for f in sorted(directory.iterdir()):
        if f.is_file() and f.suffix == ".ts":
            count += 1
    return count


def collect_metrics(repo_root: Path) -> dict:
    """收集所有模块计数指标。

    返回结构确定性排序，不含时间戳依赖（时间戳单独附加供显示用）。
    """
    backend = repo_root / "backend"
    frontend = repo_root / "audit-platform" / "frontend" / "src"

    # Backend counts
    routers = _count_py_files(backend / "app" / "routers")
    services = _count_py_files(backend / "app" / "services")
    models = _count_py_files(backend / "app" / "models")

    # Migrations: V*.sql files only
    migrations_dir = backend / "migrations"
    migrations = 0
    if migrations_dir.exists():
        migrations = len([
            f for f in sorted(migrations_dir.iterdir())
            if f.is_file() and f.name.startswith("V") and f.suffix == ".sql"
        ])

    # Tests: test_*.py recursively
    tests = _count_files_recursive(backend / "tests", "test_*.py")

    # Frontend counts
    views = _count_files_recursive(frontend / "views", "*.vue")
    components = _count_files_recursive(frontend / "components", "*.vue")
    composables = _count_composables(frontend / "composables")

    return {
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "backend": {
            "routers": routers,
            "services": services,
            "models": models,
            "migrations": migrations,
            "tests": tests,
        },
        "frontend": {
            "views": views,
            "components": components,
            "composables": composables,
        },
    }


def format_json(metrics: dict) -> str:
    """将指标格式化为 JSON 字符串（确定性排序）。"""
    return json.dumps(metrics, indent=2, ensure_ascii=False, sort_keys=False)


def format_markdown(metrics: dict) -> str:
    """将指标格式化为 Markdown 文档。

    包含自动生成标记，告知读者不要手动编辑。
    """
    lines = [
        "<!-- AUTO-GENERATED by backend/scripts/analyze/snapshot_scale.py — DO NOT EDIT MANUALLY -->",
        "",
        "# 平台规模快照",
        "",
        f"> 自动生成时间：{metrics['timestamp']}",
        ">",
        "> 运行 `python backend/scripts/analyze/snapshot_scale.py --write` 更新本文件。",
        "",
        "## 后端",
        "",
        "| 模块 | 数量 |",
        "|------|------|",
        f"| Routers | {metrics['backend']['routers']} |",
        f"| Services | {metrics['backend']['services']} |",
        f"| Models | {metrics['backend']['models']} |",
        f"| Migrations | {metrics['backend']['migrations']} |",
        f"| Tests | {metrics['backend']['tests']} |",
        "",
        "## 前端",
        "",
        "| 模块 | 数量 |",
        "|------|------|",
        f"| Views | {metrics['frontend']['views']} |",
        f"| Components | {metrics['frontend']['components']} |",
        f"| Composables | {metrics['frontend']['composables']} |",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="平台规模快照统计")
    parser.add_argument("--markdown", action="store_true", help="输出 Markdown 表格")
    parser.add_argument("--write", action="store_true",
                        help="写入 docs/architecture/scale-snapshot.md")
    parser.add_argument("--repo-root", type=Path, default=None,
                        help="仓库根目录（默认从脚本位置推断）")
    args = parser.parse_args()

    # 确定仓库根目录
    if args.repo_root:
        repo_root = args.repo_root.resolve()
    else:
        script_dir = Path(__file__).resolve().parent
        repo_root = script_dir.parent.parent.parent

    metrics = collect_metrics(repo_root)

    if args.write:
        output_path = repo_root / "docs" / "architecture" / "scale-snapshot.md"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        content = format_markdown(metrics)
        output_path.write_text(content, encoding="utf-8")
        print(f"已写入 {output_path.relative_to(repo_root)}")
        # 同时输出 JSON 到 stdout 供程序化消费
        print(format_json(metrics))
        return

    if args.markdown:
        print(format_markdown(metrics))
    else:
        print(format_json(metrics))


if __name__ == "__main__":
    main()
