"""G9 其他非流动金融资产 — 导入导出（G9-2~6 + 附注上市/国企 × 3 端点）."""

from __future__ import annotations

from ._cycle_import_export_common import create_cycle_import_export_router

_G9_2_HEADERS = [
    "序号", "资产名称", "分类", "工具种类", "指定FVTPL", "初始投资日", "到期日", "持有数量", "面值成本", "计量属性", "关联方",
    "期初余额", "期初调整", "本期增加", "本期减少", "公允价值变动", "利息收入", "减值损失", "OCI变动",
    "期末余额", "期末调整", "审定数", "公允价值层次", "估值方法", "发函情况", "OCI累计", "减值准备", "备注",
]
_G9_2_KEYS = [
    "seq", "assetName", "classification", "instrumentType", "isDesignated", "initialInvestDate", "maturityDate",
    "holdingQuantity", "faceValueOrCost", "measurementAttribute", "isRelatedParty",
    "openingBalance", "openingAdjustment", "increaseAmount", "decreaseAmount",
    "fvChangeAmount", "interestIncome", "impairmentLoss", "ociChange",
    "closingBalance", "closingAdjustment", "closingAdjusted", "fairValueLevel",
    "valuationMethod", "confirmationStatus", "ociCumulative", "impairmentProvision", "remark",
]

_G9_3_HEADERS = [
    "序号", "分录类型", "日期", "摘要", "科目代码", "科目名称", "借方", "贷方", "编制人", "备注",
]
_G9_3_KEYS = [
    "seq", "entryType", "date", "summary", "accountCode", "accountName",
    "debitAmount", "creditAmount", "preparedBy", "remark",
]

_G9_4_HEADERS = [
    "序号", "资产名称", "投资日",
    "未审数量", "未审单价", "未审公允价值",
    "审定数量", "审定单价", "审定公允价值", "差异", "差异原因",
    "公允价值层次", "估值方法", "与上期一致",
    "估值技术", "不可观察输入值", "输入值", "估值来源", "输入值来源",
    "非流动性折扣", "估值文件索引",
]
_G9_4_KEYS = [
    "seq", "assetName", "initialInvestDate",
    "closingUnadjustedQty", "closingUnadjustedPrice", "closingUnadjustedFV",
    "closingAuditedQty", "closingAuditedPrice", "closingAuditedFV", "fairValueDiff", "diffReason",
    "fairValueLevel", "valuationMethod", "methodConsistentWithPrior",
    "valuationTechnique", "unobservableInputDesc", "unobservableInputValue",
    "valuationSource", "inputSourceAndAdjustment",
    "nonLiquidityDiscount", "valuationDocIndex",
]

_G9_5_HEADERS = [
    "序号", "资产名称", "期初公允价值", "本期购入", "本期处置", "转入第三层次", "转出第三层次",
    "公允价值变动损益", "公允价值变动OCI", "利息收入", "减值损失", "其他变动",
    "期末公允价值", "仍持有未实现", "企业报告期末", "差异", "备注",
]
_G9_5_KEYS = [
    "seq", "assetName", "openingFairValue", "purchaseAmount", "disposalAmount",
    "transferIn", "transferOut", "fvChangePL", "fvChangeOCI", "interestIncome",
    "impairmentLoss", "otherChanges", "closingFairValue", "unrealizedHeld",
    "reportedClosing", "variance", "remark",
]

_G9_6_HEADERS = [
    "序号", "日期", "凭证编号", "业务内容", "对方科目", "资产名称", "借方", "贷方", "来源",
    "支持性文件", "原始凭证", "授权批准", "账务处理", "分类正确", "公允价值", "减值计提",
    "是否异常", "强制异常", "异常类型", "异常说明", "风险等级", "处理建议", "索引", "备注",
]
_G9_6_KEYS = [
    "seq", "voucherDate", "voucherNo", "businessContent", "counterAccount", "assetName",
    "debitAmount", "creditAmount", "source",
    "supportDoc", "checkOriginal", "checkAuthorized", "checkAccounting", "checkClassification",
    "checkFairValue", "checkImpairment",
    "isAbnormal", "forceAbnormal", "abnormalType", "abnormalDesc", "riskLevel", "suggestion",
    "indexRef", "remark",
]

# CAS 39 / 纸质 Excel G9-5 列名 → 十因子电子稿规范列名
_G9_5_HEADER_ALIASES = {
    "资产名称": [
        "投资项目",
        "投资项目【按明细项目列示（如：证券名称或投资单位名称）】",
    ],
    "期初公允价值": ["期初余额"],
    "本期购入": ["购买", "购入"],
    "本期处置": ["出售"],
    "转入第三层次": ["转入"],
    "转出第三层次": ["转出"],
    "公允价值变动损益": ["公允价值变动"],
    "利息收入": ["投资收益"],
    "其他变动": ["发行", "结算", "其他"],
    "期末公允价值": ["期末余额"],
    "仍持有未实现": [
        "仍持有未实现损益变动",
        "对于在报告期末持有的资产，计入损益的当期未实现利得或损失的变动",
    ],
    "企业报告期末": ["企业期末", "报告期末"],
}

_G9_DISC_HEADERS = ["行键", "项目", "期末金额", "期初金额", "附注文本"]
_G9_DISC_KEYS = ["rowKey", "label", "currentAmount", "priorAmount", "noteText"]
_G9_DISC_KEEP = ["currentAmount", "priorAmount", "noteText"]
_G9_DISC_ALIASES = {
    "项目": ["种类", "种  类", "项  目", "项目名称"],
    "期末金额": ["期末余额", "期末公允价值", "本期"],
    "期初金额": ["上年年末余额", "期初公允价值", "上期", "期初余额"],
    "行键": ["rowKey", "row_key", "键"],
    "附注文本": ["附注", "说明", "备注"],
}
_G9_DISC_LISTED_PREFILL = [
    ["listed_1", "债务工具投资", 0, 0, ""],
    ["listed_2", "权益工具投资", 0, 0, ""],
    ["listed_3", "指定为以公允价值计量且其变动计入当期损益的金融资产", 0, 0, ""],
    ["listed_4", "其他", 0, 0, ""],
]
_G9_DISC_SOE_PREFILL = [
    ["soe_1", "债务工具投资", 0, 0, ""],
    ["soe_2", "权益工具投资", 0, 0, ""],
    ["soe_3", "指定为以公允价值计量且其变动计入当期损益的金融资产", 0, 0, ""],
    ["soe_4", "其他", 0, 0, ""],
]
_G9_DISC_GUIDANCE_COMMON = [
    "附注披露编制说明",
    "",
    "结构对齐 Excel：四类（债务/权益/指定FVTPL/其他）+ 合计（合计由页面公式汇总，勿导入合计行）。",
    "行键须保留（listed_* / soe_*）；金额列可与底稿「期末余额/上年年末余额」或「期末公允价值/期初公允价值」别名对应。",
    "建议先在 G9-2 填工具种类与指定，再在附注页「分项带入」；也可本表手工/导入金额。",
    "期末合计应与 G9-1 审定（1504）勾稽；有 Level3 时应在附注汇总说明层次与调节过程。",
]

_G9_SPECS = {
    "G9-2": {
        "item_id": "G9-detail-rows",
        "title": "G9-2 明细表",
        "headers": _G9_2_HEADERS,
        "field_keys": _G9_2_KEYS,
        "allow_missing_headers": True,
        "guidance": [
            "G9-2 其他非流动金融资产明细表 编制说明",
            "",
            "一、本表目的",
            "按资产逐笔列示其他非流动金融资产（科目1504）的明细情况，反映持有期间的计量变动，",
            "核对分类（FVTPL/FVOCI/AC）、初始投资及期末审定余额，与 G9-1 审定表勾稽。",
            "",
            "二、填写要求",
            "1. 「资产名称」列：填写金融资产全称（如：XX股权投资/XX信托计划/XX基金等）。",
            "2. 「分类」列：填写 FVTPL / FVOCI / AC，与初始指定及后续重分类一致。",
            "3. 「工具种类」列：债务工具 / 权益工具 / 衍生工具 / 其他。供附注分项带入。",
            "4. 「指定FVTPL」列：填 是/否，标记是否管理层主动指定（非默认分类）。",
            "5. 「期初余额~OCI变动」列：填写本期各项变动金额（可从序时账按科目取数）。",
            "6. 「公允价值层次」列：L1（活跃市场报价）/ L2（可观察输入值）/ L3（不可观察输入值）。",
            "7. 「估值方法」列：L2/L3 必填（如市场法/收益法/成本法）。",
            "8. 「关联方」列：标注是否为关联方投资，影响披露范围。",
            "",
            "三、自动计算列说明（灰底，导入时忽略）",
            "期末余额 = 期初审定 + 增加 − 减少 + FV变动 + 利息收入 − 减值损失 + OCI变动",
            "审定数 = 期末余额 + 期末调整",
            "各分类小计自动汇总到 G9-1 对应行（FVTPL→fvtpl_1 / FVOCI→fvoci_1 / AC→ac_1）。",
            "",
            "四、审计关注",
            "1. 分类是否与初始确认时的业务模式测试+SPPI测试结论一致。",
            "2. 指定 FVTPL 是否满足 CAS22 消除或显著减少计量不一致的条件。",
            "3. 公允价值层次划分是否恰当（权益工具无活跃报价不能 L1）。",
            "4. L3 估值方法及不可观察输入值是否有外部支持（评估报告/同行业交易）。",
            "5. 期末合计与 G9-1 审定表是否勾稽一致，差异须追溯至具体调整分录。",
            "6. 关联方投资是否在附注中单独披露并评估公允性。",
            "",
            "五、数据来源",
            "从 TB 辅助核算（tb_balance 科目 1504% + 辅助维度）按投资对象取数。",
            "或从资产管理系统/证券交易系统导出后按本模板整理。",
            "公允价值可参照 Wind/Bloomberg 报价、评估报告或管理层提供的估值文件。",
        ],
    },
    "G9-3": {
        "item_id": "G9-adjustment-rows",
        "title": "G9-3 调整分录",
        "headers": _G9_3_HEADERS,
        "field_keys": _G9_3_KEYS,
        "guidance": [
            "G9-3 调整分录汇总表 编制说明",
            "",
            "一、本表目的",
            "汇总本科目（1504 其他非流动金融资产）相关的审计调整分录（AJE）和重分类调整分录（RJE），",
            "确保调整依据充分、借贷平衡，并正确回写至 G9-1 审定表。",
            "",
            "二、填写要求",
            "1. 「分录类型」列：AJE（账项调整）/ RJE（重分类调整）。",
            "2. 「日期」列：调整涉及的业务日期或资产负债表日。",
            "3. 「科目代码/名称」列：填写涉及的会计科目（如 1504/6101/4002 等）。",
            "4. 「借方/贷方」列：金额填写，同一笔分录借贷合计须平衡。",
            "5. 「编制人」列：编制该调整分录的审计团队人员。",
            "",
            "三、审计关注",
            "1. FVTPL 调整对手科目通常为 6101（公允价值变动损益）。",
            "2. FVOCI 调整对手科目通常为 4002（其他综合收益）。",
            "3. 整表借方合计须等于贷方合计（表内平衡）。",
            "4. AJE 须有合伙人审批，RJE 须标注重分类依据。",
            "5. 调整净额须与 G9-1 审定表的「调整」列一致。",
            "",
            "四、数据来源",
            "可从 G9-4 公允价值差异自动推送生成；或手工编制后推送至中央调整分录模块（A13）。",
        ],
    },
    "G9-4": {
        "item_id": "G9-fv-test-rows",
        "title": "G9-4 公允价值测试",
        "headers": _G9_4_HEADERS,
        "field_keys": _G9_4_KEYS,
        "allow_missing_headers": True,
        "guidance": [
            "G9-4 公允价值测试表 编制说明",
            "",
            "一、本表目的",
            "逐笔验证其他非流动金融资产期末公允价值计量的恰当性，评估公允价值层次划分、",
            "估值技术及不可观察输入值的合理性。差异超阈值时生成调整分录。",
            "",
            "二、填写要求",
            "1. 「未审数量/单价/公允价值」列：填写被审计单位账面记录的期末估值。",
            "2. 「审定数量/单价/公允价值」列：填写审计师独立复核后确认的公允价值。",
            "3. 「公允价值层次」列：L1 / L2 / L3，须与 G9-2 明细表一致。",
            "4. 「估值方法」列：L1 不需填（市场报价）；L2/L3 必填（如收益法DCF/市场法/NAV法等）。",
            "5. 「估值技术/不可观察输入值」列：L3 必填，描述估值模型及关键假设。",
            "6. 「非流动性折扣」列：如适用，填写折扣比例及依据。",
            "7. 「估值文件索引」列：关联评估报告或估值备忘录的底稿索引。",
            "",
            "三、自动计算列说明（灰底，导入时忽略）",
            "差异 = 审定公允价值 − 未审公允价值",
            "|差异| > 0.01 时自动标黄，须填写「差异原因」。",
            "",
            "四、审计关注",
            "1. 同一资产 L 层次在前后期间是否变动，变动是否有依据。",
            "2. L3 不可观察输入值的敏感性分析是否充分。",
            "3. 估值来源是否独立于管理层（独立第三方评估 vs 管理层自估）。",
            "4. 非流动性折扣是否有市场证据支持。",
            "5. 公允差异超重要性水平时须推送至 G9-3 生成 AJE。",
            "",
            "五、工作流程",
            "G9-2 明细带入 → 本表填写未审/审定 → 对比差异 → 回写 G9-2 审定 →",
            "差异超标推送 G9-3 → L3 资产带入 G9-5 调节表 → 回填 G9A 程序表 seq8。",
        ],
    },
    "G9-5": {
        "item_id": "G9-l3-rows",
        "title": "G9-5 第三层次调节表",
        "headers": _G9_5_HEADERS,
        "field_keys": _G9_5_KEYS,
        "allow_missing_headers": True,
        "header_aliases": _G9_5_HEADER_ALIASES,
        "guidance": [
            "G9-5 第三层次公允价值调节表 编制说明",
            "",
            "一、本表目的",
            "按 CAS 39 / IFRS 13 要求，对第三层次（L3）金融资产编制期初至期末的十因子变动调节表，",
            "验证各因子变动完整准确，公式期末与企业报告勾稽，为附注披露提供数据基础。",
            "",
            "二、填写要求",
            "1. 「资产名称」列：逐笔列示 L3 资产名称（与 G9-2 一致）。",
            "2. 十因子列（期初~其他变动）：逐笔填写期间内各类变动金额。",
            "3. 「仍持有未实现」列：报告期末仍持有资产计入损益的当期未实现利得或损失变动",
            "   （CAS 39 第74条要求披露，不参与期末公式计算）。",
            "4. 「企业报告期末」列：填写企业财务报表中列示的 L3 期末金额（用于勾稽）。",
            "",
            "三、自动计算列说明（灰底，导入时忽略）",
            "公式期末 = 期初 + 购入 − 处置 + 转入 − 转出 + FV(损益) + FV(OCI) + 利息 − 减值 + 其他",
            "差异 = 公式期末 − 企业报告期末（差异 > 0.01 标黄须说明）",
            "",
            "四、审计关注",
            "1. FV(损益) 与 FV(OCI) 须严格区分——FVTPL 走损益，FVOCI 走 OCI，不得混淆。",
            "2. 转入/转出须注明从哪个层次转入/转出及转换原因。",
            "3. 公式期末与企业报告不一致时，须追溯是哪个因子有遗漏或多计。",
            "4. 期末余额应与 G9-4 审定公允价值 / G9-2 明细表 L3 资产期末勾稽。",
            "5. 附注中须完整披露本表内容（上市/国企均要求 L3 调节表）。",
            "",
            "五、兼容性说明",
            "支持导入纸质 CAS 39 格式 Excel（旧列名自动映射）：",
            "- 「投资项目」→ 资产名称",
            "- 「期初余额」→ 期初公允价值",
            "- 「购买/出售」→ 本期购入/处置",
            "- 「投资收益」→ 利息收入",
            "- 「仍持有未实现损益变动」→ 仍持有未实现",
        ],
    },
    "G9-6": {
        "item_id": "G9-voucher-rows",
        "title": "G9-6 凭证检查",
        "headers": _G9_6_HEADERS,
        "field_keys": _G9_6_KEYS,
        "guidance": [
            "G9-6 凭证检查表 编制说明",
            "",
            "一、本表目的",
            "对其他非流动金融资产（科目1504）的重要交易凭证进行抽样检查，",
            "验证入账金额、分类、公允价值计量及减值计提的准确性和合规性。",
            "",
            "二、填写要求",
            "1. 「日期/凭证编号」列：填写记账凭证的日期和编号。",
            "2. 「业务内容」列：简述交易内容（如：购入XX信托/处置XX股权/FV调整等）。",
            "3. 「对方科目」列：填写借贷对方科目名称。",
            "4. 「资产名称」列：关联 G9-2 明细中的具体投资名称。",
            "5. 六项核对（支持性文件~减值计提）：每项填 通过/不通过/未测。",
            "6. 「是否异常」列：系统根据核对结果自动判定（任一「不通过」即标异常）。",
            "7. 「强制异常」列：手工标注截止跨期或其他特殊异常。",
            "8. 「异常类型/说明」列：异常时必填，描述问题性质和涉及金额。",
            "",
            "三、核对项说明",
            "- 支持性文件：是否取得投资协议/交割单/持仓报告等原始凭证。",
            "- 原始凭证：凭证附件是否齐全、金额是否一致。",
            "- 授权批准：大额投资是否经董事会/投资委员会审批。",
            "- 账务处理：借贷科目、金额、方向是否正确。",
            "- 分类正确：FVTPL/FVOCI/AC 分类是否与业务模式+SPPI 一致。",
            "- 公允价值：入账/变动的公允价值是否有估值支持。",
            "- 减值计提：AC/FVOCI 是否按 ECL 模型计提（FVTPL 不适用减值）。",
            "",
            "四、审计关注",
            "1. 大额购入/处置是否有完整的投资决策审批链。",
            "2. 期末集中购入（尤其12月）是否存在跨期。",
            "3. 关联方交易凭证是否有独立公允性证据。",
            "4. 异常标注的交易须逐笔追踪至审计说明/A13 错报汇总。",
            "",
            "五、抽样说明",
            "借方（本期购入/FV 正向变动）和贷方（处置/FV 负向变动/减值）分别计算检查比例。",
            "可通过抽凭引擎（account-code=1504）系统抽样，高值必选项 MUS 间隔计算。",
        ],
    },
    "附注上市": {
        "item_id": "G9-disclosure-listed",
        "title": "附注披露信息（上市公司）",
        "headers": _G9_DISC_HEADERS,
        "field_keys": _G9_DISC_KEYS,
        "keyed_by": "rowKey",
        "keep_keys": _G9_DISC_KEEP,
        "allow_missing_headers": True,
        "header_aliases": _G9_DISC_ALIASES,
        "template_prefill": _G9_DISC_LISTED_PREFILL,
        "guidance": _G9_DISC_GUIDANCE_COMMON + [
            "上市公司表头口径：种类 / 期末余额 / 上年年末余额。",
        ],
    },
    "附注国企": {
        "item_id": "G9-disclosure-soe",
        "title": "附注披露信息（国企）",
        "headers": _G9_DISC_HEADERS,
        "field_keys": _G9_DISC_KEYS,
        "keyed_by": "rowKey",
        "keep_keys": _G9_DISC_KEEP,
        "allow_missing_headers": True,
        "header_aliases": _G9_DISC_ALIASES,
        "template_prefill": _G9_DISC_SOE_PREFILL,
        "guidance": _G9_DISC_GUIDANCE_COMMON + [
            "国企表头口径：项目 / 期末公允价值 / 期初公允价值。",
        ],
    },
}

router = create_cycle_import_export_router(
    tag="g9-import-export",
    api_prefix="g9",
    specs=_G9_SPECS,
    storage_field="remark",
)
