import { defineAsyncComponent } from 'vue'
import type { HtmlRendererEntry } from '../types'

/**
 * Explicit HtmlRendererEntry[] for domain: confirmations
 * Membership is this array — no startsWith classifier.
 */
export const confirmationsEntries: HtmlRendererEntry[] = [
  {
    componentType: 'confirmation-summary',
    component: defineAsyncComponent(() => import('../../confirmation/GtConfirmationSummary.vue')),
    icon: '✉️',
    label: '函证结果汇总表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-entity-verify',
    component: defineAsyncComponent(() => import('../../confirmation/entityVerify/GtConfirmationEntityVerify.vue')),
    icon: '🔍',
    label: '核实被函证单位信息',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-followup',
    component: defineAsyncComponent(() => import('../../confirmation/followup/GtConfirmationFollowup.vue')),
    icon: '📋',
    label: '跟函过程控制',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-diff-reconcile',
    component: defineAsyncComponent(() => import('../../confirmation/diffReconcile/GtConfirmationDiffReconcile.vue')),
    icon: '⚖️',
    label: '函证差异调节表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-alternative-d05',
    component: defineAsyncComponent(() => import('../../confirmation/alternativeD05/GtConfirmationAlternativeD05.vue')),
    icon: '🔄',
    label: '替代程序(合同负债及销售)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-alternative-d06',
    component: defineAsyncComponent(() => import('../../confirmation/alternativeD06/GtConfirmationAlternativeD06.vue')),
    icon: '🔄',
    label: '替代程序(应收及销售)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-diff-checklist',
    component: defineAsyncComponent(() => import('../../confirmation/diffChecklist/GtConfirmationDiffChecklist.vue')),
    icon: '📊',
    label: '函证差异检查表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-fraud-risk',
    component: defineAsyncComponent(() => import('../../confirmation/fraudRisk/GtConfirmationFraudRisk.vue')),
    icon: '🚨',
    label: '舞弊风险评价表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-reliability',
    component: defineAsyncComponent(() => import('../../confirmation/reliability/GtConfirmationReliability.vue')),
    icon: '🔐',
    label: '回函可靠性验证',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-wealth-list',
    component: defineAsyncComponent(() => import('../../confirmation/wealthList/GtConfirmationWealthList.vue')),
    icon: '💰',
    label: '理财产品发函记录表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-send-list-e03',
    component: defineAsyncComponent(() => import('../../confirmation/e0-send-list/GtE0SendListE03.vue')),
    icon: '✉️',
    label: '发函清单(货币资金)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-send-list-e04',
    component: defineAsyncComponent(() => import('../../confirmation/e0-send-list/GtE0SendListE04.vue')),
    icon: '✉️',
    label: '发函清单(借款)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-send-list-e05',
    component: defineAsyncComponent(() => import('../../confirmation/e0-send-list/GtE0SendListE05.vue')),
    icon: '✉️',
    label: '发函清单(银承)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-alternative-f05',
    component: defineAsyncComponent(() => import('../../confirmation/alternativeF05/GtConfirmationAlternativeF05.vue')),
    icon: '🔄',
    label: '替代程序(预付及采购)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-alternative-f06',
    component: defineAsyncComponent(() => import('../../confirmation/alternativeF06/GtConfirmationAlternativeF06.vue')),
    icon: '🔄',
    label: '替代程序(应付及采购)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-alternative-g06',
    component: defineAsyncComponent(() => import('../../g0-confirmation/alternativeG06/GtConfirmationAlternativeG06.vue')),
    icon: '🔄',
    label: '替代程序(投资循环)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-alternative-h05',
    component: defineAsyncComponent(() => import('../../confirmation/alternativeH05/GtConfirmationAlternativeH05.vue')),
    icon: '🔄',
    label: '替代程序(固定资产循环)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-alternative-k05',
    component: defineAsyncComponent(() => import('../../confirmation/alternativeK05/GtConfirmationAlternativeK05.vue')),
    icon: '🔄',
    label: '替代程序(其他应收款)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-alternative-k06',
    component: defineAsyncComponent(() => import('../../confirmation/alternativeK06/GtConfirmationAlternativeK06.vue')),
    icon: '🔄',
    label: '替代程序(其他应付款)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-alternative-l05',
    component: defineAsyncComponent(() => import('../../confirmation/alternativeL05/GtConfirmationAlternativeL05.vue')),
    icon: '🔄',
    label: '替代程序(债务循环)',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-diff-securities',
    component: defineAsyncComponent(() => import('../../g0-confirmation/diffSecurities/GtConfirmationDiffSecurities.vue')),
    icon: '📈',
    label: '证券差异核对',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'confirmation-diff-nonsecurities',
    component: defineAsyncComponent(() => import('../../g0-confirmation/diffNonSecurities/GtG0DiffNonSecurities.vue')),
    icon: '🏦',
    label: '非证券差异核对',
    emits: ['save'],
    contextProps: 'standard',
  },
]
