import { defineAsyncComponent } from 'vue'
import type { HtmlRendererEntry } from '../types'

/**
 * Explicit HtmlRendererEntry[] for domain: core
 * Membership is this array — no startsWith classifier.
 */
export const coreEntries: HtmlRendererEntry[] = [
  {
    componentType: 'a1-dashboard',
    component: defineAsyncComponent(() => import('../../GtA1Dashboard.vue')),
    icon: '🎯',
    label: 'A1 项目总控仪表盘',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a2-adjustment-console',
    component: defineAsyncComponent(() => import('../../GtA2AdjustmentConsole.vue')),
    icon: '📝',
    label: 'A2 调整分录中控台',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a3-consolidation-console',
    component: defineAsyncComponent(() => import('../../GtA3ConsolidationConsole.vue')),
    icon: '🔗',
    label: 'A3 合并流程中控台',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'b-index',
    component: defineAsyncComponent(() => import('../../GtBIndex.vue')),
    icon: '🗂️',
    label: 'B 底稿目录',
    emits: ['save'],
  },
  {
    componentType: 'c-note-table',
    component: defineAsyncComponent(() => import('../../GtCNoteTable.vue')),
    icon: '📝',
    label: 'C 附注披露嵌套表',
    emits: ['save', 'subtable-toggle', 'standard-switch', 'sync-to-disclosure-notes', 'jump-to-reference', 'open-formula'],
  },
  {
    componentType: 'h-static-doc',
    component: defineAsyncComponent(() => import('../../GtHStaticDoc.vue')),
    icon: '📖',
    label: 'H 辅助说明',
    emits: [],
  },
  {
    componentType: 'custom',
    component: defineAsyncComponent(() => import('../../GtCustomWpEditor.vue')),
    icon: '📎',
    label: '自定义底稿',
    emits: ['save'],
    contextProps: 'custom',
  },
  {
    componentType: 'audit-sheet',
    component: defineAsyncComponent(() => import('../../GtAuditSheet.vue')),
    icon: '📊',
    label: '审定表',
    emits: ['save', 'field-change', 'open-formula', 'restore'],
    contextProps: 'standard',
  },
  {
    componentType: 'bad-debt-sheet',
    component: defineAsyncComponent(() => import('../../GtBadDebtSheet.vue')),
    icon: '💰',
    label: '坏账准备明细表',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'cf-verification',
    component: defineAsyncComponent(() => import('../../CashFlowVerification.vue')),
    icon: '💧',
    label: '现金流量表核查',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'word-template',
    component: defineAsyncComponent(() => import('../../WorkpaperWordEditor.vue')),
    icon: '📄',
    label: 'Word 模板编辑',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'independence-signing',
    component: defineAsyncComponent(() => import('../../IndependenceSigning.vue')),
    icon: '✍️',
    label: '独立性签署',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'wp-popup-signing',
    component: defineAsyncComponent(() => import('../../WpPopupSigning.vue')),
    icon: '✍️',
    label: '签字流转控制表',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'a1-11-signing-form',
    component: defineAsyncComponent(() => import('../../GtA111SigningForm.vue')),
    icon: '✍️',
    label: 'A1-11 签发流转控制表',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'audit-legend',
    component: defineAsyncComponent(() => import('../../AuditLegendPanel.vue')),
    icon: '📋',
    label: '审计标识一览表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'review-bundle',
    component: defineAsyncComponent(() => import('../../GtReviewBundle.vue')),
    icon: '✍️',
    label: '角色复核聚合',
    emits: ['save'],
    contextProps: 'standard',
  },
]
