import { defineAsyncComponent } from 'vue'
import type { HtmlRendererEntry } from '../types'

/**
 * Explicit HtmlRendererEntry[] for domain: programs
 * Membership is this array — no startsWith classifier.
 */
export const programsEntries: HtmlRendererEntry[] = [
  {
    componentType: 'a-program-console',
    component: defineAsyncComponent(() => import('../../GtCycleAProgramRouter.vue')),
    icon: '📋',
    label: 'A 程序表中控台',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'e-control-test',
    component: defineAsyncComponent(() => import('../../GtEControlTest.vue')),
    icon: '🧪',
    label: 'E 控制测试',
    emits: ['save', 'trigger-procedure-trimming-suggestion', 'conclusion-change', 'step-advance'],
    contextProps: 'standard',
  },
  {
    componentType: 'procedure-table',
    component: defineAsyncComponent(() => import('../../ProcedureTableRenderer.vue')),
    icon: '📋',
    label: '程序表',
    emits: ['save'],
    contextProps: 'custom',
  },
  {
    componentType: 'review-checklist',
    component: defineAsyncComponent(() => import('../../GtReviewChecklist.vue')),
    icon: '✍️',
    label: '复核面板',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'checklist-table',
    component: defineAsyncComponent(() => import('../../GtChecklistTable.vue')),
    icon: '✅',
    label: '核对表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a14-3-workbook',
    component: defineAsyncComponent(() => import('../../GtA14_3Workbook.vue')),
    icon: '🖥️',
    label: 'A14-3 IT缺陷',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a10-bundle',
    component: defineAsyncComponent(() => import('../../GtA10Bundle.vue')),
    icon: '📋',
    label: 'A10 前期审计程序',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'a11-bundle',
    component: defineAsyncComponent(() => import('../../GtA11Bundle.vue')),
    icon: '📅',
    label: 'A11 期后事项套件',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a12-bundle',
    component: defineAsyncComponent(() => import('../../GtA12Bundle.vue')),
    icon: '📋',
    label: 'A12 期初余额审计',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'a15-bundle',
    component: defineAsyncComponent(() => import('../../GtA15Bundle.vue')),
    icon: '🔄',
    label: 'A15 持续经营套件',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a16-bundle',
    component: defineAsyncComponent(() => import('../../GtA16Bundle.vue')),
    icon: '📜',
    label: 'A16 管理层声明书',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'a17-bundle',
    component: defineAsyncComponent(() => import('../../GtA17Bundle.vue')),
    icon: '📋',
    label: 'A17 审计总结聚合',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'b50-risk-assessment',
    component: defineAsyncComponent(() => import('../../GtB50RiskAssessment.vue')),
    icon: '🎯',
    label: 'B50 重大错报风险评估',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'b22a-control-matrix',
    component: defineAsyncComponent(() => import('../../GtB22AControlMatrix.vue')),
    icon: '🛡️',
    label: 'B22A 内部控制了解程序表',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'b22b-deficiency-evaluation',
    component: defineAsyncComponent(() => import('../../GtB22BDeficiencyEvaluation.vue')),
    icon: '⚠️',
    label: 'B22B 内部控制缺陷评价表',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'b22b-control-matrix',
    component: defineAsyncComponent(() => import('../../GtB22BControlMatrix.vue')),
    icon: '🗂️',
    label: 'B22B 企业层面控制矩阵登记册',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'b22c-design-effectiveness',
    component: defineAsyncComponent(() => import('../../GtB22CDesignEffectiveness.vue')),
    icon: '📋',
    label: 'B22C 企业层面控制设计有效性评价',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'b23-process-control',
    component: defineAsyncComponent(() => import('../../GtB23ProcessControl.vue')),
    icon: '🔄',
    label: 'B23 业务流程与控制了解表',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'b30-group-audit',
    component: defineAsyncComponent(() => import('../../GtB30GroupAudit.vue')),
    icon: '🏢',
    label: 'B30 集团审计范围确定',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'b2-bundle',
    component: defineAsyncComponent(() => import('../../GtB2Bundle.vue')),
    icon: '📋',
    label: 'B2 业务承接程序',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'b13-bundle',
    component: defineAsyncComponent(() => import('../../GtB13Bundle.vue')),
    icon: '📋',
    label: 'B13 初步分析性程序',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'b19-bundle',
    component: defineAsyncComponent(() => import('../../GtB19Bundle.vue')),
    icon: '📋',
    label: 'B19 审计工作方案',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'b51-bundle',
    component: defineAsyncComponent(() => import('../../GtB51Bundle.vue')),
    icon: '📋',
    label: 'B51 舞弊风险识别',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'b60-strategy',
    component: defineAsyncComponent(() => import('../../b60/GtB60Bundle.vue')),
    icon: '📋',
    label: 'B60 总体审计策略',
    emits: ['save', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'b2-12-evaluation',
    component: defineAsyncComponent(() => import('../../GtB212Evaluation.vue')),
    icon: '🧾',
    label: 'B2-12 对前任注册会计师的评价',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'a1-12-dual-checklist',
    component: defineAsyncComponent(() => import('../../GtA112DualChecklist.vue')),
    icon: '✅',
    label: 'A1-12 重大事项决定程序核查表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a1-15-disclosure-checklist',
    component: defineAsyncComponent(() => import('../../GtA115DisclosureChecklist.vue')),
    icon: '📋',
    label: 'A1-15 企业会计准则财务报表列报及披露核对表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a1-17-corresponding-data',
    component: defineAsyncComponent(() => import('../../GtA117CorrespondingData.vue')),
    icon: '📊',
    label: 'A1-17 对应数据程序表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a17-6-closing-meeting',
    component: defineAsyncComponent(() => import('../../GtA176ClosingMeeting.vue')),
    icon: '📋',
    label: 'A17-6 总结会会议纪要',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a8-1-other-info-representation',
    component: defineAsyncComponent(() => import('../../GtA81OtherInfoRepresentation.vue')),
    icon: '📋',
    label: 'A8-1 管理层对其他信息的书面声明',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a11-1-subsequent-events-inquiry',
    component: defineAsyncComponent(() => import('../../GtA111SubsequentEventsInquiry.vue')),
    icon: '📅',
    label: 'A11-1 期后事项问询函',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a17-3-consultation-record',
    component: defineAsyncComponent(() => import('../../GtA173ConsultationRecord.vue')),
    icon: '📋',
    label: 'A17-3 业务咨询记录',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a17-3-1-consultation-execution',
    component: defineAsyncComponent(() => import('../../GtA1731ConsultationExecution.vue')),
    icon: '📋',
    label: 'A17-3-1 咨询结果执行',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a17-4-disagreement-record',
    component: defineAsyncComponent(() => import('../../GtA174DisagreementRecord.vue')),
    icon: '📋',
    label: 'A17-4 重大专业分歧事项记录',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a17-7-independence-declaration',
    component: defineAsyncComponent(() => import('../../GtA177IndependenceDeclaration.vue')),
    icon: '✍️',
    label: 'A17-7 独立性声明书',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a9-1-deficiency-letter',
    component: defineAsyncComponent(() => import('../../GtA91DeficiencyLetter.vue')),
    icon: '📋',
    label: 'A9-1 内控缺陷沟通函',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a9-2-deficiency-letter-governance',
    component: defineAsyncComponent(() => import('../../GtA91DeficiencyLetter.vue')),
    icon: '📋',
    label: 'A9-2 治理层内控缺陷沟通函',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a27-1-it-audit-memo',
    component: defineAsyncComponent(() => import('../../GtA271ItAuditMemo.vue')),
    icon: '💻',
    label: 'A27-1 IT审计总结备忘录',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a12-1-legal-confirmation',
    component: defineAsyncComponent(() => import('../../GtA121LegalConfirmation.vue')),
    icon: '⚖️',
    label: 'A12-1 法律事务确认函',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a10-1-governance-communication',
    component: defineAsyncComponent(() => import('../../GtA101GovernanceCommunication.vue')),
    icon: '📋',
    label: 'A10-1 与治理层沟通函',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a5-1-cashflow-audit',
    component: defineAsyncComponent(() => import('../../GtA51CashflowAudit.vue')),
    icon: '💰',
    label: 'A5-1 现金流量表审计',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a3-8-goodwill-impairment',
    component: defineAsyncComponent(() => import('../../GtA38GoodwillImpairment.vue')),
    icon: '💠',
    label: 'A3-8 商誉减值测试',
    emits: ['save', 'jump-to-workpaper'],
    contextProps: 'standard',
  },
  {
    componentType: 'b1-risk-assessment',
    component: defineAsyncComponent(() => import('../../GtB1RiskAssessment.vue')),
    icon: '📊',
    label: 'B1-1/B1-2 风险评估表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'b1-3-business-evaluation',
    component: defineAsyncComponent(() => import('../../GtB1Evaluation.vue')),
    icon: '📝',
    label: 'B1-3 业务评价表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'b1-5-kaa-check',
    component: defineAsyncComponent(() => import('../../GtB1KaaCheck.vue')),
    icon: '✅',
    label: 'B1-5 KAA检查表',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'c-control-test',
    component: defineAsyncComponent(() => import('../../GtCControlTest.vue')),
    icon: '🧪',
    label: 'C 控制测试',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'c1-entity-level-control',
    component: defineAsyncComponent(() => import('../../GtC1EntityControl.vue')),
    icon: '🏛️',
    label: 'C1 企业层面控制测试',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'c22-itgc-bundle',
    component: defineAsyncComponent(() => import('../../GtC22ItgcBundle.vue')),
    icon: '💻',
    label: 'C22 IT一般控制测试聚合',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'c23-journal-entry-control',
    component: defineAsyncComponent(() => import('../../GtC23JournalControl.vue')),
    icon: '📋',
    label: 'C23 会计分录控制测试',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'c24-journal-entry-detail',
    component: defineAsyncComponent(() => import('../../GtC24JournalDetail.vue')),
    icon: '🔍',
    label: 'C24 会计分录细节测试',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'c25-internal-audit-reliance',
    component: defineAsyncComponent(() => import('../../GtC25InternalAudit.vue')),
    icon: '🔎',
    label: 'C25 利用内部审计工作',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'c26-info-processing-control',
    component: defineAsyncComponent(() => import('../../GtC26InfoControl.vue')),
    icon: '🛡️',
    label: 'C26 信息处理控制测试',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'f2-stocktake-bundle',
    component: defineAsyncComponent(() => import('../../GtF2StocktakeBundle.vue')),
    icon: '📦',
    label: 'F2 存货监盘',
    emits: [],
    contextProps: 'standard',
  },
]
