import { defineAsyncComponent } from 'vue'
import type { HtmlRendererEntry } from '../types'

/**
 * Explicit HtmlRendererEntry[] for domain: reports
 * Membership is this array — no startsWith classifier.
 */
export const reportsEntries: HtmlRendererEntry[] = [
  {
    componentType: 'report-analysis',
    component: defineAsyncComponent(() => import('../../ReportAnalysisPanel.vue')),
    icon: '📈',
    label: '报表分析',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'misstatement-summary',
    component: defineAsyncComponent(() => import('../../MisstatementSummaryView.vue')),
    icon: '⚠️',
    label: '错报汇总',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 'analytical-review',
    component: defineAsyncComponent(() => import('../../GtAnalyticalReview.vue')),
    icon: '📊',
    label: '分析性复核',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a17-summary',
    component: defineAsyncComponent(() => import('../../GtA17Summary.vue')),
    icon: '📋',
    label: 'A17 重大事项概要',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'kam-workpaper',
    component: defineAsyncComponent(() => import('../../GtKamWorkpaper.vue')),
    icon: '🔑',
    label: 'A17-2-1 关键审计事项',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'regulatory-letter',
    component: defineAsyncComponent(() => import('../../GtRegulatoryLetter.vue')),
    icon: '📮',
    label: 'A18-2 监管沟通函',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'goodwill-impairment',
    component: defineAsyncComponent(() => import('../../GtGoodwillImpairment.vue')),
    icon: '💎',
    label: '商誉减值测试',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'segment-report',
    component: defineAsyncComponent(() => import('../../GtSegmentReport.vue')),
    icon: '🏢',
    label: '经营分部',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'contingent-liability',
    component: defineAsyncComponent(() => import('../../GtContingentLiability.vue')),
    icon: '⚖️',
    label: '或有事项',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'discontinued-operations',
    component: defineAsyncComponent(() => import('../../GtDiscontinuedOperations.vue')),
    icon: '📉',
    label: '终止经营',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'misstatement-workpaper',
    component: defineAsyncComponent(() => import('../../GtMisstatementWorkpaper.vue')),
    icon: '⚠️',
    label: 'A13 错报套件',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a18-1-regulatory-submission',
    component: defineAsyncComponent(() => import('../../GtA181RegulatorySubmission.vue')),
    icon: '📨',
    label: 'A18-1 向监管部门报送审计小结',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a18-2-regulatory-communication',
    component: defineAsyncComponent(() => import('../../GtA182RegulatoryCommunication.vue')),
    icon: '📮',
    label: 'A18-2 与监管层沟通函',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a17-1-audit-summary',
    component: defineAsyncComponent(() => import('../../GtA171AuditSummary.vue')),
    icon: '📋',
    label: 'A17-1 重大事项概要汇总',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'a17-2-1-kam',
    component: defineAsyncComponent(() => import('../../GtA1721Kam.vue')),
    icon: '🔑',
    label: 'A17-2-1 关键审计事项',
    emits: ['save'],
    contextProps: 'standard',
  },
  {
    componentType: 'b1-4-due-diligence-report',
    component: defineAsyncComponent(() => import('../../GtB14DueDiligenceReport.vue')),
    icon: '📋',
    label: 'B1-4 尽职调查报告',
    emits: ['save'],
    contextProps: 'standard',
  },
]
