import { defineAsyncComponent } from 'vue'
import type { HtmlRendererEntry } from '../types'

/**
 * Explicit HtmlRendererEntry[] for domain: specialized
 * Membership is this array — no startsWith classifier.
 */
export const specializedEntries: HtmlRendererEntry[] = [
  {
    componentType: 'e1-monetary-fund',
    component: defineAsyncComponent(() => import('../../GtE1MonetaryFund.vue')),
    icon: '💵',
    label: 'E1 货币资金',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'f1-prepayment',
    component: defineAsyncComponent(() => import('../../GtF1Prepayment.vue')),
    icon: '💳',
    label: 'F1 预付账款',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'f2-inventory-main',
    component: defineAsyncComponent(() => import('../../GtF2InventoryMain.vue')),
    icon: '📦',
    label: 'F2 存货核心',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'f2-inventory-special',
    component: defineAsyncComponent(() => import('../../GtF2InventorySpecial.vue')),
    icon: '📦',
    label: 'F2 存货特殊',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'f2-inventory-valuation-impairment',
    component: defineAsyncComponent(() => import('../../GtF2InventoryValuation.vue')),
    icon: '📦',
    label: 'F2 计价减值',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'f3-notes-payable',
    component: defineAsyncComponent(() => import('../../GtF3NotesPayable.vue')),
    icon: '📄',
    label: 'F3 应付票据',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'f4-accounts-payable',
    component: defineAsyncComponent(() => import('../../GtF4AccountsPayable.vue')),
    icon: '📋',
    label: 'F4 应付账款',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'f5-cost-of-sales',
    component: defineAsyncComponent(() => import('../../GtF5CostOfSales.vue')),
    icon: '📊',
    label: 'F5 营业成本',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g1-trading-financial-assets',
    component: defineAsyncComponent(() => import('../../GtG1TradingFinancialAssets.vue')),
    icon: '📈',
    label: 'G1 交易性金融资产',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g2-interest-receivable',
    component: defineAsyncComponent(() => import('../../GtG2InterestReceivable.vue')),
    icon: '💰',
    label: 'G2 应收利息',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g3-dividend-receivable',
    component: defineAsyncComponent(() => import('../../GtG3DividendReceivable.vue')),
    icon: '💰',
    label: 'G3 应收股利',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g4-bond-investment-ecl',
    component: defineAsyncComponent(() => import('../../GtG4BondInvestmentEcl.vue')),
    icon: '🏦',
    label: 'G4 ECL',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g4-bond-investment-main',
    component: defineAsyncComponent(() => import('../../GtG4BondInvestmentMain.vue')),
    icon: '🏦',
    label: 'G4 债权投资',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g4-bond-investment-sppi',
    component: defineAsyncComponent(() => import('../../GtG4BondInvestmentSppi.vue')),
    icon: '🏦',
    label: 'G4 SPPI',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g5-long-term-receivable',
    component: defineAsyncComponent(() => import('../../GtG5LongTermReceivable.vue')),
    icon: '📑',
    label: 'G5 长期应收款',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g6-other-bond-investment-ecl',
    component: defineAsyncComponent(() => import('../../GtG6OtherBondInvestmentEcl.vue')),
    icon: '🏦',
    label: 'G6 ECL',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g6-other-bond-investment-main',
    component: defineAsyncComponent(() => import('../../GtG6OtherBondMain.vue')),
    icon: '📊',
    label: 'G6 其他债权投资',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g6-other-bond-investment-sppi',
    component: defineAsyncComponent(() => import('../../GtG6OtherBondSppi.vue')),
    icon: '🔬',
    label: 'G6 SPPI',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g7-long-term-equity-main',
    component: defineAsyncComponent(() => import('../../GtG7LongTermEquityMain.vue')),
    icon: '🏢',
    label: 'G7 长期股权投资',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g7-long-term-equity-method',
    component: defineAsyncComponent(() => import('../../GtG7EquityMethod.vue')),
    icon: '🏢',
    label: 'G7 权益法',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g7-long-term-equity-subsidiary',
    component: defineAsyncComponent(() => import('../../GtG7EquitySubsidiary.vue')),
    icon: '🏢',
    label: 'G7 子公司',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g8-other-equity-instruments',
    component: defineAsyncComponent(() => import('../../GtG8OtherEquityInstruments.vue')),
    icon: '📈',
    label: 'G8 其他权益工具',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g9-other-noncurrent-financial',
    component: defineAsyncComponent(() => import('../../GtG9OtherNoncurrentFinancial.vue')),
    icon: '📈',
    label: 'G9 其他非流动金融',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g10-trading-financial-liabilities',
    component: defineAsyncComponent(() => import('../../GtG10TradingFinancialLiabilities.vue')),
    icon: '📉',
    label: 'G10 交易性金融负债',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g11-investment-income',
    component: defineAsyncComponent(() => import('../../GtG11InvestmentIncome.vue')),
    icon: '💹',
    label: 'G11 投资收益',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g12-net-hedge-gains',
    component: defineAsyncComponent(() => import('../../GtG12NetHedgeGains.vue')),
    icon: '🛡️',
    label: 'G12 套期收益',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g13-fair-value-changes',
    component: defineAsyncComponent(() => import('../../GtG13FairValueChanges.vue')),
    icon: '📊',
    label: 'G13 公允价值变动',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'g14-credit-impairment-loss',
    component: defineAsyncComponent(() => import('../../GtG14CreditImpairmentLoss.vue')),
    icon: '⚠️',
    label: 'G14 信用减值损失',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'h1-fixed-assets',
    component: defineAsyncComponent(() => import('../../GtH1FixedAssets.vue')),
    icon: '🏗️',
    label: 'H1 固定资产',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'h2-construction-in-progress',
    component: defineAsyncComponent(() => import('../../GtH2ConstructionInProgress.vue')),
    icon: '🚧',
    label: 'H2 在建工程',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'h3-investment-property',
    component: defineAsyncComponent(() => import('../../GtH3InvestmentProperty.vue')),
    icon: '🏠',
    label: 'H3 投资性房地产',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'h4-engineering-materials',
    component: defineAsyncComponent(() => import('../../GtH4EngineeringMaterials.vue')),
    icon: '🧱',
    label: 'H4 工程物资',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'h5-oil-gas-assets',
    component: defineAsyncComponent(() => import('../../GtH5OilGasAssets.vue')),
    icon: '🛢️',
    label: 'H5 油气资产',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'h7-biological-assets',
    component: defineAsyncComponent(() => import('../../GtH7BiologicalAssets.vue')),
    icon: '🌱',
    label: 'H7 生产性生物资产',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'h6-asset-disposal-clearing',
    component: defineAsyncComponent(() => import('../../GtH6AssetDisposalClearing.vue')),
    icon: '🧹',
    label: 'H6 固定资产清理',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'h8-right-of-use-assets',
    component: defineAsyncComponent(() => import('../../GtH8RightOfUseAssets.vue')),
    icon: '📑',
    label: 'H8 使用权资产',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'h9-lease-liabilities',
    component: defineAsyncComponent(() => import('../../GtH9LeaseLiabilities.vue')),
    icon: '📋',
    label: 'H9 租赁负债',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'h10-asset-disposal-income',
    component: defineAsyncComponent(() => import('../../GtH10AssetDisposalIncome.vue')),
    icon: '🏭',
    label: 'H10 资产处置损益',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'i1-intangible-assets',
    component: defineAsyncComponent(() => import('../../GtI1IntangibleAssets.vue')),
    icon: '💎',
    label: 'I1 无形资产',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'i2-development-expenditure',
    component: defineAsyncComponent(() => import('../../GtI2DevelopmentExpenditure.vue')),
    icon: '🔬',
    label: 'I2 开发支出',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'i3-goodwill',
    component: defineAsyncComponent(() => import('../../GtI3Goodwill.vue')),
    icon: '💎',
    label: 'I3 商誉',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'i4-long-term-prepaid',
    component: defineAsyncComponent(() => import('../../GtI4LongTermPrepaid.vue')),
    icon: '📋',
    label: 'I4 长期待摊费用',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'i5-other-noncurrent-assets',
    component: defineAsyncComponent(() => import('../../GtI5OtherNoncurrentAssets.vue')),
    icon: '📋',
    label: 'I5 其他非流动资产',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'i6-research-development-expense',
    component: defineAsyncComponent(() => import('../../GtI6ResearchDevelopmentExpense.vue')),
    icon: '🔬',
    label: 'I6 研发费用',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'j1-employee-compensation',
    component: defineAsyncComponent(() => import('../../j1/GtJ1EmployeeCompensation.vue')),
    icon: '👥',
    label: 'J1 应付职工薪酬',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'j2-defined-benefit-plan',
    component: defineAsyncComponent(() => import('../../j2/GtJ2DefinedBenefitPlan.vue')),
    icon: '🏥',
    label: 'J2 设定受益计划',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'j3-share-based-payment',
    component: defineAsyncComponent(() => import('../../j3/GtJ3ShareBasedPayment.vue')),
    icon: '📊',
    label: 'J3 股份支付',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k1-other-receivables',
    component: defineAsyncComponent(() => import('../../GtK1OtherReceivables.vue')),
    icon: '💰',
    label: 'K1 其他应收款',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k2-other-current-assets',
    component: defineAsyncComponent(() => import('../../GtK2OtherCurrentAssets.vue')),
    icon: '📋',
    label: 'K2 其他流动资产',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k3-other-payables',
    component: defineAsyncComponent(() => import('../../GtK3OtherPayables.vue')),
    icon: '💳',
    label: 'K3 其他应付款',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k4-other-current-liabilities',
    component: defineAsyncComponent(() => import('../../GtK4OtherCurrentLiabilities.vue')),
    icon: '📋',
    label: 'K4 其他流动负债',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k5-provisions',
    component: defineAsyncComponent(() => import('../../GtK5Provisions.vue')),
    icon: '⚖️',
    label: 'K5 预计负债',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k6-held-for-sale',
    component: defineAsyncComponent(() => import('../../GtK6HeldForSale.vue')),
    icon: '🏷️',
    label: 'K6 持有待售',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k7-deferred-income',
    component: defineAsyncComponent(() => import('../../GtK7DeferredIncome.vue')),
    icon: '📋',
    label: 'K7 递延收益',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k8-selling-expenses',
    component: defineAsyncComponent(() => import('../../GtK8SellingExpenses.vue')),
    icon: '💰',
    label: 'K8 销售费用',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k9-admin-expenses',
    component: defineAsyncComponent(() => import('../../GtK9AdminExpenses.vue')),
    icon: '🏢',
    label: 'K9 管理费用',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k11-asset-impairment-loss',
    component: defineAsyncComponent(() => import('../../GtK11AssetImpairmentLoss.vue')),
    icon: '📉',
    label: 'K11 资产减值损失',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k10-other-income',
    component: defineAsyncComponent(() => import('../../GtK10OtherIncome.vue')),
    icon: '🏛️',
    label: 'K10 其他收益',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k12-non-operating-income',
    component: defineAsyncComponent(() => import('../../GtK12NonOperatingIncome.vue')),
    icon: '🎁',
    label: 'K12 营业外收入',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'k13-non-operating-expense',
    component: defineAsyncComponent(() => import('../../GtK13NonOperatingExpense.vue')),
    icon: '💸',
    label: 'K13 营业外支出',
    emits: ['save', 'completed', 'navigate-sheet'],
    contextProps: 'standard',
  },
  {
    componentType: 'l1-short-term-loans',
    component: defineAsyncComponent(() => import('../../GtL1ShortTermLoans.vue')),
    icon: '🏦',
    label: 'L1 短期借款',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'l2-interest-payable',
    component: defineAsyncComponent(() => import('../../GtL2InterestPayable.vue')),
    icon: '💸',
    label: 'L2 应付利息',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'l3-long-term-loans',
    component: defineAsyncComponent(() => import('../../GtL3LongTermLoans.vue')),
    icon: '🏛️',
    label: 'L3 长期借款',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'l4-bonds-payable',
    component: defineAsyncComponent(() => import('../../GtL4BondsPayable.vue')),
    icon: '📜',
    label: 'L4 应付债券',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'l5-long-term-payables',
    component: defineAsyncComponent(() => import('../../GtL5LongTermPayables.vue')),
    icon: '💳',
    label: 'L5 长期应付款',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'l6-special-payables',
    component: defineAsyncComponent(() => import('../../GtL6SpecialPayables.vue')),
    icon: '🏛️',
    label: 'L6 专项应付款',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'l7-other-noncurrent-liabilities',
    component: defineAsyncComponent(() => import('../../GtL7OtherNoncurrentLiabilities.vue')),
    icon: '📋',
    label: 'L7 其他非流动负债',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'l8-financial-expenses',
    component: defineAsyncComponent(() => import('../../GtL8FinancialExpenses.vue')),
    icon: '💰',
    label: 'L8 财务费用',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm1-dividends-payable',
    component: defineAsyncComponent(() => import('../../GtM1DividendsPayable.vue')),
    icon: '💸',
    label: 'M1 应付股利',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm2-paid-in-capital',
    component: defineAsyncComponent(() => import('../../GtM2PaidInCapital.vue')),
    icon: '🏦',
    label: 'M2 实收资本（股本）',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm3-treasury-stock',
    component: defineAsyncComponent(() => import('../../GtM3TreasuryStock.vue')),
    icon: '📦',
    label: 'M3 库存股',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm4-capital-reserve',
    component: defineAsyncComponent(() => import('../../GtM4CapitalReserve.vue')),
    icon: '💰',
    label: 'M4 资本公积',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm5-surplus-reserve',
    component: defineAsyncComponent(() => import('../../GtM5SurplusReserve.vue')),
    icon: '📊',
    label: 'M5 盈余公积',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm6-retained-earnings',
    component: defineAsyncComponent(() => import('../../GtM6RetainedEarnings.vue')),
    icon: '💰',
    label: 'M6 未分配利润',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm7-special-reserve',
    component: defineAsyncComponent(() => import('../../GtM7SpecialReserve.vue')),
    icon: '🛡️',
    label: 'M7 专项储备',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm8-general-risk-reserve',
    component: defineAsyncComponent(() => import('../../GtM8GeneralRiskReserve.vue')),
    icon: '⚠️',
    label: 'M8 一般风险准备',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm9-other-comprehensive-income',
    component: defineAsyncComponent(() => import('../../GtM9OtherComprehensiveIncome.vue')),
    icon: '🌈',
    label: 'M9 其他综合收益',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'm10-other-equity-instruments',
    component: defineAsyncComponent(() => import('../../GtM10OtherEquityInstruments.vue')),
    icon: '📜',
    label: 'M10 其他权益工具',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'n1-deferred-tax-assets',
    component: defineAsyncComponent(() => import('../../GtN1DeferredTaxAssets.vue')),
    icon: '🧾',
    label: 'N1 递延所得税资产',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'n2-taxes-payable',
    component: defineAsyncComponent(() => import('../../GtN2TaxesPayable.vue')),
    icon: '🧾',
    label: 'N2 应交税费',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'n3-deferred-tax-liabilities',
    component: defineAsyncComponent(() => import('../../GtN3DeferredTaxLiabilities.vue')),
    icon: '🧾',
    label: 'N3 递延所得税负债',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'n4-taxes-and-surcharges',
    component: defineAsyncComponent(() => import('../../GtN4TaxesAndSurcharges.vue')),
    icon: '🧾',
    label: 'N4 税金及附加',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 'n5-income-tax-expense',
    component: defineAsyncComponent(() => import('../../GtN5IncomeTaxExpense.vue')),
    icon: '🧾',
    label: 'N5 所得税费用',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's3-policy-change',
    component: defineAsyncComponent(() => import('../../s3-policy-change/GtS3PolicyChange.vue')),
    icon: '📋',
    label: 'S3 会计政策变更',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's4-nonmonetary-exchange',
    component: defineAsyncComponent(() => import('../../s4-nonmonetary-exchange/GtS4NonmonetaryExchange.vue')),
    icon: '🔄',
    label: 'S4 非货币性资产交换',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's5-debt-restructuring',
    component: defineAsyncComponent(() => import('../../s5-debt-restructuring/GtS5DebtRestructuring.vue')),
    icon: '📑',
    label: 'S5 债务重组',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's6-fund-occupation',
    component: defineAsyncComponent(() => import('../../s6-fund-occupation/GtS6FundOccupation.vue')),
    icon: '💰',
    label: 'S6 资金占用',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's12-cpa-expert',
    component: defineAsyncComponent(() => import('../../s12-cpa-expert/GtS12CpaExpert.vue')),
    icon: '👨‍💼',
    label: 'S12 注册会计师专家',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's13-mgmt-expert',
    component: defineAsyncComponent(() => import('../../s13-mgmt-expert/GtS13MgmtExpert.vue')),
    icon: '👨‍💻',
    label: 'S13 管理层专家',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's14-accounting-estimate',
    component: defineAsyncComponent(() => import('../../s14-accounting-estimate/GtS14AccountingEstimate.vue')),
    icon: '🧮',
    label: 'S14 会计估计',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's15-eps-roe',
    component: defineAsyncComponent(() => import('../../s15-eps-roe/GtS15EpsRoe.vue')),
    icon: '📊',
    label: 'S15 每股收益与净资产收益率',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's20-revenue-deduction',
    component: defineAsyncComponent(() => import('../../s20-revenue-deduction/GtS20RevenueDeduction.vue')),
    icon: '💹',
    label: 'S20 营业收入扣除',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's21-data-asset',
    component: defineAsyncComponent(() => import('../../s21-data-asset/GtS21DataAsset.vue')),
    icon: '💾',
    label: 'S21 数据资产',
    emits: ['save', 'completed'],
    contextProps: 'standard',
  },
  {
    componentType: 's32-fraud-bundle',
    component: defineAsyncComponent(() => import('../../s32-fraud-bundle/GtS32Bundle.vue')),
    icon: '🚨',
    label: 'S32 舞弊核查聚合',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 's33-ann14-bundle',
    component: defineAsyncComponent(() => import('../../s33-ann14-bundle/GtS33Bundle.vue')),
    icon: '📋',
    label: 'S33 14号公告核查聚合',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 's34-ipo-bundle',
    component: defineAsyncComponent(() => import('../../s34-ipo-bundle/GtS34Bundle.vue')),
    icon: '📋',
    label: 'S34 首发审核特项核查聚合',
    emits: [],
    contextProps: 'standard',
  },
  {
    componentType: 's35-refinance-bundle',
    component: defineAsyncComponent(() => import('../../s35-refinance-bundle/GtS35Bundle.vue')),
    icon: '📋',
    label: 'S35 再融资审核特项核查聚合',
    emits: [],
    contextProps: 'standard',
  },
]
