/**
 * B60 默认章节定义数组（前端内置降级数据源）
 *
 * 当后端 API `GET /api/b60/chapter-definitions` 10 秒超时或返回非 2xx 时，
 * GtB60Bundle 使用此数组作为降级章节定义。
 *
 * 与后端 `backend/app/data/b60_chapter_definitions.json` 保持同步。
 *
 * Requirements: 4.3
 */
import type { ChapterDefinition } from '../composables/useB60FormData'

export const DEFAULT_CHAPTER_DEFINITIONS: ChapterDefinition[] = [
  {
    chapter_id: 'B60-CH-01',
    title: '总体审计策略概述',
    level: 1,
    required: true,
    hint: '概述本次审计的总体策略，包括审计目标、审计范围的初步确定、审计方向及重点领域的总体考虑。应结合被审计单位的行业特征、经营规模、内部控制状况等因素，说明审计策略制定的主要依据和逻辑。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-02',
    title: '重大关注事项与风险领域',
    level: 1,
    required: true,
    hint: '识别并记录本次审计需重点关注的事项和风险领域，包括但不限于：重大错报风险（财务报表层次和认定层次）、舞弊风险、关联方交易风险、持续经营风险、会计估计和公允价值计量等高风险领域。应引用风险评估底稿（B50）的结论。',
    data_source: { label: 'B50 风险评估', wp_code: 'B50' },
  },
  {
    chapter_id: 'B60-CH-03',
    title: '财务报表层次重大错报风险',
    level: 2,
    required: true,
    hint: '描述已识别的财务报表层次重大错报风险及其性质，包括管理层凌驾于内部控制之上的风险、舞弊导致收入确认的重大错报风险等。说明针对这些风险拟采取的总体应对措施。',
    data_source: { label: 'B50 风险评估', wp_code: 'B50' },
  },
  {
    chapter_id: 'B60-CH-04',
    title: '认定层次重大错报风险',
    level: 2,
    required: true,
    hint: '列示已识别的认定层次重大错报风险，按交易类别、账户余额和披露分类，说明风险涉及的具体认定及评估为重大风险的原因。',
    data_source: { label: 'B50 风险评估', wp_code: 'B50' },
  },
  {
    chapter_id: 'B60-CH-05',
    title: '审计方法与应对措施',
    level: 1,
    required: true,
    hint: '说明针对已识别风险拟采取的审计方法和具体应对措施，包括控制测试与实质性程序的组合策略、分析性程序的运用计划、函证程序的安排等。对于特别风险，应说明专门设计的进一步审计程序。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-06',
    title: '控制测试策略',
    level: 2,
    required: false,
    hint: '说明是否计划实施控制测试及其范围。如计划信赖内部控制，描述拟测试的关键控制及测试方法；如不计划信赖内部控制，说明原因及替代的实质性程序安排。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-07',
    title: '实质性程序策略',
    level: 2,
    required: true,
    hint: '概述各重要科目拟实施的实质性程序类型（细节测试或实质性分析程序），说明程序设计与风险评估结论的对应关系。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-08',
    title: '审计范围',
    level: 1,
    required: true,
    hint: '明确本次审计的范围，包括：审计期间、合并范围内的组成部分及其重要性、是否涉及组成部分审计师、特殊目的审计范围的排除或限制等。对于集团审计，应说明各组成部分的分类及拟执行工作的类型。',
    data_source: { label: 'B10 项目基本信息', wp_code: 'B10' },
  },
  {
    chapter_id: 'B60-CH-09',
    title: '合并范围与组成部分',
    level: 2,
    required: false,
    hint: '列示纳入合并范围的组成部分清单，标注重要组成部分及其判断依据（资产/收入/利润占比），说明对各组成部分拟执行的审计工作类型。',
    data_source: { label: 'B10 项目基本信息', wp_code: 'B10' },
  },
  {
    chapter_id: 'B60-CH-10',
    title: '时间安排与关键节点',
    level: 1,
    required: true,
    hint: '制定审计工作的时间安排计划，包括：现场审计开始和结束日期、中期审计安排、期末审计安排、出具审计报告的目标日期等关键时间节点。说明时间安排与被审计单位财务报告编制进度的协调情况。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-11',
    title: '中期审计安排',
    level: 2,
    required: false,
    hint: '如安排中期审计，说明中期审计的时间、范围和目标，包括拟在中期完成的控制测试和实质性程序，以及中期审计结论对期末审计程序的影响。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-12',
    title: '期末审计安排',
    level: 2,
    required: true,
    hint: '说明期末审计的具体时间安排、各阶段工作内容及交付物要求，包括盘点安排、函证截止日期、期后事项审阅期间等。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-13',
    title: '审计资源分配',
    level: 1,
    required: true,
    hint: '说明审计项目组的人员配置、各成员的职责分工及专业胜任能力要求。包括项目合伙人、项目经理、审计助理的具体分工，是否需要利用专家及其安排。应考虑项目的复杂程度和风险水平进行合理配置。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-14',
    title: '项目组成员及职责',
    level: 2,
    required: true,
    hint: '列示项目组核心成员名单、专业资质、承担的审计领域及预计投入工时。说明项目合伙人对关键审计领域的参与程度和复核安排。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-15',
    title: '专家利用计划',
    level: 2,
    required: false,
    hint: '说明是否计划利用审计师的专家或管理层的专家，专家的领域（如IT审计、资产评估、精算、税务等），利用专家工作的范围及对专家能力、客观性和独立性的评价安排。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-16',
    title: '重要性水平确定',
    level: 1,
    required: true,
    hint: '记录财务报表整体重要性水平、实际执行的重要性水平及明显微小错报临界值的确定过程和依据。应说明选取的基准及百分比的确定理由，以及对特定交易类别或账户余额是否需要确定更低的重要性水平。',
    data_source: { label: 'B15 重要性', wp_code: 'B15' },
  },
  {
    chapter_id: 'B60-CH-17',
    title: '整体重要性水平',
    level: 2,
    required: true,
    hint: '记录整体重要性水平的金额、选取的基准及百分比，说明基准选取的合理性。如基准数据存在波动，说明如何进行正常化调整。',
    data_source: { label: 'B15 重要性', wp_code: 'B15' },
  },
  {
    chapter_id: 'B60-CH-18',
    title: '实际执行的重要性',
    level: 2,
    required: true,
    hint: '记录实际执行的重要性水平金额及其与整体重要性的比例（通常为50%-75%），说明确定比例时考虑的因素。',
    data_source: { label: 'B15 重要性', wp_code: 'B15' },
  },
  {
    chapter_id: 'B60-CH-19',
    title: '特定项目重要性',
    level: 3,
    required: false,
    hint: '如存在特定交易类别、账户余额或披露需要确定更低的重要性水平（如关联方交易、管理层薪酬披露等），记录其金额和确定依据。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-20',
    title: '审计风险概述',
    level: 1,
    required: true,
    hint: '概述本次审计面临的主要风险，包括固有风险、控制风险和检查风险的总体评估。说明审计风险模型的运用情况，以及如何通过调整审计程序将审计风险降至可接受的低水平。',
    data_source: { label: 'B50 风险评估', wp_code: 'B50' },
  },
  {
    chapter_id: 'B60-CH-21',
    title: '固有风险因素',
    level: 2,
    required: true,
    hint: '描述影响固有风险评估的关键因素，包括行业和监管环境特征、被审计单位的性质、会计政策的选择和运用、交易的复杂程度等。',
    data_source: { label: 'B50 风险评估', wp_code: 'B50' },
  },
  {
    chapter_id: 'B60-CH-22',
    title: '控制环境评估',
    level: 2,
    required: true,
    hint: '概述对被审计单位控制环境的总体评价，包括治理层的监督、管理层的理念和经营风格、组织结构等。说明控制环境评估对审计策略的影响。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-23',
    title: '舞弊风险评估',
    level: 3,
    required: true,
    hint: '记录舞弊风险评估的结论，包括管理层凌驾于内部控制之上的风险（推定存在）、收入确认舞弊风险的考虑、舞弊三角分析，以及针对舞弊风险设计的审计程序。',
    data_source: { label: 'B50 风险评估', wp_code: 'B50' },
  },
  {
    chapter_id: 'B60-CH-24',
    title: '其他需关注事项',
    level: 1,
    required: false,
    hint: '记录上述各章节未涵盖但对本次审计有重要影响的其他事项，包括但不限于：与管理层和治理层的沟通安排、审计质量控制措施、连续审计中上年度遗留事项的跟进、监管环境变化的影响等。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-25',
    title: '与治理层沟通事项',
    level: 2,
    required: false,
    hint: '列示计划与治理层沟通的重要审计事项，包括审计范围和时间安排、审计中发现的重大问题、内部控制缺陷等。',
    data_source: null,
  },
  {
    chapter_id: 'B60-CH-26',
    title: '质量控制措施',
    level: 2,
    required: false,
    hint: '说明本项目拟采取的质量控制措施，包括项目质量控制复核（EQCR）的安排、关键审计判断的复核机制、底稿复核的层级和时间安排等。',
    data_source: null,
  },
]
